/// <summary>
/// Name: System::Diagnostics::ConditionalAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Diagnostics {
class ConditionalAttribute {
public:
    inline static _TypePtr _ConditionalAttribute;
};
}
