/// <summary>
/// Name: System::Diagnostics::DebuggerBrowsableAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Diagnostics {
class DebuggerBrowsableAttribute {
public:
    inline static _TypePtr _DebuggerBrowsableAttribute;
};
}
