/// <summary>
/// Name: System::Diagnostics::DebuggerBrowsableState
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Diagnostics {
class DebuggerBrowsableState {
public:
    inline static _TypePtr _DebuggerBrowsableState;
};
}
