/// <summary>
/// Name: System::Diagnostics::Debugger
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Diagnostics {
class Debugger {
public:
    inline static _TypePtr _Debugger;
};
}
