/// <summary>
/// Name: System::Diagnostics::DebuggerDisplayAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Diagnostics {
class DebuggerDisplayAttribute {
public:
    inline static _TypePtr _DebuggerDisplayAttribute;
};
}
