/// <summary>
/// Name: System::Diagnostics::DebuggableAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Diagnostics {
class DebuggableAttribute {
public:
    inline static _TypePtr _DebuggableAttribute;
};
}
