/// <summary>
/// Name: System::Diagnostics::DebuggerStepThroughAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Diagnostics {
class DebuggerStepThroughAttribute {
public:
    inline static _TypePtr _DebuggerStepThroughAttribute;
};
}
