/// <summary>
/// Name: System::Diagnostics::DebuggerTypeProxyAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Diagnostics {
class DebuggerTypeProxyAttribute {
public:
    inline static _TypePtr _DebuggerTypeProxyAttribute;
};
}
