/// <summary>
/// Name: System::Diagnostics::DebuggerStepperBoundaryAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Diagnostics {
class DebuggerStepperBoundaryAttribute {
public:
    inline static _TypePtr _DebuggerStepperBoundaryAttribute;
};
}
