/// <summary>
/// Name: System::Diagnostics::DebuggerVisualizerAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Diagnostics {
class DebuggerVisualizerAttribute {
public:
    inline static _TypePtr _DebuggerVisualizerAttribute;
};
}
