/// <summary>
/// Name: System::Diagnostics::DebuggerNonUserCodeAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Diagnostics {
class DebuggerNonUserCodeAttribute {
public:
    inline static _TypePtr _DebuggerNonUserCodeAttribute;
};
}
