/// <summary>
/// Name: System::Diagnostics::DebuggerHiddenAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Diagnostics {
class DebuggerHiddenAttribute {
public:
    inline static _TypePtr _DebuggerHiddenAttribute;
};
}
