/// <summary>
/// Name: System::Diagnostics::StackTrace
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Diagnostics {
class StackTrace {
public:
    inline static _TypePtr _StackTrace;
};
}
