/// <summary>
/// Name: System::Runtime::InteropServices::ComTypes::DESCKIND
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices::ComTypes {
class DESCKIND {
public:
    inline static _TypePtr _DESCKIND;
};
}
