/// <summary>
/// Name: System::Runtime::InteropServices::ComTypes::ELEMDESC
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices::ComTypes {
class ELEMDESC {
public:
    inline static _TypePtr _ELEMDESC;
};
}
