/// <summary>
/// Name: System::Runtime::InteropServices::ComTypes::EXCEPINFO
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices::ComTypes {
class EXCEPINFO {
public:
    inline static _TypePtr _EXCEPINFO;
};
}
