/// <summary>
/// Name: System::Runtime::InteropServices::ComTypes::FUNCFLAGS
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices::ComTypes {
class FUNCFLAGS {
public:
    inline static _TypePtr _FUNCFLAGS;
};
}
