/// <summary>
/// Name: System::Runtime::InteropServices::ComTypes::FUNCDESC
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices::ComTypes {
class FUNCDESC {
public:
    inline static _TypePtr _FUNCDESC;
};
}
