/// <summary>
/// Name: System::Runtime::InteropServices::ComTypes::IBindCtx
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices::ComTypes {
class IBindCtx {
public:
    inline static _TypePtr _IBindCtx;
};
}
