/// <summary>
/// Name: System::Runtime::InteropServices::ComTypes::IConnectionPointContainer
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices::ComTypes {
class IConnectionPointContainer {
public:
    inline static _TypePtr _IConnectionPointContainer;
};
}
