/// <summary>
/// Name: System::Runtime::InteropServices::ComTypes::IConnectionPoint
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices::ComTypes {
class IConnectionPoint {
public:
    inline static _TypePtr _IConnectionPoint;
};
}
