/// <summary>
/// Name: System::Runtime::InteropServices::ComTypes::IEnumConnectionPoints
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices::ComTypes {
class IEnumConnectionPoints {
public:
    inline static _TypePtr _IEnumConnectionPoints;
};
}
