/// <summary>
/// Name: System::Runtime::InteropServices::ComTypes::IEnumVARIANT
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices::ComTypes {
class IEnumVARIANT {
public:
    inline static _TypePtr _IEnumVARIANT;
};
}
