/// <summary>
/// Name: System::Runtime::InteropServices::ComTypes::IEnumConnections
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices::ComTypes {
class IEnumConnections {
public:
    inline static _TypePtr _IEnumConnections;
};
}
