/// <summary>
/// Name: System::Runtime::InteropServices::ComTypes::IEnumMoniker
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices::ComTypes {
class IEnumMoniker {
public:
    inline static _TypePtr _IEnumMoniker;
};
}
