/// <summary>
/// Name: System::Runtime::InteropServices::ComTypes::IPersistFile
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices::ComTypes {
class IPersistFile {
public:
    inline static _TypePtr _IPersistFile;
};
}
