/// <summary>
/// Name: System::Runtime::InteropServices::ComTypes::IRunningObjectTable
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices::ComTypes {
class IRunningObjectTable {
public:
    inline static _TypePtr _IRunningObjectTable;
};
}
