/// <summary>
/// Name: System::Runtime::InteropServices::ComTypes::IStream
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices::ComTypes {
class IStream {
public:
    inline static _TypePtr _IStream;
};
}
