/// <summary>
/// Name: System::Runtime::InteropServices::ComTypes::ITypeInfo
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices::ComTypes {
class ITypeInfo {
public:
    inline static _TypePtr _ITypeInfo;
};
}
