/// <summary>
/// Name: System::Runtime::InteropServices::ComTypes::ITypeComp
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices::ComTypes {
class ITypeComp {
public:
    inline static _TypePtr _ITypeComp;
};
}
