/// <summary>
/// Name: System::Runtime::InteropServices::ComTypes::ITypeLib
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices::ComTypes {
class ITypeLib {
public:
    inline static _TypePtr _ITypeLib;
};
}
