/// <summary>
/// Name: System::Runtime::InteropServices::ComTypes::STATSTG
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices::ComTypes {
class STATSTG {
public:
    inline static _TypePtr _STATSTG;
};
}
