/// <summary>
/// Name: System::Runtime::InteropServices::ComTypes::TYPEKIND
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices::ComTypes {
class TYPEKIND {
public:
    inline static _TypePtr _TYPEKIND;
};
}
