/// <summary>
/// Name: System::Runtime::InteropServices::ComTypes::TYPEFLAGS
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices::ComTypes {
class TYPEFLAGS {
public:
    inline static _TypePtr _TYPEFLAGS;
};
}
