/// <summary>
/// Name: System::Runtime::InteropServices::ComTypes::TYPEDESC
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices::ComTypes {
class TYPEDESC {
public:
    inline static _TypePtr _TYPEDESC;
};
}
