/// <summary>
/// Name: System::Runtime::InteropServices::ComTypes::TYPEATTR
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices::ComTypes {
class TYPEATTR {
public:
    inline static _TypePtr _TYPEATTR;
};
}
