/// <summary>
/// Name: System::Runtime::InteropServices::ComTypes::TYPELIBATTR
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices::ComTypes {
class TYPELIBATTR {
public:
    inline static _TypePtr _TYPELIBATTR;
};
}
