/// <summary>
/// Name: System::Runtime::InteropServices::ComTypes::VARKIND
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices::ComTypes {
class VARKIND {
public:
    inline static _TypePtr _VARKIND;
};
}
