/// <summary>
/// Name: System::Threading::AbandonedMutexException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Threading {
class AbandonedMutexException {
public:
    inline static _TypePtr _AbandonedMutexException;
};
}
