/// <summary>
/// Name: System::Threading::ApartmentState
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Threading {
class ApartmentState {
public:
    inline static _TypePtr _ApartmentState;
};
}
