/// <summary>
/// Name: System::Threading::AsyncFlowControl
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Threading {
class AsyncFlowControl {
public:
    inline static _TypePtr _AsyncFlowControl;
};
}
