/// <summary>
/// Name: System::Threading::AutoResetEvent
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Threading {
class AutoResetEvent {
public:
    inline static _TypePtr _AutoResetEvent;
};
}
