/// <summary>
/// Name: System::Threading::ContextCallback
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Threading {
class ContextCallback {
public:
    inline static _TypePtr _ContextCallback;
};
}
