/// <summary>
/// Name: System::Threading::EventWaitHandle
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Threading {
class EventWaitHandle {
public:
    inline static _TypePtr _EventWaitHandle;
};
}
