/// <summary>
/// Name: System::Threading::EventResetMode
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Threading {
class EventResetMode {
public:
    inline static _TypePtr _EventResetMode;
};
}
