/// <summary>
/// Name: System::Threading::ExecutionContext
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Threading {
class ExecutionContext {
public:
    inline static _TypePtr _ExecutionContext;
};
}
