/// <summary>
/// Name: System::Threading::HostExecutionContext
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Threading {
class HostExecutionContext {
public:
    inline static _TypePtr _HostExecutionContext;
};
}
