/// <summary>
/// Name: System::Threading::HostExecutionContextManager
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Threading {
class HostExecutionContextManager {
public:
    inline static _TypePtr _HostExecutionContextManager;
};
}
