/// <summary>
/// Name: System::Threading::Interlocked
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Threading {
class Interlocked {
public:
    inline static _TypePtr _Interlocked;
};
}
