/// <summary>
/// Name: System::Threading::IOCompletionCallback
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Threading {
class IOCompletionCallback {
public:
    inline static _TypePtr _IOCompletionCallback;
};
}
