/// <summary>
/// Name: System::Threading::LockCookie
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Threading {
class LockCookie {
public:
    inline static _TypePtr _LockCookie;
};
}
