/// <summary>
/// Name: System::Threading::ManualResetEvent
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Threading {
class ManualResetEvent {
public:
    inline static _TypePtr _ManualResetEvent;
};
}
