/// <summary>
/// Name: System::Threading::Monitor
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Threading {
class Monitor {
public:
    inline static _TypePtr _Monitor;
};
}
