/// <summary>
/// Name: System::Threading::Mutex
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Threading {
class Mutex {
public:
    inline static _TypePtr _Mutex;
};
}
