/// <summary>
/// Name: System::Threading::NativeOverlapped
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Threading {
class NativeOverlapped {
public:
    inline static _TypePtr _NativeOverlapped;
};
}
