/// <summary>
/// Name: System::Threading::Overlapped
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Threading {
class Overlapped {
public:
    inline static _TypePtr _Overlapped;
};
}
