/// <summary>
/// Name: System::Threading::ParameterizedThreadStart
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Threading {
class ParameterizedThreadStart {
public:
    inline static _TypePtr _ParameterizedThreadStart;
};
}
