/// <summary>
/// Name: System::Threading::ReaderWriterLock
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Threading {
class ReaderWriterLock {
public:
    inline static _TypePtr _ReaderWriterLock;
};
}
