/// <summary>
/// Name: System::Threading::RegisteredWaitHandle
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Threading {
class RegisteredWaitHandle {
public:
    inline static _TypePtr _RegisteredWaitHandle;
};
}
