/// <summary>
/// Name: System::Threading::SendOrPostCallback
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Threading {
class SendOrPostCallback {
public:
    inline static _TypePtr _SendOrPostCallback;
};
}
