/// <summary>
/// Name: System::Threading::SynchronizationLockException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Threading {
class SynchronizationLockException {
public:
    inline static _TypePtr _SynchronizationLockException;
};
}
