/// <summary>
/// Name: System::Threading::SynchronizationContext
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Threading {
class SynchronizationContext {
public:
    inline static _TypePtr _SynchronizationContext;
};
}
