/// <summary>
/// Name: System::Threading::ThreadPool
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Threading {
class ThreadPool {
public:
    inline static _TypePtr _ThreadPool;
};
}
