/// <summary>
/// Name: System::Threading::ThreadAbortException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Threading {
class ThreadAbortException {
public:
    inline static _TypePtr _ThreadAbortException;
};
}
