/// <summary>
/// Name: System::Threading::ThreadState
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Threading {
class ThreadState {
public:
    inline static _TypePtr _ThreadState;
};
}
