/// <summary>
/// Name: System::Threading::ThreadInterruptedException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Threading {
class ThreadInterruptedException {
public:
    inline static _TypePtr _ThreadInterruptedException;
};
}
