/// <summary>
/// Name: System::Threading::ThreadStart
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Threading {
class ThreadStart {
public:
    inline static _TypePtr _ThreadStart;
};
}
