/// <summary>
/// Name: System::Threading::ThreadStartException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Threading {
class ThreadStartException {
public:
    inline static _TypePtr _ThreadStartException;
};
}
