/// <summary>
/// Name: System::Threading::ThreadStateException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Threading {
class ThreadStateException {
public:
    inline static _TypePtr _ThreadStateException;
};
}
