/// <summary>
/// Name: System::Threading::ThreadPriority
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Threading {
class ThreadPriority {
public:
    inline static _TypePtr _ThreadPriority;
};
}
