/// <summary>
/// Name: System::Threading::Thread
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Threading {
class Thread {
public:
    inline static _TypePtr _Thread;
};
}
