/// <summary>
/// Name: System::Threading::Timeout
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Threading {
class Timeout {
public:
    inline static _TypePtr _Timeout;
};
}
