/// <summary>
/// Name: System::Threading::Timer
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Threading {
class Timer {
public:
    inline static _TypePtr _Timer;
};
}
