/// <summary>
/// Name: System::Threading::TimerCallback
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Threading {
class TimerCallback {
public:
    inline static _TypePtr _TimerCallback;
};
}
