/// <summary>
/// Name: System::Threading::WaitHandle
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Threading {
class WaitHandle {
public:
    inline static _TypePtr _WaitHandle;
};
}
