/// <summary>
/// Name: System::Threading::WaitCallback
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Threading {
class WaitCallback {
public:
    inline static _TypePtr _WaitCallback;
};
}
