/// <summary>
/// Name: System::Threading::WaitOrTimerCallback
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Threading {
class WaitOrTimerCallback {
public:
    inline static _TypePtr _WaitOrTimerCallback;
};
}
