/// <summary>
/// Name: System::Threading::WaitHandleCannotBeOpenedException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Threading {
class WaitHandleCannotBeOpenedException {
public:
    inline static _TypePtr _WaitHandleCannotBeOpenedException;
};
}
