/// <summary>
/// Name: System::IO::IsolatedStorage::INormalizeForIsolatedStorage
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::IO::IsolatedStorage {
class INormalizeForIsolatedStorage {
public:
    inline static _TypePtr _INormalizeForIsolatedStorage;
};
}
