/// <summary>
/// Name: System::IO::IsolatedStorage::IsolatedStorageFileStream
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::IO::IsolatedStorage {
class IsolatedStorageFileStream {
public:
    inline static _TypePtr _IsolatedStorageFileStream;
};
}
