/// <summary>
/// Name: System::IO::IsolatedStorage::IsolatedStorageException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::IO::IsolatedStorage {
class IsolatedStorageException {
public:
    inline static _TypePtr _IsolatedStorageException;
};
}
