/// <summary>
/// Name: System::IO::IsolatedStorage::IsolatedStorageScope
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::IO::IsolatedStorage {
class IsolatedStorageScope {
public:
    inline static _TypePtr _IsolatedStorageScope;
};
}
