/// <summary>
/// Name: System::IO::IsolatedStorage::IsolatedStorage
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::IO::IsolatedStorage {
class IsolatedStorage {
public:
    inline static _TypePtr _IsolatedStorage;
};
}
