/// <summary>
/// Name: System::IO::IsolatedStorage::IsolatedStorageFile
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::IO::IsolatedStorage {
class IsolatedStorageFile {
public:
    inline static _TypePtr _IsolatedStorageFile;
};
}
