/// <summary>
/// Name: System::Runtime::Remoting::Proxies::ProxyAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Proxies {
class ProxyAttribute {
public:
    inline static _TypePtr _ProxyAttribute;
};
}
