/// <summary>
/// Name: System::Runtime::Remoting::Proxies::RealProxy
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Proxies {
class RealProxy {
public:
    inline static _TypePtr _RealProxy;
};
}
