/// <summary>
/// Name: System::Runtime::Remoting::ActivatedServiceTypeEntry
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting {
class ActivatedServiceTypeEntry {
public:
    inline static _TypePtr _ActivatedServiceTypeEntry;
};
}
