/// <summary>
/// Name: System::Runtime::Remoting::ActivatedClientTypeEntry
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting {
class ActivatedClientTypeEntry {
public:
    inline static _TypePtr _ActivatedClientTypeEntry;
};
}
