/// <summary>
/// Name: System::Runtime::Remoting::CustomErrorsModes
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting {
class CustomErrorsModes {
public:
    inline static _TypePtr _CustomErrorsModes;
};
}
