/// <summary>
/// Name: System::Runtime::Remoting::IChannelInfo
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting {
class IChannelInfo {
public:
    inline static _TypePtr _IChannelInfo;
};
}
