/// <summary>
/// Name: System::Runtime::Remoting::IEnvoyInfo
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting {
class IEnvoyInfo {
public:
    inline static _TypePtr _IEnvoyInfo;
};
}
