/// <summary>
/// Name: System::Runtime::Remoting::InternalRemotingServices
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting {
class InternalRemotingServices {
public:
    inline static _TypePtr _InternalRemotingServices;
};
}
