/// <summary>
/// Name: System::Runtime::Remoting::IObjectHandle
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting {
class IObjectHandle {
public:
    inline static _TypePtr _IObjectHandle;
};
}
