/// <summary>
/// Name: System::Runtime::Remoting::IRemotingTypeInfo
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting {
class IRemotingTypeInfo {
public:
    inline static _TypePtr _IRemotingTypeInfo;
};
}
