/// <summary>
/// Name: System::Runtime::Remoting::ObjectHandle
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting {
class ObjectHandle {
public:
    inline static _TypePtr _ObjectHandle;
};
}
