/// <summary>
/// Name: System::Runtime::Remoting::ObjRef
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting {
class ObjRef {
public:
    inline static _TypePtr _ObjRef;
};
}
