/// <summary>
/// Name: System::Runtime::Remoting::RemotingException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting {
class RemotingException {
public:
    inline static _TypePtr _RemotingException;
};
}
