/// <summary>
/// Name: System::Runtime::Remoting::RemotingTimeoutException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting {
class RemotingTimeoutException {
public:
    inline static _TypePtr _RemotingTimeoutException;
};
}
