/// <summary>
/// Name: System::Runtime::Remoting::RemotingConfiguration
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting {
class RemotingConfiguration {
public:
    inline static _TypePtr _RemotingConfiguration;
};
}
