/// <summary>
/// Name: System::Runtime::Remoting::RemotingServices
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting {
class RemotingServices {
public:
    inline static _TypePtr _RemotingServices;
};
}
