/// <summary>
/// Name: System::Runtime::Remoting::ServerException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting {
class ServerException {
public:
    inline static _TypePtr _ServerException;
};
}
