/// <summary>
/// Name: System::Runtime::Remoting::SoapServices
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting {
class SoapServices {
public:
    inline static _TypePtr _SoapServices;
};
}
