/// <summary>
/// Name: System::Runtime::Remoting::TypeEntry
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting {
class TypeEntry {
public:
    inline static _TypePtr _TypeEntry;
};
}
