/// <summary>
/// Name: System::Runtime::Remoting::WellKnownServiceTypeEntry
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting {
class WellKnownServiceTypeEntry {
public:
    inline static _TypePtr _WellKnownServiceTypeEntry;
};
}
