/// <summary>
/// Name: System::Runtime::Remoting::WellKnownClientTypeEntry
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting {
class WellKnownClientTypeEntry {
public:
    inline static _TypePtr _WellKnownClientTypeEntry;
};
}
