/// <summary>
/// Name: System::Runtime::Remoting::WellKnownObjectMode
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting {
class WellKnownObjectMode {
public:
    inline static _TypePtr _WellKnownObjectMode;
};
}
