/// <summary>
/// Name: System::Globalization::CalendarWeekRule
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Globalization {
class CalendarWeekRule {
public:
    inline static _TypePtr _CalendarWeekRule;
};
}
