/// <summary>
/// Name: System::Globalization::CalendarAlgorithmType
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Globalization {
class CalendarAlgorithmType {
public:
    inline static _TypePtr _CalendarAlgorithmType;
};
}
