/// <summary>
/// Name: System::Globalization::Calendar
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Globalization {
class Calendar {
public:
    inline static _TypePtr _Calendar;
};
}
