/// <summary>
/// Name: System::Globalization::CharUnicodeInfo
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Globalization {
class CharUnicodeInfo {
public:
    inline static _TypePtr _CharUnicodeInfo;
};
}
