/// <summary>
/// Name: System::Globalization::ChineseLunisolarCalendar
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Globalization {
class ChineseLunisolarCalendar {
public:
    inline static _TypePtr _ChineseLunisolarCalendar;
};
}
