/// <summary>
/// Name: System::Globalization::CompareOptions
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Globalization {
class CompareOptions {
public:
    inline static _TypePtr _CompareOptions;
};
}
