/// <summary>
/// Name: System::Globalization::CompareInfo
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Globalization {
class CompareInfo {
public:
    inline static _TypePtr _CompareInfo;
};
}
