/// <summary>
/// Name: System::Globalization::CultureTypes
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Globalization {
class CultureTypes {
public:
    inline static _TypePtr _CultureTypes;
};
}
