/// <summary>
/// Name: System::Globalization::CultureInfo
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Globalization {
class CultureInfo {
public:
    inline static _TypePtr _CultureInfo;
};
}
