/// <summary>
/// Name: System::Globalization::DateTimeFormatInfo
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Globalization {
class DateTimeFormatInfo {
public:
    inline static _TypePtr _DateTimeFormatInfo;
};
}
