/// <summary>
/// Name: System::Globalization::DateTimeStyles
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Globalization {
class DateTimeStyles {
public:
    inline static _TypePtr _DateTimeStyles;
};
}
