/// <summary>
/// Name: System::Globalization::DaylightTime
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Globalization {
class DaylightTime {
public:
    inline static _TypePtr _DaylightTime;
};
}
