/// <summary>
/// Name: System::Globalization::DigitShapes
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Globalization {
class DigitShapes {
public:
    inline static _TypePtr _DigitShapes;
};
}
