/// <summary>
/// Name: System::Globalization::EastAsianLunisolarCalendar
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Globalization {
class EastAsianLunisolarCalendar {
public:
    inline static _TypePtr _EastAsianLunisolarCalendar;
};
}
