/// <summary>
/// Name: System::Globalization::GregorianCalendar
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Globalization {
class GregorianCalendar {
public:
    inline static _TypePtr _GregorianCalendar;
};
}
