/// <summary>
/// Name: System::Globalization::GregorianCalendarTypes
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Globalization {
class GregorianCalendarTypes {
public:
    inline static _TypePtr _GregorianCalendarTypes;
};
}
