/// <summary>
/// Name: System::Globalization::HebrewCalendar
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Globalization {
class HebrewCalendar {
public:
    inline static _TypePtr _HebrewCalendar;
};
}
