/// <summary>
/// Name: System::Globalization::HijriCalendar
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Globalization {
class HijriCalendar {
public:
    inline static _TypePtr _HijriCalendar;
};
}
