/// <summary>
/// Name: System::Globalization::IdnMapping
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Globalization {
class IdnMapping {
public:
    inline static _TypePtr _IdnMapping;
};
}
