/// <summary>
/// Name: System::Globalization::JapaneseCalendar
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Globalization {
class JapaneseCalendar {
public:
    inline static _TypePtr _JapaneseCalendar;
};
}
