/// <summary>
/// Name: System::Globalization::JapaneseLunisolarCalendar
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Globalization {
class JapaneseLunisolarCalendar {
public:
    inline static _TypePtr _JapaneseLunisolarCalendar;
};
}
