/// <summary>
/// Name: System::Globalization::JulianCalendar
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Globalization {
class JulianCalendar {
public:
    inline static _TypePtr _JulianCalendar;
};
}
