/// <summary>
/// Name: System::Globalization::KoreanLunisolarCalendar
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Globalization {
class KoreanLunisolarCalendar {
public:
    inline static _TypePtr _KoreanLunisolarCalendar;
};
}
