/// <summary>
/// Name: System::Globalization::KoreanCalendar
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Globalization {
class KoreanCalendar {
public:
    inline static _TypePtr _KoreanCalendar;
};
}
