/// <summary>
/// Name: System::Globalization::NumberStyles
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Globalization {
class NumberStyles {
public:
    inline static _TypePtr _NumberStyles;
};
}
