/// <summary>
/// Name: System::Globalization::NumberFormatInfo
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Globalization {
class NumberFormatInfo {
public:
    inline static _TypePtr _NumberFormatInfo;
};
}
