/// <summary>
/// Name: System::Globalization::PersianCalendar
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Globalization {
class PersianCalendar {
public:
    inline static _TypePtr _PersianCalendar;
};
}
