/// <summary>
/// Name: System::Globalization::RegionInfo
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Globalization {
class RegionInfo {
public:
    inline static _TypePtr _RegionInfo;
};
}
