/// <summary>
/// Name: System::Globalization::SortKey
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Globalization {
class SortKey {
public:
    inline static _TypePtr _SortKey;
};
}
