/// <summary>
/// Name: System::Globalization::StringInfo
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Globalization {
class StringInfo {
public:
    inline static _TypePtr _StringInfo;
};
}
