/// <summary>
/// Name: System::Globalization::TaiwanLunisolarCalendar
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Globalization {
class TaiwanLunisolarCalendar {
public:
    inline static _TypePtr _TaiwanLunisolarCalendar;
};
}
