/// <summary>
/// Name: System::Globalization::TaiwanCalendar
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Globalization {
class TaiwanCalendar {
public:
    inline static _TypePtr _TaiwanCalendar;
};
}
