/// <summary>
/// Name: System::Globalization::TextInfo
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Globalization {
class TextInfo {
public:
    inline static _TypePtr _TextInfo;
};
}
