/// <summary>
/// Name: System::Globalization::TextElementEnumerator
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Globalization {
class TextElementEnumerator {
public:
    inline static _TypePtr _TextElementEnumerator;
};
}
