/// <summary>
/// Name: System::Globalization::ThaiBuddhistCalendar
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Globalization {
class ThaiBuddhistCalendar {
public:
    inline static _TypePtr _ThaiBuddhistCalendar;
};
}
