/// <summary>
/// Name: System::Globalization::UmAlQuraCalendar
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Globalization {
class UmAlQuraCalendar {
public:
    inline static _TypePtr _UmAlQuraCalendar;
};
}
