/// <summary>
/// Name: System::Globalization::UnicodeCategory
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Globalization {
class UnicodeCategory {
public:
    inline static _TypePtr _UnicodeCategory;
};
}
