/// <summary>
/// Name: System::Deployment::Internal::InternalApplicationIdentityHelper
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Deployment::Internal {
class InternalApplicationIdentityHelper {
public:
    inline static _TypePtr _InternalApplicationIdentityHelper;
};
}
