/// <summary>
/// Name: System::Deployment::Internal::InternalActivationContextHelper
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Deployment::Internal {
class InternalActivationContextHelper {
public:
    inline static _TypePtr _InternalActivationContextHelper;
};
}
