/// <summary>
/// Name: Microsoft::Win32::RegistryHive
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace Microsoft::Win32 {
class RegistryHive {
public:
    inline static _TypePtr _RegistryHive;
};
}
