/// <summary>
/// Name: Microsoft::Win32::Registry
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace Microsoft::Win32 {
class Registry {
public:
    inline static _TypePtr _Registry;
};
}
