/// <summary>
/// Name: Microsoft::Win32::RegistryValueOptions
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace Microsoft::Win32 {
class RegistryValueOptions {
public:
    inline static _TypePtr _RegistryValueOptions;
};
}
