/// <summary>
/// Name: Microsoft::Win32::RegistryValueKind
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace Microsoft::Win32 {
class RegistryValueKind {
public:
    inline static _TypePtr _RegistryValueKind;
};
}
