/// <summary>
/// Name: Microsoft::Win32::RegistryKeyPermissionCheck
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace Microsoft::Win32 {
class RegistryKeyPermissionCheck {
public:
    inline static _TypePtr _RegistryKeyPermissionCheck;
};
}
