/// <summary>
/// Name: Microsoft::Win32::RegistryKey
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace Microsoft::Win32 {
class RegistryKey {
public:
    inline static _TypePtr _RegistryKey;
};
}
