/// <summary>
/// Name: System::Configuration::Assemblies::AssemblyVersionCompatibility
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Configuration::Assemblies {
class AssemblyVersionCompatibility {
public:
    inline static _TypePtr _AssemblyVersionCompatibility;
};
}
