/// <summary>
/// Name: System::Configuration::Assemblies::AssemblyHashAlgorithm
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Configuration::Assemblies {
class AssemblyHashAlgorithm {
public:
    inline static _TypePtr _AssemblyHashAlgorithm;
};
}
