/// <summary>
/// Name: System::Configuration::Assemblies::AssemblyHash
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Configuration::Assemblies {
class AssemblyHash {
public:
    inline static _TypePtr _AssemblyHash;
};
}
