/// <summary>
/// Name: System::Runtime::Remoting::Metadata::SoapAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Metadata {
class SoapAttribute {
public:
    inline static _TypePtr _SoapAttribute;
};
}
