/// <summary>
/// Name: System::Runtime::Remoting::Metadata::SoapTypeAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Metadata {
class SoapTypeAttribute {
public:
    inline static _TypePtr _SoapTypeAttribute;
};
}
