/// <summary>
/// Name: System::Runtime::Remoting::Metadata::SoapParameterAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Metadata {
class SoapParameterAttribute {
public:
    inline static _TypePtr _SoapParameterAttribute;
};
}
