/// <summary>
/// Name: System::Runtime::Remoting::Metadata::SoapMethodAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Metadata {
class SoapMethodAttribute {
public:
    inline static _TypePtr _SoapMethodAttribute;
};
}
