/// <summary>
/// Name: System::Runtime::Remoting::Metadata::SoapFieldAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Metadata {
class SoapFieldAttribute {
public:
    inline static _TypePtr _SoapFieldAttribute;
};
}
