/// <summary>
/// Name: System::Runtime::Remoting::Metadata::SoapOption
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Metadata {
class SoapOption {
public:
    inline static _TypePtr _SoapOption;
};
}
