/// <summary>
/// Name: System::Runtime::Remoting::Metadata::XmlFieldOrderOption
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Metadata {
class XmlFieldOrderOption {
public:
    inline static _TypePtr _XmlFieldOrderOption;
};
}
