/// <summary>
/// Name: System::Reflection::Emit::AssemblyBuilderAccess
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection::Emit {
class AssemblyBuilderAccess {
public:
    inline static _TypePtr _AssemblyBuilderAccess;
};
}
