/// <summary>
/// Name: System::Reflection::Emit::AssemblyBuilder
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection::Emit {
class AssemblyBuilder {
public:
    inline static _TypePtr _AssemblyBuilder;
};
}
