/// <summary>
/// Name: System::Reflection::Emit::ConstructorBuilder
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection::Emit {
class ConstructorBuilder {
public:
    inline static _TypePtr _ConstructorBuilder;
};
}
