/// <summary>
/// Name: System::Reflection::Emit::CustomAttributeBuilder
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection::Emit {
class CustomAttributeBuilder {
public:
    inline static _TypePtr _CustomAttributeBuilder;
};
}
