/// <summary>
/// Name: System::Reflection::Emit::DynamicMethod
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection::Emit {
class DynamicMethod {
public:
    inline static _TypePtr _DynamicMethod;
};
}
