/// <summary>
/// Name: System::Reflection::Emit::DynamicILInfo
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection::Emit {
class DynamicILInfo {
public:
    inline static _TypePtr _DynamicILInfo;
};
}
