/// <summary>
/// Name: System::Reflection::Emit::EnumBuilder
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection::Emit {
class EnumBuilder {
public:
    inline static _TypePtr _EnumBuilder;
};
}
