/// <summary>
/// Name: System::Reflection::Emit::EventToken
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection::Emit {
class EventToken {
public:
    inline static _TypePtr _EventToken;
};
}
