/// <summary>
/// Name: System::Reflection::Emit::EventBuilder
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection::Emit {
class EventBuilder {
public:
    inline static _TypePtr _EventBuilder;
};
}
