/// <summary>
/// Name: System::Reflection::Emit::FieldBuilder
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection::Emit {
class FieldBuilder {
public:
    inline static _TypePtr _FieldBuilder;
};
}
