/// <summary>
/// Name: System::Reflection::Emit::FieldToken
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection::Emit {
class FieldToken {
public:
    inline static _TypePtr _FieldToken;
};
}
