/// <summary>
/// Name: System::Reflection::Emit::FlowControl
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection::Emit {
class FlowControl {
public:
    inline static _TypePtr _FlowControl;
};
}
