/// <summary>
/// Name: System::Reflection::Emit::GenericTypeParameterBuilder
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection::Emit {
class GenericTypeParameterBuilder {
public:
    inline static _TypePtr _GenericTypeParameterBuilder;
};
}
