/// <summary>
/// Name: System::Reflection::Emit::Label
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection::Emit {
class Label {
public:
    inline static _TypePtr _Label;
};
}
