/// <summary>
/// Name: System::Reflection::Emit::LocalBuilder
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection::Emit {
class LocalBuilder {
public:
    inline static _TypePtr _LocalBuilder;
};
}
