/// <summary>
/// Name: System::Reflection::Emit::MethodRental
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection::Emit {
class MethodRental {
public:
    inline static _TypePtr _MethodRental;
};
}
