/// <summary>
/// Name: System::Reflection::Emit::MethodBuilder
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection::Emit {
class MethodBuilder {
public:
    inline static _TypePtr _MethodBuilder;
};
}
