/// <summary>
/// Name: System::Reflection::Emit::ModuleBuilder
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection::Emit {
class ModuleBuilder {
public:
    inline static _TypePtr _ModuleBuilder;
};
}
