/// <summary>
/// Name: System::Reflection::Emit::OpCodes
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection::Emit {
class OpCodes {
public:
    inline static _TypePtr _OpCodes;
};
}
