/// <summary>
/// Name: System::Reflection::Emit::OpCodeType
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection::Emit {
class OpCodeType {
public:
    inline static _TypePtr _OpCodeType;
};
}
