/// <summary>
/// Name: System::Reflection::Emit::OpCode
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection::Emit {
class OpCode {
public:
    inline static _TypePtr _OpCode;
};
}
