/// <summary>
/// Name: System::Reflection::Emit::OperandType
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection::Emit {
class OperandType {
public:
    inline static _TypePtr _OperandType;
};
}
