/// <summary>
/// Name: System::Reflection::Emit::PackingSize
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection::Emit {
class PackingSize {
public:
    inline static _TypePtr _PackingSize;
};
}
