/// <summary>
/// Name: System::Reflection::Emit::ParameterBuilder
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection::Emit {
class ParameterBuilder {
public:
    inline static _TypePtr _ParameterBuilder;
};
}
