/// <summary>
/// Name: System::Reflection::Emit::ParameterToken
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection::Emit {
class ParameterToken {
public:
    inline static _TypePtr _ParameterToken;
};
}
