/// <summary>
/// Name: System::Reflection::Emit::PEFileKinds
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection::Emit {
class PEFileKinds {
public:
    inline static _TypePtr _PEFileKinds;
};
}
