/// <summary>
/// Name: System::Reflection::Emit::PropertyToken
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection::Emit {
class PropertyToken {
public:
    inline static _TypePtr _PropertyToken;
};
}
