/// <summary>
/// Name: System::Reflection::Emit::PropertyBuilder
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection::Emit {
class PropertyBuilder {
public:
    inline static _TypePtr _PropertyBuilder;
};
}
