/// <summary>
/// Name: System::Reflection::Emit::SignatureHelper
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection::Emit {
class SignatureHelper {
public:
    inline static _TypePtr _SignatureHelper;
};
}
