/// <summary>
/// Name: System::Reflection::Emit::SignatureToken
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection::Emit {
class SignatureToken {
public:
    inline static _TypePtr _SignatureToken;
};
}
