/// <summary>
/// Name: System::Reflection::Emit::StringToken
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection::Emit {
class StringToken {
public:
    inline static _TypePtr _StringToken;
};
}
