/// <summary>
/// Name: System::Reflection::Emit::TypeBuilder
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection::Emit {
class TypeBuilder {
public:
    inline static _TypePtr _TypeBuilder;
};
}
