/// <summary>
/// Name: System::Reflection::Emit::TypeToken
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection::Emit {
class TypeToken {
public:
    inline static _TypePtr _TypeToken;
};
}
