/// <summary>
/// Name: System::Reflection::Emit::UnmanagedMarshal
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection::Emit {
class UnmanagedMarshal {
public:
    inline static _TypePtr _UnmanagedMarshal;
};
}
