/// <summary>
/// Name: System::Runtime::Remoting::Metadata::W3cXsd2001::SoapAnyUri
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Metadata::W3cXsd2001 {
class SoapAnyUri {
public:
    inline static _TypePtr _SoapAnyUri;
};
}
