/// <summary>
/// Name: System::Runtime::Remoting::Metadata::W3cXsd2001::SoapYear
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Metadata::W3cXsd2001 {
class SoapYear {
public:
    inline static _TypePtr _SoapYear;
};
}
