/// <summary>
/// Name: System::Runtime::Remoting::Metadata::W3cXsd2001::SoapNonNegativeInteger
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Metadata::W3cXsd2001 {
class SoapNonNegativeInteger {
public:
    inline static _TypePtr _SoapNonNegativeInteger;
};
}
