/// <summary>
/// Name: System::Runtime::Remoting::Metadata::W3cXsd2001::SoapDuration
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Metadata::W3cXsd2001 {
class SoapDuration {
public:
    inline static _TypePtr _SoapDuration;
};
}
