/// <summary>
/// Name: System::Runtime::Remoting::Metadata::W3cXsd2001::SoapDate
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Metadata::W3cXsd2001 {
class SoapDate {
public:
    inline static _TypePtr _SoapDate;
};
}
