/// <summary>
/// Name: System::Runtime::Remoting::Metadata::W3cXsd2001::SoapNmtokens
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Metadata::W3cXsd2001 {
class SoapNmtokens {
public:
    inline static _TypePtr _SoapNmtokens;
};
}
