/// <summary>
/// Name: System::Runtime::Remoting::Metadata::W3cXsd2001::SoapNegativeInteger
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Metadata::W3cXsd2001 {
class SoapNegativeInteger {
public:
    inline static _TypePtr _SoapNegativeInteger;
};
}
