/// <summary>
/// Name: System::Runtime::Remoting::Metadata::W3cXsd2001::SoapMonth
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Metadata::W3cXsd2001 {
class SoapMonth {
public:
    inline static _TypePtr _SoapMonth;
};
}
