/// <summary>
/// Name: Microsoft::Win32::SafeHandles::CriticalHandleZeroOrMinusOneIsInvalid
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace Microsoft::Win32::SafeHandles {
class CriticalHandleZeroOrMinusOneIsInvalid {
public:
    inline static _TypePtr _CriticalHandleZeroOrMinusOneIsInvalid;
};
}
