/// <summary>
/// Name: Microsoft::Win32::SafeHandles::CriticalHandleMinusOneIsInvalid
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace Microsoft::Win32::SafeHandles {
class CriticalHandleMinusOneIsInvalid {
public:
    inline static _TypePtr _CriticalHandleMinusOneIsInvalid;
};
}
