/// <summary>
/// Name: Microsoft::Win32::SafeHandles::SafeFileHandle
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace Microsoft::Win32::SafeHandles {
class SafeFileHandle {
public:
    inline static _TypePtr _SafeFileHandle;
};
}
