/// <summary>
/// Name: Microsoft::Win32::SafeHandles::SafeWaitHandle
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace Microsoft::Win32::SafeHandles {
class SafeWaitHandle {
public:
    inline static _TypePtr _SafeWaitHandle;
};
}
