/// <summary>
/// Name: Microsoft::Win32::SafeHandles::SafeHandleMinusOneIsInvalid
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace Microsoft::Win32::SafeHandles {
class SafeHandleMinusOneIsInvalid {
public:
    inline static _TypePtr _SafeHandleMinusOneIsInvalid;
};
}
