/// <summary>
/// Name: Microsoft::Win32::SafeHandles::SafeHandleZeroOrMinusOneIsInvalid
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace Microsoft::Win32::SafeHandles {
class SafeHandleZeroOrMinusOneIsInvalid {
public:
    inline static _TypePtr _SafeHandleZeroOrMinusOneIsInvalid;
};
}
