/// <summary>
/// Name: System::Runtime::GCLatencyMode
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime {
class GCLatencyMode {
public:
    inline static _TypePtr _GCLatencyMode;
};
}
