/// <summary>
/// Name: System::Runtime::GCSettings
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime {
class GCSettings {
public:
    inline static _TypePtr _GCSettings;
};
}
