/// <summary>
/// Name: System::Runtime::MemoryFailPoint
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime {
class MemoryFailPoint {
public:
    inline static _TypePtr _MemoryFailPoint;
};
}
