/// <summary>
/// Name: System::Runtime::CompilerServices::AccessedThroughPropertyAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::CompilerServices {
class AccessedThroughPropertyAttribute {
public:
    inline static _TypePtr _AccessedThroughPropertyAttribute;
};
}
