/// <summary>
/// Name: System::Runtime::CompilerServices::CallConvFastcall
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::CompilerServices {
class CallConvFastcall {
public:
    inline static _TypePtr _CallConvFastcall;
};
}
