/// <summary>
/// Name: System::Runtime::CompilerServices::CallConvCdecl
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::CompilerServices {
class CallConvCdecl {
public:
    inline static _TypePtr _CallConvCdecl;
};
}
