/// <summary>
/// Name: System::Runtime::CompilerServices::CallConvStdcall
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::CompilerServices {
class CallConvStdcall {
public:
    inline static _TypePtr _CallConvStdcall;
};
}
