/// <summary>
/// Name: System::Runtime::CompilerServices::CompilerGeneratedAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::CompilerServices {
class CompilerGeneratedAttribute {
public:
    inline static _TypePtr _CompilerGeneratedAttribute;
};
}
