/// <summary>
/// Name: System::Runtime::CompilerServices::CompilationRelaxationsAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::CompilerServices {
class CompilationRelaxationsAttribute {
public:
    inline static _TypePtr _CompilationRelaxationsAttribute;
};
}
