/// <summary>
/// Name: System::Runtime::CompilerServices::CompilerGlobalScopeAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::CompilerServices {
class CompilerGlobalScopeAttribute {
public:
    inline static _TypePtr _CompilerGlobalScopeAttribute;
};
}
