/// <summary>
/// Name: System::Runtime::CompilerServices::CompilerMarshalOverride
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::CompilerServices {
class CompilerMarshalOverride {
public:
    inline static _TypePtr _CompilerMarshalOverride;
};
}
