/// <summary>
/// Name: System::Runtime::CompilerServices::CompilationRelaxations
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::CompilerServices {
class CompilationRelaxations {
public:
    inline static _TypePtr _CompilationRelaxations;
};
}
