/// <summary>
/// Name: System::Runtime::CompilerServices::CustomConstantAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::CompilerServices {
class CustomConstantAttribute {
public:
    inline static _TypePtr _CustomConstantAttribute;
};
}
