/// <summary>
/// Name: System::Runtime::CompilerServices::DateTimeConstantAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::CompilerServices {
class DateTimeConstantAttribute {
public:
    inline static _TypePtr _DateTimeConstantAttribute;
};
}
