/// <summary>
/// Name: System::Runtime::CompilerServices::DecimalConstantAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::CompilerServices {
class DecimalConstantAttribute {
public:
    inline static _TypePtr _DecimalConstantAttribute;
};
}
