/// <summary>
/// Name: System::Runtime::CompilerServices::DefaultDependencyAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::CompilerServices {
class DefaultDependencyAttribute {
public:
    inline static _TypePtr _DefaultDependencyAttribute;
};
}
