/// <summary>
/// Name: System::Runtime::CompilerServices::DependencyAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::CompilerServices {
class DependencyAttribute {
public:
    inline static _TypePtr _DependencyAttribute;
};
}
