/// <summary>
/// Name: System::Runtime::CompilerServices::DiscardableAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::CompilerServices {
class DiscardableAttribute {
public:
    inline static _TypePtr _DiscardableAttribute;
};
}
