/// <summary>
/// Name: System::Runtime::CompilerServices::FixedAddressValueTypeAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::CompilerServices {
class FixedAddressValueTypeAttribute {
public:
    inline static _TypePtr _FixedAddressValueTypeAttribute;
};
}
