/// <summary>
/// Name: System::Runtime::CompilerServices::FixedBufferAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::CompilerServices {
class FixedBufferAttribute {
public:
    inline static _TypePtr _FixedBufferAttribute;
};
}
