/// <summary>
/// Name: System::Runtime::CompilerServices::HasCopySemanticsAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::CompilerServices {
class HasCopySemanticsAttribute {
public:
    inline static _TypePtr _HasCopySemanticsAttribute;
};
}
