/// <summary>
/// Name: System::Runtime::CompilerServices::IDispatchConstantAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::CompilerServices {
class IDispatchConstantAttribute {
public:
    inline static _TypePtr _IDispatchConstantAttribute;
};
}
