/// <summary>
/// Name: System::Runtime::CompilerServices::IndexerNameAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::CompilerServices {
class IndexerNameAttribute {
public:
    inline static _TypePtr _IndexerNameAttribute;
};
}
