/// <summary>
/// Name: System::Runtime::CompilerServices::InternalsVisibleToAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::CompilerServices {
class InternalsVisibleToAttribute {
public:
    inline static _TypePtr _InternalsVisibleToAttribute;
};
}
