/// <summary>
/// Name: System::Runtime::CompilerServices::IsBoxed
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::CompilerServices {
class IsBoxed {
public:
    inline static _TypePtr _IsBoxed;
};
}
