/// <summary>
/// Name: System::Runtime::CompilerServices::IsByValue
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::CompilerServices {
class IsByValue {
public:
    inline static _TypePtr _IsByValue;
};
}
