/// <summary>
/// Name: System::Runtime::CompilerServices::IsConst
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::CompilerServices {
class IsConst {
public:
    inline static _TypePtr _IsConst;
};
}
