/// <summary>
/// Name: System::Runtime::CompilerServices::IsCopyConstructed
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::CompilerServices {
class IsCopyConstructed {
public:
    inline static _TypePtr _IsCopyConstructed;
};
}
