/// <summary>
/// Name: System::Runtime::CompilerServices::IsExplicitlyDereferenced
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::CompilerServices {
class IsExplicitlyDereferenced {
public:
    inline static _TypePtr _IsExplicitlyDereferenced;
};
}
