/// <summary>
/// Name: System::Runtime::CompilerServices::IsImplicitlyDereferenced
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::CompilerServices {
class IsImplicitlyDereferenced {
public:
    inline static _TypePtr _IsImplicitlyDereferenced;
};
}
