/// <summary>
/// Name: System::Runtime::CompilerServices::IsJitIntrinsic
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::CompilerServices {
class IsJitIntrinsic {
public:
    inline static _TypePtr _IsJitIntrinsic;
};
}
