/// <summary>
/// Name: System::Runtime::CompilerServices::IsLong
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::CompilerServices {
class IsLong {
public:
    inline static _TypePtr _IsLong;
};
}
