/// <summary>
/// Name: System::Runtime::CompilerServices::IsPinned
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::CompilerServices {
class IsPinned {
public:
    inline static _TypePtr _IsPinned;
};
}
