/// <summary>
/// Name: System::Runtime::CompilerServices::IsSignUnspecifiedByte
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::CompilerServices {
class IsSignUnspecifiedByte {
public:
    inline static _TypePtr _IsSignUnspecifiedByte;
};
}
