/// <summary>
/// Name: System::Runtime::CompilerServices::IsUdtReturn
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::CompilerServices {
class IsUdtReturn {
public:
    inline static _TypePtr _IsUdtReturn;
};
}
