/// <summary>
/// Name: System::Runtime::CompilerServices::IsVolatile
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::CompilerServices {
class IsVolatile {
public:
    inline static _TypePtr _IsVolatile;
};
}
