/// <summary>
/// Name: System::Runtime::CompilerServices::IUnknownConstantAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::CompilerServices {
class IUnknownConstantAttribute {
public:
    inline static _TypePtr _IUnknownConstantAttribute;
};
}
