/// <summary>
/// Name: System::Runtime::CompilerServices::LoadHint
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::CompilerServices {
class LoadHint {
public:
    inline static _TypePtr _LoadHint;
};
}
