/// <summary>
/// Name: System::Runtime::CompilerServices::MethodImplAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::CompilerServices {
class MethodImplAttribute {
public:
    inline static _TypePtr _MethodImplAttribute;
};
}
