/// <summary>
/// Name: System::Runtime::CompilerServices::MethodImplOptions
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::CompilerServices {
class MethodImplOptions {
public:
    inline static _TypePtr _MethodImplOptions;
};
}
