/// <summary>
/// Name: System::Runtime::CompilerServices::MethodCodeType
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::CompilerServices {
class MethodCodeType {
public:
    inline static _TypePtr _MethodCodeType;
};
}
