/// <summary>
/// Name: System::Runtime::CompilerServices::NativeCppClassAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::CompilerServices {
class NativeCppClassAttribute {
public:
    inline static _TypePtr _NativeCppClassAttribute;
};
}
