/// <summary>
/// Name: System::Runtime::CompilerServices::RequiredAttributeAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::CompilerServices {
class RequiredAttributeAttribute {
public:
    inline static _TypePtr _RequiredAttributeAttribute;
};
}
