/// <summary>
/// Name: System::Runtime::CompilerServices::RuntimeCompatibilityAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::CompilerServices {
class RuntimeCompatibilityAttribute {
public:
    inline static _TypePtr _RuntimeCompatibilityAttribute;
};
}
