/// <summary>
/// Name: System::Runtime::CompilerServices::RuntimeHelpers
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::CompilerServices {
class RuntimeHelpers {
public:
    inline static _TypePtr _RuntimeHelpers;
};
}
