/// <summary>
/// Name: System::Runtime::CompilerServices::RuntimeWrappedException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::CompilerServices {
class RuntimeWrappedException {
public:
    inline static _TypePtr _RuntimeWrappedException;
};
}
