/// <summary>
/// Name: System::Runtime::CompilerServices::ScopelessEnumAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::CompilerServices {
class ScopelessEnumAttribute {
public:
    inline static _TypePtr _ScopelessEnumAttribute;
};
}
