/// <summary>
/// Name: System::Runtime::CompilerServices::SpecialNameAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::CompilerServices {
class SpecialNameAttribute {
public:
    inline static _TypePtr _SpecialNameAttribute;
};
}
