/// <summary>
/// Name: System::Runtime::CompilerServices::StringFreezingAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::CompilerServices {
class StringFreezingAttribute {
public:
    inline static _TypePtr _StringFreezingAttribute;
};
}
