/// <summary>
/// Name: System::Runtime::CompilerServices::SuppressIldasmAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::CompilerServices {
class SuppressIldasmAttribute {
public:
    inline static _TypePtr _SuppressIldasmAttribute;
};
}
