/// <summary>
/// Name: System::Runtime::CompilerServices::TypeForwardedToAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::CompilerServices {
class TypeForwardedToAttribute {
public:
    inline static _TypePtr _TypeForwardedToAttribute;
};
}
