/// <summary>
/// Name: System::Runtime::CompilerServices::UnsafeValueTypeAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::CompilerServices {
class UnsafeValueTypeAttribute {
public:
    inline static _TypePtr _UnsafeValueTypeAttribute;
};
}
