/// <summary>
/// Name: System::Security::Policy::AllMembershipCondition
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Policy {
class AllMembershipCondition {
public:
    inline static _TypePtr _AllMembershipCondition;
};
}
