/// <summary>
/// Name: System::Security::Policy::ApplicationSecurityInfo
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Policy {
class ApplicationSecurityInfo {
public:
    inline static _TypePtr _ApplicationSecurityInfo;
};
}
