/// <summary>
/// Name: System::Security::Policy::ApplicationTrustCollection
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Policy {
class ApplicationTrustCollection {
public:
    inline static _TypePtr _ApplicationTrustCollection;
};
}
