/// <summary>
/// Name: System::Security::Policy::ApplicationVersionMatch
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Policy {
class ApplicationVersionMatch {
public:
    inline static _TypePtr _ApplicationVersionMatch;
};
}
