/// <summary>
/// Name: System::Security::Policy::ApplicationTrustEnumerator
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Policy {
class ApplicationTrustEnumerator {
public:
    inline static _TypePtr _ApplicationTrustEnumerator;
};
}
