/// <summary>
/// Name: System::Security::Policy::ApplicationDirectory
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Policy {
class ApplicationDirectory {
public:
    inline static _TypePtr _ApplicationDirectory;
};
}
