/// <summary>
/// Name: System::Security::Policy::ApplicationDirectoryMembershipCondition
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Policy {
class ApplicationDirectoryMembershipCondition {
public:
    inline static _TypePtr _ApplicationDirectoryMembershipCondition;
};
}
