/// <summary>
/// Name: System::Security::Policy::CodeGroup
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Policy {
class CodeGroup {
public:
    inline static _TypePtr _CodeGroup;
};
}
