/// <summary>
/// Name: System::Security::Policy::CodeConnectAccess
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Policy {
class CodeConnectAccess {
public:
    inline static _TypePtr _CodeConnectAccess;
};
}
