/// <summary>
/// Name: System::Security::Policy::Evidence
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Policy {
class Evidence {
public:
    inline static _TypePtr _Evidence;
};
}
