/// <summary>
/// Name: System::Security::Policy::FileCodeGroup
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Policy {
class FileCodeGroup {
public:
    inline static _TypePtr _FileCodeGroup;
};
}
