/// <summary>
/// Name: System::Security::Policy::FirstMatchCodeGroup
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Policy {
class FirstMatchCodeGroup {
public:
    inline static _TypePtr _FirstMatchCodeGroup;
};
}
