/// <summary>
/// Name: System::Security::Policy::GacInstalled
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Policy {
class GacInstalled {
public:
    inline static _TypePtr _GacInstalled;
};
}
