/// <summary>
/// Name: System::Security::Policy::GacMembershipCondition
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Policy {
class GacMembershipCondition {
public:
    inline static _TypePtr _GacMembershipCondition;
};
}
