/// <summary>
/// Name: System::Security::Policy::HashMembershipCondition
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Policy {
class HashMembershipCondition {
public:
    inline static _TypePtr _HashMembershipCondition;
};
}
