/// <summary>
/// Name: System::Security::Policy::Hash
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Policy {
class Hash {
public:
    inline static _TypePtr _Hash;
};
}
