/// <summary>
/// Name: System::Security::Policy::IApplicationTrustManager
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Policy {
class IApplicationTrustManager {
public:
    inline static _TypePtr _IApplicationTrustManager;
};
}
