/// <summary>
/// Name: System::Security::Policy::IIdentityPermissionFactory
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Policy {
class IIdentityPermissionFactory {
public:
    inline static _TypePtr _IIdentityPermissionFactory;
};
}
