/// <summary>
/// Name: System::Security::Policy::IMembershipCondition
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Policy {
class IMembershipCondition {
public:
    inline static _TypePtr _IMembershipCondition;
};
}
