/// <summary>
/// Name: System::Security::Policy::NetCodeGroup
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Policy {
class NetCodeGroup {
public:
    inline static _TypePtr _NetCodeGroup;
};
}
