/// <summary>
/// Name: System::Security::Policy::PermissionRequestEvidence
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Policy {
class PermissionRequestEvidence {
public:
    inline static _TypePtr _PermissionRequestEvidence;
};
}
