/// <summary>
/// Name: System::Security::Policy::PolicyStatement
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Policy {
class PolicyStatement {
public:
    inline static _TypePtr _PolicyStatement;
};
}
