/// <summary>
/// Name: System::Security::Policy::PolicyException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Policy {
class PolicyException {
public:
    inline static _TypePtr _PolicyException;
};
}
