/// <summary>
/// Name: System::Security::Policy::PolicyLevel
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Policy {
class PolicyLevel {
public:
    inline static _TypePtr _PolicyLevel;
};
}
