/// <summary>
/// Name: System::Security::Policy::PolicyStatementAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Policy {
class PolicyStatementAttribute {
public:
    inline static _TypePtr _PolicyStatementAttribute;
};
}
