/// <summary>
/// Name: System::Security::Policy::PublisherMembershipCondition
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Policy {
class PublisherMembershipCondition {
public:
    inline static _TypePtr _PublisherMembershipCondition;
};
}
