/// <summary>
/// Name: System::Security::Policy::Publisher
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Policy {
class Publisher {
public:
    inline static _TypePtr _Publisher;
};
}
