/// <summary>
/// Name: System::Security::Policy::SiteMembershipCondition
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Policy {
class SiteMembershipCondition {
public:
    inline static _TypePtr _SiteMembershipCondition;
};
}
