/// <summary>
/// Name: System::Security::Policy::Site
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Policy {
class Site {
public:
    inline static _TypePtr _Site;
};
}
