/// <summary>
/// Name: System::Security::Policy::StrongName
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Policy {
class StrongName {
public:
    inline static _TypePtr _StrongName;
};
}
