/// <summary>
/// Name: System::Security::Policy::StrongNameMembershipCondition
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Policy {
class StrongNameMembershipCondition {
public:
    inline static _TypePtr _StrongNameMembershipCondition;
};
}
