/// <summary>
/// Name: System::Security::Policy::TrustManagerContext
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Policy {
class TrustManagerContext {
public:
    inline static _TypePtr _TrustManagerContext;
};
}
