/// <summary>
/// Name: System::Security::Policy::TrustManagerUIContext
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Policy {
class TrustManagerUIContext {
public:
    inline static _TypePtr _TrustManagerUIContext;
};
}
