/// <summary>
/// Name: System::Security::Policy::UnionCodeGroup
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Policy {
class UnionCodeGroup {
public:
    inline static _TypePtr _UnionCodeGroup;
};
}
