/// <summary>
/// Name: System::Security::Policy::Url
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Policy {
class Url {
public:
    inline static _TypePtr _Url;
};
}
