/// <summary>
/// Name: System::Security::Policy::UrlMembershipCondition
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Policy {
class UrlMembershipCondition {
public:
    inline static _TypePtr _UrlMembershipCondition;
};
}
