/// <summary>
/// Name: System::Security::Policy::ZoneMembershipCondition
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Policy {
class ZoneMembershipCondition {
public:
    inline static _TypePtr _ZoneMembershipCondition;
};
}
