/// <summary>
/// Name: System::Security::Policy::Zone
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Policy {
class Zone {
public:
    inline static _TypePtr _Zone;
};
}
