/// <summary>
/// Name: System::Runtime::Remoting::Lifetime::ClientSponsor
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Lifetime {
class ClientSponsor {
public:
    inline static _TypePtr _ClientSponsor;
};
}
