/// <summary>
/// Name: System::Runtime::Remoting::Lifetime::ILease
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Lifetime {
class ILease {
public:
    inline static _TypePtr _ILease;
};
}
