/// <summary>
/// Name: System::Runtime::Remoting::Lifetime::ISponsor
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Lifetime {
class ISponsor {
public:
    inline static _TypePtr _ISponsor;
};
}
