/// <summary>
/// Name: System::Runtime::Remoting::Lifetime::LeaseState
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Lifetime {
class LeaseState {
public:
    inline static _TypePtr _LeaseState;
};
}
