/// <summary>
/// Name: System::Runtime::Remoting::Lifetime::LifetimeServices
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Lifetime {
class LifetimeServices {
public:
    inline static _TypePtr _LifetimeServices;
};
}
