/// <summary>
/// Name: System::Security::AllowPartiallyTrustedCallersAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security {
class AllowPartiallyTrustedCallersAttribute {
public:
    inline static _TypePtr _AllowPartiallyTrustedCallersAttribute;
};
}
