/// <summary>
/// Name: System::Security::CodeAccessPermission
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security {
class CodeAccessPermission {
public:
    inline static _TypePtr _CodeAccessPermission;
};
}
