/// <summary>
/// Name: System::Security::HostSecurityManager
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security {
class HostSecurityManager {
public:
    inline static _TypePtr _HostSecurityManager;
};
}
