/// <summary>
/// Name: System::Security::HostProtectionException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security {
class HostProtectionException {
public:
    inline static _TypePtr _HostProtectionException;
};
}
