/// <summary>
/// Name: System::Security::HostSecurityManagerOptions
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security {
class HostSecurityManagerOptions {
public:
    inline static _TypePtr _HostSecurityManagerOptions;
};
}
