/// <summary>
/// Name: System::Security::IEvidenceFactory
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security {
class IEvidenceFactory {
public:
    inline static _TypePtr _IEvidenceFactory;
};
}
