/// <summary>
/// Name: System::Security::IPermission
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security {
class IPermission {
public:
    inline static _TypePtr _IPermission;
};
}
