/// <summary>
/// Name: System::Security::ISecurityEncodable
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security {
class ISecurityEncodable {
public:
    inline static _TypePtr _ISecurityEncodable;
};
}
