/// <summary>
/// Name: System::Security::ISecurityPolicyEncodable
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security {
class ISecurityPolicyEncodable {
public:
    inline static _TypePtr _ISecurityPolicyEncodable;
};
}
