/// <summary>
/// Name: System::Security::IStackWalk
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security {
class IStackWalk {
public:
    inline static _TypePtr _IStackWalk;
};
}
