/// <summary>
/// Name: System::Security::PermissionSet
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security {
class PermissionSet {
public:
    inline static _TypePtr _PermissionSet;
};
}
