/// <summary>
/// Name: System::Security::PolicyLevelType
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security {
class PolicyLevelType {
public:
    inline static _TypePtr _PolicyLevelType;
};
}
