/// <summary>
/// Name: System::Security::SecurityContext
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security {
class SecurityContext {
public:
    inline static _TypePtr _SecurityContext;
};
}
