/// <summary>
/// Name: System::Security::SecurityCriticalAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security {
class SecurityCriticalAttribute {
public:
    inline static _TypePtr _SecurityCriticalAttribute;
};
}
