/// <summary>
/// Name: System::Security::SecurityCriticalScope
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security {
class SecurityCriticalScope {
public:
    inline static _TypePtr _SecurityCriticalScope;
};
}
