/// <summary>
/// Name: System::Security::SecurityException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security {
class SecurityException {
public:
    inline static _TypePtr _SecurityException;
};
}
