/// <summary>
/// Name: System::Security::SecurityElement
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security {
class SecurityElement {
public:
    inline static _TypePtr _SecurityElement;
};
}
