/// <summary>
/// Name: System::Security::SecurityZone
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security {
class SecurityZone {
public:
    inline static _TypePtr _SecurityZone;
};
}
