/// <summary>
/// Name: System::Security::SecurityTreatAsSafeAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security {
class SecurityTreatAsSafeAttribute {
public:
    inline static _TypePtr _SecurityTreatAsSafeAttribute;
};
}
