/// <summary>
/// Name: System::Security::SecuritySafeCriticalAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security {
class SecuritySafeCriticalAttribute {
public:
    inline static _TypePtr _SecuritySafeCriticalAttribute;
};
}
