/// <summary>
/// Name: System::Security::SecureString
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security {
class SecureString {
public:
    inline static _TypePtr _SecureString;
};
}
