/// <summary>
/// Name: System::Security::SecurityState
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security {
class SecurityState {
public:
    inline static _TypePtr _SecurityState;
};
}
