/// <summary>
/// Name: System::Security::SecurityManager
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security {
class SecurityManager {
public:
    inline static _TypePtr _SecurityManager;
};
}
