/// <summary>
/// Name: System::Security::SecurityTransparentAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security {
class SecurityTransparentAttribute {
public:
    inline static _TypePtr _SecurityTransparentAttribute;
};
}
