/// <summary>
/// Name: System::Security::SuppressUnmanagedCodeSecurityAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security {
class SuppressUnmanagedCodeSecurityAttribute {
public:
    inline static _TypePtr _SuppressUnmanagedCodeSecurityAttribute;
};
}
