/// <summary>
/// Name: System::Security::UnverifiableCodeAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security {
class UnverifiableCodeAttribute {
public:
    inline static _TypePtr _UnverifiableCodeAttribute;
};
}
