/// <summary>
/// Name: System::Security::VerificationException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security {
class VerificationException {
public:
    inline static _TypePtr _VerificationException;
};
}
