/// <summary>
/// Name: System::Security::XmlSyntaxException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security {
class XmlSyntaxException {
public:
    inline static _TypePtr _XmlSyntaxException;
};
}
