/// <summary>
/// Name: System::Diagnostics::CodeAnalysis::SuppressMessageAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Diagnostics::CodeAnalysis {
class SuppressMessageAttribute {
public:
    inline static _TypePtr _SuppressMessageAttribute;
};
}
