/// <summary>
/// Name: System::_AppDomain
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class _AppDomain {
public:
    inline static _TypePtr __AppDomain;
};
}
