/// <summary>
/// Name: System::AccessViolationException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class AccessViolationException {
public:
    inline static _TypePtr _AccessViolationException;
};
}
