/// <summary>
/// Name: System::ActivationContext
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class ActivationContext {
public:
    inline static _TypePtr _ActivationContext;
};
}
