/// <summary>
/// Name: System::Activator
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class Activator {
public:
    inline static _TypePtr _Activator;
};
}
