/// <summary>
/// Name: System::AppDomainInitializer
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class AppDomainInitializer {
public:
    inline static _TypePtr _AppDomainInitializer;
};
}
