/// <summary>
/// Name: System::AppDomain
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class AppDomain {
public:
    inline static _TypePtr _AppDomain;
};
}
