/// <summary>
/// Name: System::AppDomainSetup
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class AppDomainSetup {
public:
    inline static _TypePtr _AppDomainSetup;
};
}
