/// <summary>
/// Name: System::AppDomainManagerInitializationOptions
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class AppDomainManagerInitializationOptions {
public:
    inline static _TypePtr _AppDomainManagerInitializationOptions;
};
}
