/// <summary>
/// Name: System::AppDomainManager
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class AppDomainManager {
public:
    inline static _TypePtr _AppDomainManager;
};
}
