/// <summary>
/// Name: System::AppDomainUnloadedException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class AppDomainUnloadedException {
public:
    inline static _TypePtr _AppDomainUnloadedException;
};
}
