/// <summary>
/// Name: System::ApplicationIdentity
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class ApplicationIdentity {
public:
    inline static _TypePtr _ApplicationIdentity;
};
}
