/// <summary>
/// Name: System::ApplicationException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class ApplicationException {
public:
    inline static _TypePtr _ApplicationException;
};
}
