/// <summary>
/// Name: System::ApplicationId
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class ApplicationId {
public:
    inline static _TypePtr _ApplicationId;
};
}
