/// <summary>
/// Name: System::ArgIterator
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class ArgIterator {
public:
    inline static _TypePtr _ArgIterator;
};
}
