/// <summary>
/// Name: System::ArgumentException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class ArgumentException {
public:
    inline static _TypePtr _ArgumentException;
};
}
