/// <summary>
/// Name: System::ArgumentOutOfRangeException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class ArgumentOutOfRangeException {
public:
    inline static _TypePtr _ArgumentOutOfRangeException;
};
}
