/// <summary>
/// Name: System::ArgumentNullException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class ArgumentNullException {
public:
    inline static _TypePtr _ArgumentNullException;
};
}
