/// <summary>
/// Name: System::ArithmeticException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class ArithmeticException {
public:
    inline static _TypePtr _ArithmeticException;
};
}
