/// <summary>
/// Name: System::ArrayTypeMismatchException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class ArrayTypeMismatchException {
public:
    inline static _TypePtr _ArrayTypeMismatchException;
};
}
