/// <summary>
/// Name: System::Array
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class Array {
public:
    inline static _TypePtr _Array;
};
}
