/// <summary>
/// Name: System::AssemblyLoadEventHandler
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class AssemblyLoadEventHandler {
public:
    inline static _TypePtr _AssemblyLoadEventHandler;
};
}
