/// <summary>
/// Name: System::AsyncCallback
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class AsyncCallback {
public:
    inline static _TypePtr _AsyncCallback;
};
}
