/// <summary>
/// Name: System::AttributeTargets
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class AttributeTargets {
public:
    inline static _TypePtr _AttributeTargets;
};
}
