/// <summary>
/// Name: System::Attribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class Attribute {
public:
    inline static _TypePtr _Attribute;
};
}
