/// <summary>
/// Name: System::AttributeUsageAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class AttributeUsageAttribute {
public:
    inline static _TypePtr _AttributeUsageAttribute;
};
}
