/// <summary>
/// Name: System::BadImageFormatException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class BadImageFormatException {
public:
    inline static _TypePtr _BadImageFormatException;
};
}
