/// <summary>
/// Name: System::Base64FormattingOptions
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class Base64FormattingOptions {
public:
    inline static _TypePtr _Base64FormattingOptions;
};
}
