/// <summary>
/// Name: System::Boolean
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class Boolean {
public:
    inline static _TypePtr _Boolean;
};
}
