/// <summary>
/// Name: System::Buffer
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class Buffer {
public:
    inline static _TypePtr _Buffer;
};
}
