/// <summary>
/// Name: System::Byte
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class Byte {
public:
    inline static _TypePtr _Byte;
};
}
