/// <summary>
/// Name: System::CannotUnloadAppDomainException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class CannotUnloadAppDomainException {
public:
    inline static _TypePtr _CannotUnloadAppDomainException;
};
}
