/// <summary>
/// Name: System::Char
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class Char {
public:
    inline static _TypePtr _Char;
};
}
