/// <summary>
/// Name: System::CharEnumerator
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class CharEnumerator {
public:
    inline static _TypePtr _CharEnumerator;
};
}
