/// <summary>
/// Name: System::CLSCompliantAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class CLSCompliantAttribute {
public:
    inline static _TypePtr _CLSCompliantAttribute;
};
}
