/// <summary>
/// Name: System::ConsoleModifiers
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class ConsoleModifiers {
public:
    inline static _TypePtr _ConsoleModifiers;
};
}
