/// <summary>
/// Name: System::ConsoleKeyInfo
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class ConsoleKeyInfo {
public:
    inline static _TypePtr _ConsoleKeyInfo;
};
}
