/// <summary>
/// Name: System::ConsoleSpecialKey
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class ConsoleSpecialKey {
public:
    inline static _TypePtr _ConsoleSpecialKey;
};
}
