/// <summary>
/// Name: System::ConsoleKey
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class ConsoleKey {
public:
    inline static _TypePtr _ConsoleKey;
};
}
