/// <summary>
/// Name: System::ConsoleCancelEventArgs
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class ConsoleCancelEventArgs {
public:
    inline static _TypePtr _ConsoleCancelEventArgs;
};
}
