/// <summary>
/// Name: System::ConsoleColor
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class ConsoleColor {
public:
    inline static _TypePtr _ConsoleColor;
};
}
