/// <summary>
/// Name: System::Console
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class Console {
public:
    inline static _TypePtr _Console;
};
}
