/// <summary>
/// Name: System::ConsoleCancelEventHandler
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class ConsoleCancelEventHandler {
public:
    inline static _TypePtr _ConsoleCancelEventHandler;
};
}
