/// <summary>
/// Name: System::ContextBoundObject
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class ContextBoundObject {
public:
    inline static _TypePtr _ContextBoundObject;
};
}
