/// <summary>
/// Name: System::ContextMarshalException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class ContextMarshalException {
public:
    inline static _TypePtr _ContextMarshalException;
};
}
