/// <summary>
/// Name: System::ContextStaticAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class ContextStaticAttribute {
public:
    inline static _TypePtr _ContextStaticAttribute;
};
}
