/// <summary>
/// Name: System::Convert
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class Convert {
public:
    inline static _TypePtr _Convert;
};
}
