/// <summary>
/// Name: System::CrossAppDomainDelegate
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class CrossAppDomainDelegate {
public:
    inline static _TypePtr _CrossAppDomainDelegate;
};
}
