/// <summary>
/// Name: System::DataMisalignedException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class DataMisalignedException {
public:
    inline static _TypePtr _DataMisalignedException;
};
}
