/// <summary>
/// Name: System::DateTimeKind
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class DateTimeKind {
public:
    inline static _TypePtr _DateTimeKind;
};
}
