/// <summary>
/// Name: System::DateTime
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class DateTime {
public:
    inline static _TypePtr _DateTime;
};
}
