/// <summary>
/// Name: System::DateTimeOffset
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class DateTimeOffset {
public:
    inline static _TypePtr _DateTimeOffset;
};
}
