/// <summary>
/// Name: System::DayOfWeek
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class DayOfWeek {
public:
    inline static _TypePtr _DayOfWeek;
};
}
