/// <summary>
/// Name: System::DBNull
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class DBNull {
public:
    inline static _TypePtr _DBNull;
};
}
