/// <summary>
/// Name: System::Decimal
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class Decimal {
public:
    inline static _TypePtr _Decimal;
};
}
