/// <summary>
/// Name: System::Delegate
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class Delegate {
public:
    inline static _TypePtr _Delegate;
};
}
