/// <summary>
/// Name: System::DivideByZeroException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class DivideByZeroException {
public:
    inline static _TypePtr _DivideByZeroException;
};
}
