/// <summary>
/// Name: System::DllNotFoundException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class DllNotFoundException {
public:
    inline static _TypePtr _DllNotFoundException;
};
}
