/// <summary>
/// Name: System::Double
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class Double {
public:
    inline static _TypePtr _Double;
};
}
