/// <summary>
/// Name: System::DuplicateWaitObjectException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class DuplicateWaitObjectException {
public:
    inline static _TypePtr _DuplicateWaitObjectException;
};
}
