/// <summary>
/// Name: System::EntryPointNotFoundException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class EntryPointNotFoundException {
public:
    inline static _TypePtr _EntryPointNotFoundException;
};
}
