/// <summary>
/// Name: System::Enum
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class Enum {
public:
    inline static _TypePtr _Enum;
};
}
