/// <summary>
/// Name: System::EnvironmentVariableTarget
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class EnvironmentVariableTarget {
public:
    inline static _TypePtr _EnvironmentVariableTarget;
};
}
