/// <summary>
/// Name: System::Environment
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class Environment {
public:
    inline static _TypePtr _Environment;
};
}
