/// <summary>
/// Name: System::EventArgs
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class EventArgs {
public:
    inline static _TypePtr _EventArgs;
};
}
