/// <summary>
/// Name: System::Exception
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class Exception {
public:
    inline static _TypePtr _Exception;
};
}
