/// <summary>
/// Name: System::ExecutionEngineException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class ExecutionEngineException {
public:
    inline static _TypePtr _ExecutionEngineException;
};
}
