/// <summary>
/// Name: System::FieldAccessException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class FieldAccessException {
public:
    inline static _TypePtr _FieldAccessException;
};
}
