/// <summary>
/// Name: System::FlagsAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class FlagsAttribute {
public:
    inline static _TypePtr _FlagsAttribute;
};
}
