/// <summary>
/// Name: System::GC
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class GC {
public:
    inline static _TypePtr _GC;
};
}
