/// <summary>
/// Name: System::GCCollectionMode
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class GCCollectionMode {
public:
    inline static _TypePtr _GCCollectionMode;
};
}
