/// <summary>
/// Name: System::GCNotificationStatus
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class GCNotificationStatus {
public:
    inline static _TypePtr _GCNotificationStatus;
};
}
