/// <summary>
/// Name: System::Guid
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class Guid {
public:
    inline static _TypePtr _Guid;
};
}
