/// <summary>
/// Name: System::IAppDomainSetup
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class IAppDomainSetup {
public:
    inline static _TypePtr _IAppDomainSetup;
};
}
