/// <summary>
/// Name: System::IAsyncResult
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class IAsyncResult {
public:
    inline static _TypePtr _IAsyncResult;
};
}
