/// <summary>
/// Name: System::ICloneable
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class ICloneable {
public:
    inline static _TypePtr _ICloneable;
};
}
