/// <summary>
/// Name: System::IComparable
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class IComparable {
public:
    inline static _TypePtr _IComparable;
};
}
