/// <summary>
/// Name: System::IConvertible
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class IConvertible {
public:
    inline static _TypePtr _IConvertible;
};
}
