/// <summary>
/// Name: System::ICustomFormatter
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class ICustomFormatter {
public:
    inline static _TypePtr _ICustomFormatter;
};
}
