/// <summary>
/// Name: System::IDisposable
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class IDisposable {
public:
    inline static _TypePtr _IDisposable;
};
}
