/// <summary>
/// Name: System::IFormattable
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class IFormattable {
public:
    inline static _TypePtr _IFormattable;
};
}
