/// <summary>
/// Name: System::IFormatProvider
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class IFormatProvider {
public:
    inline static _TypePtr _IFormatProvider;
};
}
