/// <summary>
/// Name: System::IndexOutOfRangeException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class IndexOutOfRangeException {
public:
    inline static _TypePtr _IndexOutOfRangeException;
};
}
