/// <summary>
/// Name: System::InsufficientMemoryException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class InsufficientMemoryException {
public:
    inline static _TypePtr _InsufficientMemoryException;
};
}
