/// <summary>
/// Name: System::Int16
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class Int16 {
public:
    inline static _TypePtr _Int16;
};
}
