/// <summary>
/// Name: System::Int32
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class Int32 {
public:
    inline static _TypePtr _Int32;
};
}
