/// <summary>
/// Name: System::Int64
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class Int64 {
public:
    inline static _TypePtr _Int64;
};
}
