/// <summary>
/// Name: System::IntPtr
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class IntPtr {
public:
    inline static _TypePtr _IntPtr;
};
}
