/// <summary>
/// Name: System::InvalidCastException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class InvalidCastException {
public:
    inline static _TypePtr _InvalidCastException;
};
}
