/// <summary>
/// Name: System::InvalidProgramException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class InvalidProgramException {
public:
    inline static _TypePtr _InvalidProgramException;
};
}
