/// <summary>
/// Name: System::InvalidOperationException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class InvalidOperationException {
public:
    inline static _TypePtr _InvalidOperationException;
};
}
