/// <summary>
/// Name: System::IServiceProvider
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class IServiceProvider {
public:
    inline static _TypePtr _IServiceProvider;
};
}
