/// <summary>
/// Name: System::LoaderOptimization
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class LoaderOptimization {
public:
    inline static _TypePtr _LoaderOptimization;
};
}
