/// <summary>
/// Name: System::LoaderOptimizationAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class LoaderOptimizationAttribute {
public:
    inline static _TypePtr _LoaderOptimizationAttribute;
};
}
