/// <summary>
/// Name: System::LocalDataStoreSlot
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class LocalDataStoreSlot {
public:
    inline static _TypePtr _LocalDataStoreSlot;
};
}
