/// <summary>
/// Name: System::MarshalByRefObject
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class MarshalByRefObject {
public:
    inline static _TypePtr _MarshalByRefObject;
};
}
