/// <summary>
/// Name: System::Math
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class Math {
public:
    inline static _TypePtr _Math;
};
}
