/// <summary>
/// Name: System::MemberAccessException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class MemberAccessException {
public:
    inline static _TypePtr _MemberAccessException;
};
}
