/// <summary>
/// Name: System::MethodAccessException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class MethodAccessException {
public:
    inline static _TypePtr _MethodAccessException;
};
}
