/// <summary>
/// Name: System::MidpointRounding
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class MidpointRounding {
public:
    inline static _TypePtr _MidpointRounding;
};
}
