/// <summary>
/// Name: System::MissingFieldException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class MissingFieldException {
public:
    inline static _TypePtr _MissingFieldException;
};
}
