/// <summary>
/// Name: System::MissingMethodException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class MissingMethodException {
public:
    inline static _TypePtr _MissingMethodException;
};
}
