/// <summary>
/// Name: System::ModuleHandle
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class ModuleHandle {
public:
    inline static _TypePtr _ModuleHandle;
};
}
