/// <summary>
/// Name: System::MTAThreadAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class MTAThreadAttribute {
public:
    inline static _TypePtr _MTAThreadAttribute;
};
}
