/// <summary>
/// Name: System::MulticastNotSupportedException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class MulticastNotSupportedException {
public:
    inline static _TypePtr _MulticastNotSupportedException;
};
}
