/// <summary>
/// Name: System::MulticastDelegate
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class MulticastDelegate {
public:
    inline static _TypePtr _MulticastDelegate;
};
}
