/// <summary>
/// Name: System::NonSerializedAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class NonSerializedAttribute {
public:
    inline static _TypePtr _NonSerializedAttribute;
};
}
