/// <summary>
/// Name: System::NotFiniteNumberException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class NotFiniteNumberException {
public:
    inline static _TypePtr _NotFiniteNumberException;
};
}
