/// <summary>
/// Name: System::NotImplementedException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class NotImplementedException {
public:
    inline static _TypePtr _NotImplementedException;
};
}
