/// <summary>
/// Name: System::NotSupportedException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class NotSupportedException {
public:
    inline static _TypePtr _NotSupportedException;
};
}
