/// <summary>
/// Name: System::NullReferenceException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class NullReferenceException {
public:
    inline static _TypePtr _NullReferenceException;
};
}
