/// <summary>
/// Name: System::Nullable
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class Nullable {
public:
    inline static _TypePtr _Nullable;
};
}
