/// <summary>
/// Name: System::Object
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class Object {
public:
    inline static _TypePtr _Object;
};
}
