/// <summary>
/// Name: System::ObjectDisposedException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class ObjectDisposedException {
public:
    inline static _TypePtr _ObjectDisposedException;
};
}
