/// <summary>
/// Name: System::ObsoleteAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class ObsoleteAttribute {
public:
    inline static _TypePtr _ObsoleteAttribute;
};
}
