/// <summary>
/// Name: System::OperatingSystem
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class OperatingSystem {
public:
    inline static _TypePtr _OperatingSystem;
};
}
