/// <summary>
/// Name: System::OperationCanceledException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class OperationCanceledException {
public:
    inline static _TypePtr _OperationCanceledException;
};
}
