/// <summary>
/// Name: System::OutOfMemoryException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class OutOfMemoryException {
public:
    inline static _TypePtr _OutOfMemoryException;
};
}
