/// <summary>
/// Name: System::OverflowException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class OverflowException {
public:
    inline static _TypePtr _OverflowException;
};
}
