/// <summary>
/// Name: System::ParamArrayAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class ParamArrayAttribute {
public:
    inline static _TypePtr _ParamArrayAttribute;
};
}
