/// <summary>
/// Name: System::PlatformNotSupportedException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class PlatformNotSupportedException {
public:
    inline static _TypePtr _PlatformNotSupportedException;
};
}
