/// <summary>
/// Name: System::PlatformID
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class PlatformID {
public:
    inline static _TypePtr _PlatformID;
};
}
