/// <summary>
/// Name: System::Random
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class Random {
public:
    inline static _TypePtr _Random;
};
}
