/// <summary>
/// Name: System::RankException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class RankException {
public:
    inline static _TypePtr _RankException;
};
}
