/// <summary>
/// Name: System::ResolveEventHandler
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class ResolveEventHandler {
public:
    inline static _TypePtr _ResolveEventHandler;
};
}
