/// <summary>
/// Name: System::ResolveEventArgs
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class ResolveEventArgs {
public:
    inline static _TypePtr _ResolveEventArgs;
};
}
