/// <summary>
/// Name: System::RuntimeMethodHandle
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class RuntimeMethodHandle {
public:
    inline static _TypePtr _RuntimeMethodHandle;
};
}
