/// <summary>
/// Name: System::RuntimeFieldHandle
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class RuntimeFieldHandle {
public:
    inline static _TypePtr _RuntimeFieldHandle;
};
}
