/// <summary>
/// Name: System::RuntimeTypeHandle
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class RuntimeTypeHandle {
public:
    inline static _TypePtr _RuntimeTypeHandle;
};
}
