/// <summary>
/// Name: System::SByte
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class SByte {
public:
    inline static _TypePtr _SByte;
};
}
