/// <summary>
/// Name: System::SerializableAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class SerializableAttribute {
public:
    inline static _TypePtr _SerializableAttribute;
};
}
