/// <summary>
/// Name: System::Single
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class Single {
public:
    inline static _TypePtr _Single;
};
}
