/// <summary>
/// Name: System::StackOverflowException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class StackOverflowException {
public:
    inline static _TypePtr _StackOverflowException;
};
}
