/// <summary>
/// Name: System::STAThreadAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class STAThreadAttribute {
public:
    inline static _TypePtr _STAThreadAttribute;
};
}
