/// <summary>
/// Name: System::StringComparer
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class StringComparer {
public:
    inline static _TypePtr _StringComparer;
};
}
