/// <summary>
/// Name: System::String
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class String {
public:
    inline static _TypePtr _String;
};
}
