/// <summary>
/// Name: System::StringSplitOptions
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class StringSplitOptions {
public:
    inline static _TypePtr _StringSplitOptions;
};
}
