/// <summary>
/// Name: System::StringComparison
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class StringComparison {
public:
    inline static _TypePtr _StringComparison;
};
}
