/// <summary>
/// Name: System::ThreadStaticAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class ThreadStaticAttribute {
public:
    inline static _TypePtr _ThreadStaticAttribute;
};
}
