/// <summary>
/// Name: System::TimeSpan
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class TimeSpan {
public:
    inline static _TypePtr _TimeSpan;
};
}
