/// <summary>
/// Name: System::TimeZone
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class TimeZone {
public:
    inline static _TypePtr _TimeZone;
};
}
