/// <summary>
/// Name: System::TimeoutException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class TimeoutException {
public:
    inline static _TypePtr _TimeoutException;
};
}
