/// <summary>
/// Name: System::TypeUnloadedException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class TypeUnloadedException {
public:
    inline static _TypePtr _TypeUnloadedException;
};
}
