/// <summary>
/// Name: System::TypeLoadException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class TypeLoadException {
public:
    inline static _TypePtr _TypeLoadException;
};
}
