/// <summary>
/// Name: System::TypedReference
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class TypedReference {
public:
    inline static _TypePtr _TypedReference;
};
}
