/// <summary>
/// Name: System::Type
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class Type {
public:
    inline static _TypePtr _Type;
};
}
