/// <summary>
/// Name: System::TypeInitializationException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class TypeInitializationException {
public:
    inline static _TypePtr _TypeInitializationException;
};
}
