/// <summary>
/// Name: System::TypeCode
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class TypeCode {
public:
    inline static _TypePtr _TypeCode;
};
}
