/// <summary>
/// Name: System::UInt16
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class UInt16 {
public:
    inline static _TypePtr _UInt16;
};
}
