/// <summary>
/// Name: System::UInt64
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class UInt64 {
public:
    inline static _TypePtr _UInt64;
};
}
