/// <summary>
/// Name: System::UIntPtr
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class UIntPtr {
public:
    inline static _TypePtr _UIntPtr;
};
}
