/// <summary>
/// Name: System::UnauthorizedAccessException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class UnauthorizedAccessException {
public:
    inline static _TypePtr _UnauthorizedAccessException;
};
}
