/// <summary>
/// Name: System::UnhandledExceptionEventHandler
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class UnhandledExceptionEventHandler {
public:
    inline static _TypePtr _UnhandledExceptionEventHandler;
};
}
