/// <summary>
/// Name: System::UnhandledExceptionEventArgs
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class UnhandledExceptionEventArgs {
public:
    inline static _TypePtr _UnhandledExceptionEventArgs;
};
}
