/// <summary>
/// Name: System::ValueType
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class ValueType {
public:
    inline static _TypePtr _ValueType;
};
}
