/// <summary>
/// Name: System::Version
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class Version {
public:
    inline static _TypePtr _Version;
};
}
