/// <summary>
/// Name: System::Void
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class Void {
public:
    inline static _TypePtr _Void;
};
}
