/// <summary>
/// Name: System::WeakReference
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System {
class WeakReference {
public:
    inline static _TypePtr _WeakReference;
};
}
