/// <summary>
/// Name: System::Runtime::ConstrainedExecution::Cer
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::ConstrainedExecution {
class Cer {
public:
    inline static _TypePtr _Cer;
};
}
