/// <summary>
/// Name: System::Runtime::ConstrainedExecution::CriticalFinalizerObject
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::ConstrainedExecution {
class CriticalFinalizerObject {
public:
    inline static _TypePtr _CriticalFinalizerObject;
};
}
