/// <summary>
/// Name: System::Runtime::ConstrainedExecution::PrePrepareMethodAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::ConstrainedExecution {
class PrePrepareMethodAttribute {
public:
    inline static _TypePtr _PrePrepareMethodAttribute;
};
}
