/// <summary>
/// Name: System::Runtime::ConstrainedExecution::ReliabilityContractAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::ConstrainedExecution {
class ReliabilityContractAttribute {
public:
    inline static _TypePtr _ReliabilityContractAttribute;
};
}
