/// <summary>
/// Name: System::Security::Principal::GenericPrincipal
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Principal {
class GenericPrincipal {
public:
    inline static _TypePtr _GenericPrincipal;
};
}
