/// <summary>
/// Name: System::Security::Principal::GenericIdentity
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Principal {
class GenericIdentity {
public:
    inline static _TypePtr _GenericIdentity;
};
}
