/// <summary>
/// Name: System::Security::Principal::IdentityReference
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Principal {
class IdentityReference {
public:
    inline static _TypePtr _IdentityReference;
};
}
