/// <summary>
/// Name: System::Security::Principal::IdentityReferenceCollection
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Principal {
class IdentityReferenceCollection {
public:
    inline static _TypePtr _IdentityReferenceCollection;
};
}
