/// <summary>
/// Name: System::Security::Principal::IdentityNotMappedException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Principal {
class IdentityNotMappedException {
public:
    inline static _TypePtr _IdentityNotMappedException;
};
}
