/// <summary>
/// Name: System::Security::Principal::IIdentity
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Principal {
class IIdentity {
public:
    inline static _TypePtr _IIdentity;
};
}
