/// <summary>
/// Name: System::Security::Principal::IPrincipal
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Principal {
class IPrincipal {
public:
    inline static _TypePtr _IPrincipal;
};
}
