/// <summary>
/// Name: System::Security::Principal::NTAccount
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Principal {
class NTAccount {
public:
    inline static _TypePtr _NTAccount;
};
}
