/// <summary>
/// Name: System::Security::Principal::PrincipalPolicy
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Principal {
class PrincipalPolicy {
public:
    inline static _TypePtr _PrincipalPolicy;
};
}
