/// <summary>
/// Name: System::Security::Principal::SecurityIdentifier
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Principal {
class SecurityIdentifier {
public:
    inline static _TypePtr _SecurityIdentifier;
};
}
