/// <summary>
/// Name: System::Security::Principal::TokenImpersonationLevel
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Principal {
class TokenImpersonationLevel {
public:
    inline static _TypePtr _TokenImpersonationLevel;
};
}
