/// <summary>
/// Name: System::Security::Principal::TokenAccessLevels
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Principal {
class TokenAccessLevels {
public:
    inline static _TypePtr _TokenAccessLevels;
};
}
