/// <summary>
/// Name: System::Security::Principal::WellKnownSidType
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Principal {
class WellKnownSidType {
public:
    inline static _TypePtr _WellKnownSidType;
};
}
