/// <summary>
/// Name: System::Security::Principal::WindowsBuiltInRole
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Principal {
class WindowsBuiltInRole {
public:
    inline static _TypePtr _WindowsBuiltInRole;
};
}
