/// <summary>
/// Name: System::Security::Principal::WindowsImpersonationContext
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Principal {
class WindowsImpersonationContext {
public:
    inline static _TypePtr _WindowsImpersonationContext;
};
}
