/// <summary>
/// Name: System::Security::Principal::WindowsAccountType
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Principal {
class WindowsAccountType {
public:
    inline static _TypePtr _WindowsAccountType;
};
}
