/// <summary>
/// Name: System::Security::Principal::WindowsPrincipal
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Principal {
class WindowsPrincipal {
public:
    inline static _TypePtr _WindowsPrincipal;
};
}
