/// <summary>
/// Name: System::Security::Principal::WindowsIdentity
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Principal {
class WindowsIdentity {
public:
    inline static _TypePtr _WindowsIdentity;
};
}
