/// <summary>
/// Name: System::Runtime::Versioning::ResourceConsumptionAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Versioning {
class ResourceConsumptionAttribute {
public:
    inline static _TypePtr _ResourceConsumptionAttribute;
};
}
