/// <summary>
/// Name: System::Runtime::Versioning::ResourceScope
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Versioning {
class ResourceScope {
public:
    inline static _TypePtr _ResourceScope;
};
}
