/// <summary>
/// Name: System::Runtime::Versioning::ResourceExposureAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Versioning {
class ResourceExposureAttribute {
public:
    inline static _TypePtr _ResourceExposureAttribute;
};
}
