/// <summary>
/// Name: System::Runtime::Versioning::VersioningHelper
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Versioning {
class VersioningHelper {
public:
    inline static _TypePtr _VersioningHelper;
};
}
