/// <summary>
/// Name: System::Runtime::Serialization::Formatters::Binary::BinaryFormatter
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Serialization::Formatters::Binary {
class BinaryFormatter {
public:
    inline static _TypePtr _BinaryFormatter;
};
}
