/// <summary>
/// Name: System::Runtime::Serialization::FormatterConverter
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Serialization {
class FormatterConverter {
public:
    inline static _TypePtr _FormatterConverter;
};
}
