/// <summary>
/// Name: System::Runtime::Serialization::FormatterServices
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Serialization {
class FormatterServices {
public:
    inline static _TypePtr _FormatterServices;
};
}
