/// <summary>
/// Name: System::Runtime::Serialization::Formatter
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Serialization {
class Formatter {
public:
    inline static _TypePtr _Formatter;
};
}
