/// <summary>
/// Name: System::Runtime::Serialization::IDeserializationCallback
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Serialization {
class IDeserializationCallback {
public:
    inline static _TypePtr _IDeserializationCallback;
};
}
