/// <summary>
/// Name: System::Runtime::Serialization::IFormatterConverter
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Serialization {
class IFormatterConverter {
public:
    inline static _TypePtr _IFormatterConverter;
};
}
