/// <summary>
/// Name: System::Runtime::Serialization::IObjectReference
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Serialization {
class IObjectReference {
public:
    inline static _TypePtr _IObjectReference;
};
}
