/// <summary>
/// Name: System::Runtime::Serialization::ISerializable
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Serialization {
class ISerializable {
public:
    inline static _TypePtr _ISerializable;
};
}
