/// <summary>
/// Name: System::Runtime::Serialization::ISerializationSurrogate
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Serialization {
class ISerializationSurrogate {
public:
    inline static _TypePtr _ISerializationSurrogate;
};
}
