/// <summary>
/// Name: System::Runtime::Serialization::ISurrogateSelector
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Serialization {
class ISurrogateSelector {
public:
    inline static _TypePtr _ISurrogateSelector;
};
}
