/// <summary>
/// Name: System::Runtime::Serialization::ObjectIDGenerator
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Serialization {
class ObjectIDGenerator {
public:
    inline static _TypePtr _ObjectIDGenerator;
};
}
