/// <summary>
/// Name: System::Runtime::Serialization::ObjectManager
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Serialization {
class ObjectManager {
public:
    inline static _TypePtr _ObjectManager;
};
}
