/// <summary>
/// Name: System::Runtime::Serialization::OnDeserializedAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Serialization {
class OnDeserializedAttribute {
public:
    inline static _TypePtr _OnDeserializedAttribute;
};
}
