/// <summary>
/// Name: System::Runtime::Serialization::OnDeserializingAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Serialization {
class OnDeserializingAttribute {
public:
    inline static _TypePtr _OnDeserializingAttribute;
};
}
