/// <summary>
/// Name: System::Runtime::Serialization::OnSerializedAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Serialization {
class OnSerializedAttribute {
public:
    inline static _TypePtr _OnSerializedAttribute;
};
}
