/// <summary>
/// Name: System::Runtime::Serialization::OnSerializingAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Serialization {
class OnSerializingAttribute {
public:
    inline static _TypePtr _OnSerializingAttribute;
};
}
