/// <summary>
/// Name: System::Runtime::Serialization::OptionalFieldAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Serialization {
class OptionalFieldAttribute {
public:
    inline static _TypePtr _OptionalFieldAttribute;
};
}
