/// <summary>
/// Name: System::Runtime::Serialization::SerializationObjectManager
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Serialization {
class SerializationObjectManager {
public:
    inline static _TypePtr _SerializationObjectManager;
};
}
