/// <summary>
/// Name: System::Runtime::Serialization::SerializationBinder
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Serialization {
class SerializationBinder {
public:
    inline static _TypePtr _SerializationBinder;
};
}
