/// <summary>
/// Name: System::Runtime::Serialization::SerializationEntry
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Serialization {
class SerializationEntry {
public:
    inline static _TypePtr _SerializationEntry;
};
}
