/// <summary>
/// Name: System::Runtime::Serialization::SerializationInfo
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Serialization {
class SerializationInfo {
public:
    inline static _TypePtr _SerializationInfo;
};
}
