/// <summary>
/// Name: System::Runtime::Serialization::SerializationException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Serialization {
class SerializationException {
public:
    inline static _TypePtr _SerializationException;
};
}
