/// <summary>
/// Name: System::Runtime::Serialization::SerializationInfoEnumerator
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Serialization {
class SerializationInfoEnumerator {
public:
    inline static _TypePtr _SerializationInfoEnumerator;
};
}
