/// <summary>
/// Name: System::Runtime::Serialization::StreamingContext
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Serialization {
class StreamingContext {
public:
    inline static _TypePtr _StreamingContext;
};
}
