/// <summary>
/// Name: System::Runtime::Serialization::StreamingContextStates
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Serialization {
class StreamingContextStates {
public:
    inline static _TypePtr _StreamingContextStates;
};
}
