/// <summary>
/// Name: System::Runtime::Serialization::SurrogateSelector
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Serialization {
class SurrogateSelector {
public:
    inline static _TypePtr _SurrogateSelector;
};
}
