/// <summary>
/// Name: System::Security::Cryptography::AsymmetricSignatureDeformatter
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Cryptography {
class AsymmetricSignatureDeformatter {
public:
    inline static _TypePtr _AsymmetricSignatureDeformatter;
};
}
