/// <summary>
/// Name: System::Security::Cryptography::AsymmetricSignatureFormatter
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Cryptography {
class AsymmetricSignatureFormatter {
public:
    inline static _TypePtr _AsymmetricSignatureFormatter;
};
}
