/// <summary>
/// Name: System::Security::Cryptography::AsymmetricKeyExchangeFormatter
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Cryptography {
class AsymmetricKeyExchangeFormatter {
public:
    inline static _TypePtr _AsymmetricKeyExchangeFormatter;
};
}
