/// <summary>
/// Name: System::Security::Cryptography::AsymmetricAlgorithm
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Cryptography {
class AsymmetricAlgorithm {
public:
    inline static _TypePtr _AsymmetricAlgorithm;
};
}
