/// <summary>
/// Name: System::Security::Cryptography::AsymmetricKeyExchangeDeformatter
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Cryptography {
class AsymmetricKeyExchangeDeformatter {
public:
    inline static _TypePtr _AsymmetricKeyExchangeDeformatter;
};
}
