/// <summary>
/// Name: System::Security::Cryptography::CipherMode
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Cryptography {
class CipherMode {
public:
    inline static _TypePtr _CipherMode;
};
}
