/// <summary>
/// Name: System::Security::Cryptography::CryptoStreamMode
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Cryptography {
class CryptoStreamMode {
public:
    inline static _TypePtr _CryptoStreamMode;
};
}
