/// <summary>
/// Name: System::Security::Cryptography::CryptographicUnexpectedOperationException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Cryptography {
class CryptographicUnexpectedOperationException {
public:
    inline static _TypePtr _CryptographicUnexpectedOperationException;
};
}
