/// <summary>
/// Name: System::Security::Cryptography::CryptoConfig
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Cryptography {
class CryptoConfig {
public:
    inline static _TypePtr _CryptoConfig;
};
}
