/// <summary>
/// Name: System::Security::Cryptography::CryptoStream
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Cryptography {
class CryptoStream {
public:
    inline static _TypePtr _CryptoStream;
};
}
