/// <summary>
/// Name: System::Security::Cryptography::CryptographicException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Cryptography {
class CryptographicException {
public:
    inline static _TypePtr _CryptographicException;
};
}
