/// <summary>
/// Name: System::Security::Cryptography::CryptoAPITransform
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Cryptography {
class CryptoAPITransform {
public:
    inline static _TypePtr _CryptoAPITransform;
};
}
