/// <summary>
/// Name: System::Security::Cryptography::CspKeyContainerInfo
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Cryptography {
class CspKeyContainerInfo {
public:
    inline static _TypePtr _CspKeyContainerInfo;
};
}
