/// <summary>
/// Name: System::Security::Cryptography::CspProviderFlags
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Cryptography {
class CspProviderFlags {
public:
    inline static _TypePtr _CspProviderFlags;
};
}
