/// <summary>
/// Name: System::Security::Cryptography::CspParameters
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Cryptography {
class CspParameters {
public:
    inline static _TypePtr _CspParameters;
};
}
