/// <summary>
/// Name: System::Security::Cryptography::DeriveBytes
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Cryptography {
class DeriveBytes {
public:
    inline static _TypePtr _DeriveBytes;
};
}
