/// <summary>
/// Name: System::Security::Cryptography::DES
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Cryptography {
class DES {
public:
    inline static _TypePtr _DES;
};
}
