/// <summary>
/// Name: System::Security::Cryptography::DESCryptoServiceProvider
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Cryptography {
class DESCryptoServiceProvider {
public:
    inline static _TypePtr _DESCryptoServiceProvider;
};
}
