/// <summary>
/// Name: System::Security::Cryptography::DSA
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Cryptography {
class DSA {
public:
    inline static _TypePtr _DSA;
};
}
