/// <summary>
/// Name: System::Security::Cryptography::DSACryptoServiceProvider
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Cryptography {
class DSACryptoServiceProvider {
public:
    inline static _TypePtr _DSACryptoServiceProvider;
};
}
