/// <summary>
/// Name: System::Security::Cryptography::DSAParameters
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Cryptography {
class DSAParameters {
public:
    inline static _TypePtr _DSAParameters;
};
}
