/// <summary>
/// Name: System::Security::Cryptography::DSASignatureDeformatter
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Cryptography {
class DSASignatureDeformatter {
public:
    inline static _TypePtr _DSASignatureDeformatter;
};
}
