/// <summary>
/// Name: System::Security::Cryptography::DSASignatureFormatter
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Cryptography {
class DSASignatureFormatter {
public:
    inline static _TypePtr _DSASignatureFormatter;
};
}
