/// <summary>
/// Name: System::Security::Cryptography::FromBase64Transform
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Cryptography {
class FromBase64Transform {
public:
    inline static _TypePtr _FromBase64Transform;
};
}
