/// <summary>
/// Name: System::Security::Cryptography::FromBase64TransformMode
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Cryptography {
class FromBase64TransformMode {
public:
    inline static _TypePtr _FromBase64TransformMode;
};
}
