/// <summary>
/// Name: System::Security::Cryptography::HashAlgorithm
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Cryptography {
class HashAlgorithm {
public:
    inline static _TypePtr _HashAlgorithm;
};
}
