/// <summary>
/// Name: System::Security::Cryptography::HMACSHA384
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Cryptography {
class HMACSHA384 {
public:
    inline static _TypePtr _HMACSHA384;
};
}
