/// <summary>
/// Name: System::Security::Cryptography::HMAC
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Cryptography {
class HMAC {
public:
    inline static _TypePtr _HMAC;
};
}
