/// <summary>
/// Name: System::Security::Cryptography::HMACSHA256
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Cryptography {
class HMACSHA256 {
public:
    inline static _TypePtr _HMACSHA256;
};
}
