/// <summary>
/// Name: System::Security::Cryptography::HMACSHA512
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Cryptography {
class HMACSHA512 {
public:
    inline static _TypePtr _HMACSHA512;
};
}
