/// <summary>
/// Name: System::Security::Cryptography::HMACMD5
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Cryptography {
class HMACMD5 {
public:
    inline static _TypePtr _HMACMD5;
};
}
