/// <summary>
/// Name: System::Security::Cryptography::HMACRIPEMD160
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Cryptography {
class HMACRIPEMD160 {
public:
    inline static _TypePtr _HMACRIPEMD160;
};
}
