/// <summary>
/// Name: System::Security::Cryptography::ICryptoTransform
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Cryptography {
class ICryptoTransform {
public:
    inline static _TypePtr _ICryptoTransform;
};
}
