/// <summary>
/// Name: System::Security::Cryptography::ICspAsymmetricAlgorithm
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Cryptography {
class ICspAsymmetricAlgorithm {
public:
    inline static _TypePtr _ICspAsymmetricAlgorithm;
};
}
