/// <summary>
/// Name: System::Security::Cryptography::KeyedHashAlgorithm
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Cryptography {
class KeyedHashAlgorithm {
public:
    inline static _TypePtr _KeyedHashAlgorithm;
};
}
