/// <summary>
/// Name: System::Security::Cryptography::KeyNumber
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Cryptography {
class KeyNumber {
public:
    inline static _TypePtr _KeyNumber;
};
}
