/// <summary>
/// Name: System::Security::Cryptography::KeySizes
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Cryptography {
class KeySizes {
public:
    inline static _TypePtr _KeySizes;
};
}
