/// <summary>
/// Name: System::Security::Cryptography::MACTripleDES
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Cryptography {
class MACTripleDES {
public:
    inline static _TypePtr _MACTripleDES;
};
}
