/// <summary>
/// Name: System::Security::Cryptography::MaskGenerationMethod
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Cryptography {
class MaskGenerationMethod {
public:
    inline static _TypePtr _MaskGenerationMethod;
};
}
