/// <summary>
/// Name: System::Security::Cryptography::MD5CryptoServiceProvider
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Cryptography {
class MD5CryptoServiceProvider {
public:
    inline static _TypePtr _MD5CryptoServiceProvider;
};
}
