/// <summary>
/// Name: System::Security::Cryptography::PaddingMode
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Cryptography {
class PaddingMode {
public:
    inline static _TypePtr _PaddingMode;
};
}
