/// <summary>
/// Name: System::Security::Cryptography::PasswordDeriveBytes
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Cryptography {
class PasswordDeriveBytes {
public:
    inline static _TypePtr _PasswordDeriveBytes;
};
}
