/// <summary>
/// Name: System::Security::Cryptography::PKCS1MaskGenerationMethod
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Cryptography {
class PKCS1MaskGenerationMethod {
public:
    inline static _TypePtr _PKCS1MaskGenerationMethod;
};
}
