/// <summary>
/// Name: System::Security::Cryptography::RandomNumberGenerator
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Cryptography {
class RandomNumberGenerator {
public:
    inline static _TypePtr _RandomNumberGenerator;
};
}
