/// <summary>
/// Name: System::Security::Cryptography::RC2
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Cryptography {
class RC2 {
public:
    inline static _TypePtr _RC2;
};
}
