/// <summary>
/// Name: System::Security::Cryptography::RC2CryptoServiceProvider
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Cryptography {
class RC2CryptoServiceProvider {
public:
    inline static _TypePtr _RC2CryptoServiceProvider;
};
}
