/// <summary>
/// Name: System::Security::Cryptography::Rfc2898DeriveBytes
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Cryptography {
class Rfc2898DeriveBytes {
public:
    inline static _TypePtr _Rfc2898DeriveBytes;
};
}
