/// <summary>
/// Name: System::Security::Cryptography::RijndaelManagedTransform
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Cryptography {
class RijndaelManagedTransform {
public:
    inline static _TypePtr _RijndaelManagedTransform;
};
}
