/// <summary>
/// Name: System::Security::Cryptography::Rijndael
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Cryptography {
class Rijndael {
public:
    inline static _TypePtr _Rijndael;
};
}
