/// <summary>
/// Name: System::Security::Cryptography::RijndaelManaged
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Cryptography {
class RijndaelManaged {
public:
    inline static _TypePtr _RijndaelManaged;
};
}
