/// <summary>
/// Name: System::Security::Cryptography::RIPEMD160Managed
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Cryptography {
class RIPEMD160Managed {
public:
    inline static _TypePtr _RIPEMD160Managed;
};
}
