/// <summary>
/// Name: System::Security::Cryptography::RIPEMD160
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Cryptography {
class RIPEMD160 {
public:
    inline static _TypePtr _RIPEMD160;
};
}
