/// <summary>
/// Name: System::Security::Cryptography::RNGCryptoServiceProvider
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Cryptography {
class RNGCryptoServiceProvider {
public:
    inline static _TypePtr _RNGCryptoServiceProvider;
};
}
