/// <summary>
/// Name: System::Security::Cryptography::RSA
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Cryptography {
class RSA {
public:
    inline static _TypePtr _RSA;
};
}
