/// <summary>
/// Name: System::Security::Cryptography::RSAOAEPKeyExchangeFormatter
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Cryptography {
class RSAOAEPKeyExchangeFormatter {
public:
    inline static _TypePtr _RSAOAEPKeyExchangeFormatter;
};
}
