/// <summary>
/// Name: System::Security::Cryptography::RSAOAEPKeyExchangeDeformatter
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Cryptography {
class RSAOAEPKeyExchangeDeformatter {
public:
    inline static _TypePtr _RSAOAEPKeyExchangeDeformatter;
};
}
