/// <summary>
/// Name: System::Security::Cryptography::RSAParameters
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Cryptography {
class RSAParameters {
public:
    inline static _TypePtr _RSAParameters;
};
}
