/// <summary>
/// Name: System::Security::Cryptography::RSAPKCS1SignatureDeformatter
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Cryptography {
class RSAPKCS1SignatureDeformatter {
public:
    inline static _TypePtr _RSAPKCS1SignatureDeformatter;
};
}
