/// <summary>
/// Name: System::Security::Cryptography::RSAPKCS1SignatureFormatter
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Cryptography {
class RSAPKCS1SignatureFormatter {
public:
    inline static _TypePtr _RSAPKCS1SignatureFormatter;
};
}
