/// <summary>
/// Name: System::Security::Cryptography::RSAPKCS1KeyExchangeDeformatter
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Cryptography {
class RSAPKCS1KeyExchangeDeformatter {
public:
    inline static _TypePtr _RSAPKCS1KeyExchangeDeformatter;
};
}
