/// <summary>
/// Name: System::Security::Cryptography::SHA1CryptoServiceProvider
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Cryptography {
class SHA1CryptoServiceProvider {
public:
    inline static _TypePtr _SHA1CryptoServiceProvider;
};
}
