/// <summary>
/// Name: System::Security::Cryptography::SHA1
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Cryptography {
class SHA1 {
public:
    inline static _TypePtr _SHA1;
};
}
