/// <summary>
/// Name: System::Security::Cryptography::SHA1Managed
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Cryptography {
class SHA1Managed {
public:
    inline static _TypePtr _SHA1Managed;
};
}
