/// <summary>
/// Name: System::Security::Cryptography::SHA256Managed
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Cryptography {
class SHA256Managed {
public:
    inline static _TypePtr _SHA256Managed;
};
}
