/// <summary>
/// Name: System::Security::Cryptography::SHA384
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Cryptography {
class SHA384 {
public:
    inline static _TypePtr _SHA384;
};
}
