/// <summary>
/// Name: System::Security::Cryptography::SHA384Managed
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Cryptography {
class SHA384Managed {
public:
    inline static _TypePtr _SHA384Managed;
};
}
