/// <summary>
/// Name: System::Security::Cryptography::SHA512Managed
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Cryptography {
class SHA512Managed {
public:
    inline static _TypePtr _SHA512Managed;
};
}
