/// <summary>
/// Name: System::Security::Cryptography::SHA512
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Cryptography {
class SHA512 {
public:
    inline static _TypePtr _SHA512;
};
}
