/// <summary>
/// Name: System::Security::Cryptography::SignatureDescription
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Cryptography {
class SignatureDescription {
public:
    inline static _TypePtr _SignatureDescription;
};
}
