/// <summary>
/// Name: System::Security::Cryptography::SymmetricAlgorithm
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Cryptography {
class SymmetricAlgorithm {
public:
    inline static _TypePtr _SymmetricAlgorithm;
};
}
