/// <summary>
/// Name: System::Security::Cryptography::ToBase64Transform
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Cryptography {
class ToBase64Transform {
public:
    inline static _TypePtr _ToBase64Transform;
};
}
