/// <summary>
/// Name: System::Security::Cryptography::TripleDESCryptoServiceProvider
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Cryptography {
class TripleDESCryptoServiceProvider {
public:
    inline static _TypePtr _TripleDESCryptoServiceProvider;
};
}
