/// <summary>
/// Name: System::Security::Cryptography::TripleDES
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Cryptography {
class TripleDES {
public:
    inline static _TypePtr _TripleDES;
};
}
