/// <summary>
/// Name: System::Runtime::Serialization::Formatters::FormatterTypeStyle
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Serialization::Formatters {
class FormatterTypeStyle {
public:
    inline static _TypePtr _FormatterTypeStyle;
};
}
