/// <summary>
/// Name: System::Runtime::Serialization::Formatters::FormatterAssemblyStyle
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Serialization::Formatters {
class FormatterAssemblyStyle {
public:
    inline static _TypePtr _FormatterAssemblyStyle;
};
}
