/// <summary>
/// Name: System::Runtime::Serialization::Formatters::IFieldInfo
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Serialization::Formatters {
class IFieldInfo {
public:
    inline static _TypePtr _IFieldInfo;
};
}
