/// <summary>
/// Name: System::Runtime::Serialization::Formatters::InternalRM
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Serialization::Formatters {
class InternalRM {
public:
    inline static _TypePtr _InternalRM;
};
}
