/// <summary>
/// Name: System::Runtime::Serialization::Formatters::InternalST
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Serialization::Formatters {
class InternalST {
public:
    inline static _TypePtr _InternalST;
};
}
