/// <summary>
/// Name: System::Runtime::Serialization::Formatters::ISoapMessage
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Serialization::Formatters {
class ISoapMessage {
public:
    inline static _TypePtr _ISoapMessage;
};
}
