/// <summary>
/// Name: System::Runtime::Serialization::Formatters::ServerFault
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Serialization::Formatters {
class ServerFault {
public:
    inline static _TypePtr _ServerFault;
};
}
