/// <summary>
/// Name: System::Runtime::Serialization::Formatters::SoapFault
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Serialization::Formatters {
class SoapFault {
public:
    inline static _TypePtr _SoapFault;
};
}
