/// <summary>
/// Name: System::Runtime::Serialization::Formatters::SoapMessage
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Serialization::Formatters {
class SoapMessage {
public:
    inline static _TypePtr _SoapMessage;
};
}
