/// <summary>
/// Name: System::Runtime::Serialization::Formatters::TypeFilterLevel
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Serialization::Formatters {
class TypeFilterLevel {
public:
    inline static _TypePtr _TypeFilterLevel;
};
}
