/// <summary>
/// Name: System::Diagnostics::SymbolStore::ISymbolReader
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Diagnostics::SymbolStore {
class ISymbolReader {
public:
    inline static _TypePtr _ISymbolReader;
};
}
