/// <summary>
/// Name: System::Diagnostics::SymbolStore::ISymbolDocument
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Diagnostics::SymbolStore {
class ISymbolDocument {
public:
    inline static _TypePtr _ISymbolDocument;
};
}
