/// <summary>
/// Name: System::Diagnostics::SymbolStore::ISymbolBinder
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Diagnostics::SymbolStore {
class ISymbolBinder {
public:
    inline static _TypePtr _ISymbolBinder;
};
}
