/// <summary>
/// Name: System::Diagnostics::SymbolStore::ISymbolNamespace
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Diagnostics::SymbolStore {
class ISymbolNamespace {
public:
    inline static _TypePtr _ISymbolNamespace;
};
}
