/// <summary>
/// Name: System::Diagnostics::SymbolStore::ISymbolBinder1
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Diagnostics::SymbolStore {
class ISymbolBinder1 {
public:
    inline static _TypePtr _ISymbolBinder1;
};
}
