/// <summary>
/// Name: System::Diagnostics::SymbolStore::ISymbolDocumentWriter
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Diagnostics::SymbolStore {
class ISymbolDocumentWriter {
public:
    inline static _TypePtr _ISymbolDocumentWriter;
};
}
