/// <summary>
/// Name: System::Diagnostics::SymbolStore::ISymbolWriter
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Diagnostics::SymbolStore {
class ISymbolWriter {
public:
    inline static _TypePtr _ISymbolWriter;
};
}
