/// <summary>
/// Name: System::Diagnostics::SymbolStore::ISymbolVariable
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Diagnostics::SymbolStore {
class ISymbolVariable {
public:
    inline static _TypePtr _ISymbolVariable;
};
}
