/// <summary>
/// Name: System::Diagnostics::SymbolStore::ISymbolMethod
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Diagnostics::SymbolStore {
class ISymbolMethod {
public:
    inline static _TypePtr _ISymbolMethod;
};
}
