/// <summary>
/// Name: System::Diagnostics::SymbolStore::ISymbolScope
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Diagnostics::SymbolStore {
class ISymbolScope {
public:
    inline static _TypePtr _ISymbolScope;
};
}
