/// <summary>
/// Name: System::Diagnostics::SymbolStore::SymAddressKind
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Diagnostics::SymbolStore {
class SymAddressKind {
public:
    inline static _TypePtr _SymAddressKind;
};
}
