/// <summary>
/// Name: System::Diagnostics::SymbolStore::SymbolToken
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Diagnostics::SymbolStore {
class SymbolToken {
public:
    inline static _TypePtr _SymbolToken;
};
}
