/// <summary>
/// Name: System::Diagnostics::SymbolStore::SymDocumentType
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Diagnostics::SymbolStore {
class SymDocumentType {
public:
    inline static _TypePtr _SymDocumentType;
};
}
