/// <summary>
/// Name: System::Diagnostics::SymbolStore::SymLanguageType
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Diagnostics::SymbolStore {
class SymLanguageType {
public:
    inline static _TypePtr _SymLanguageType;
};
}
