/// <summary>
/// Name: System::Diagnostics::SymbolStore::SymLanguageVendor
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Diagnostics::SymbolStore {
class SymLanguageVendor {
public:
    inline static _TypePtr _SymLanguageVendor;
};
}
