/// <summary>
/// Name: System::Collections::ArrayList
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Collections {
class ArrayList {
public:
    inline static _TypePtr _ArrayList;
};
}
