/// <summary>
/// Name: System::Collections::BitArray
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Collections {
class BitArray {
public:
    inline static _TypePtr _BitArray;
};
}
