/// <summary>
/// Name: System::Collections::CaseInsensitiveHashCodeProvider
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Collections {
class CaseInsensitiveHashCodeProvider {
public:
    inline static _TypePtr _CaseInsensitiveHashCodeProvider;
};
}
