/// <summary>
/// Name: System::Collections::CaseInsensitiveComparer
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Collections {
class CaseInsensitiveComparer {
public:
    inline static _TypePtr _CaseInsensitiveComparer;
};
}
