/// <summary>
/// Name: System::Collections::CollectionBase
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Collections {
class CollectionBase {
public:
    inline static _TypePtr _CollectionBase;
};
}
