/// <summary>
/// Name: System::Collections::Comparer
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Collections {
class Comparer {
public:
    inline static _TypePtr _Comparer;
};
}
