/// <summary>
/// Name: System::Collections::DictionaryBase
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Collections {
class DictionaryBase {
public:
    inline static _TypePtr _DictionaryBase;
};
}
