/// <summary>
/// Name: System::Collections::DictionaryEntry
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Collections {
class DictionaryEntry {
public:
    inline static _TypePtr _DictionaryEntry;
};
}
