/// <summary>
/// Name: System::Collections::Hashtable
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Collections {
class Hashtable {
public:
    inline static _TypePtr _Hashtable;
};
}
