/// <summary>
/// Name: System::Collections::ICollection
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Collections {
class ICollection {
public:
    inline static _TypePtr _ICollection;
};
}
