/// <summary>
/// Name: System::Collections::IComparer
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Collections {
class IComparer {
public:
    inline static _TypePtr _IComparer;
};
}
