/// <summary>
/// Name: System::Collections::IDictionary
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Collections {
class IDictionary {
public:
    inline static _TypePtr _IDictionary;
};
}
