/// <summary>
/// Name: System::Collections::IDictionaryEnumerator
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Collections {
class IDictionaryEnumerator {
public:
    inline static _TypePtr _IDictionaryEnumerator;
};
}
