/// <summary>
/// Name: System::Collections::IEnumerable
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Collections {
class IEnumerable {
public:
    inline static _TypePtr _IEnumerable;
};
}
