/// <summary>
/// Name: System::Collections::IEnumerator
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Collections {
class IEnumerator {
public:
    inline static _TypePtr _IEnumerator;
};
}
