/// <summary>
/// Name: System::Collections::IEqualityComparer
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Collections {
class IEqualityComparer {
public:
    inline static _TypePtr _IEqualityComparer;
};
}
