/// <summary>
/// Name: System::Collections::IHashCodeProvider
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Collections {
class IHashCodeProvider {
public:
    inline static _TypePtr _IHashCodeProvider;
};
}
