/// <summary>
/// Name: System::Collections::IList
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Collections {
class IList {
public:
    inline static _TypePtr _IList;
};
}
