/// <summary>
/// Name: System::Collections::Queue
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Collections {
class Queue {
public:
    inline static _TypePtr _Queue;
};
}
