/// <summary>
/// Name: System::Collections::ReadOnlyCollectionBase
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Collections {
class ReadOnlyCollectionBase {
public:
    inline static _TypePtr _ReadOnlyCollectionBase;
};
}
