/// <summary>
/// Name: System::Collections::SortedList
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Collections {
class SortedList {
public:
    inline static _TypePtr _SortedList;
};
}
