/// <summary>
/// Name: System::Collections::Stack
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Collections {
class Stack {
public:
    inline static _TypePtr _Stack;
};
}
