/// <summary>
/// Name: System::Runtime::Remoting::Messaging::AsyncResult
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Messaging {
class AsyncResult {
public:
    inline static _TypePtr _AsyncResult;
};
}
