/// <summary>
/// Name: System::Runtime::Remoting::Messaging::CallContext
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Messaging {
class CallContext {
public:
    inline static _TypePtr _CallContext;
};
}
