/// <summary>
/// Name: System::Runtime::Remoting::Messaging::ConstructionResponse
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Messaging {
class ConstructionResponse {
public:
    inline static _TypePtr _ConstructionResponse;
};
}
