/// <summary>
/// Name: System::Runtime::Remoting::Messaging::HeaderHandler
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Messaging {
class HeaderHandler {
public:
    inline static _TypePtr _HeaderHandler;
};
}
