/// <summary>
/// Name: System::Runtime::Remoting::Messaging::Header
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Messaging {
class Header {
public:
    inline static _TypePtr _Header;
};
}
