/// <summary>
/// Name: System::Runtime::Remoting::Messaging::ILogicalThreadAffinative
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Messaging {
class ILogicalThreadAffinative {
public:
    inline static _TypePtr _ILogicalThreadAffinative;
};
}
