/// <summary>
/// Name: System::Runtime::Remoting::Messaging::IMessageCtrl
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Messaging {
class IMessageCtrl {
public:
    inline static _TypePtr _IMessageCtrl;
};
}
