/// <summary>
/// Name: System::Runtime::Remoting::Messaging::IMessageSink
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Messaging {
class IMessageSink {
public:
    inline static _TypePtr _IMessageSink;
};
}
