/// <summary>
/// Name: System::Runtime::Remoting::Messaging::IMessage
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Messaging {
class IMessage {
public:
    inline static _TypePtr _IMessage;
};
}
