/// <summary>
/// Name: System::Runtime::Remoting::Messaging::IMethodCallMessage
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Messaging {
class IMethodCallMessage {
public:
    inline static _TypePtr _IMethodCallMessage;
};
}
