/// <summary>
/// Name: System::Runtime::Remoting::Messaging::IMethodMessage
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Messaging {
class IMethodMessage {
public:
    inline static _TypePtr _IMethodMessage;
};
}
