/// <summary>
/// Name: System::Runtime::Remoting::Messaging::IMethodReturnMessage
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Messaging {
class IMethodReturnMessage {
public:
    inline static _TypePtr _IMethodReturnMessage;
};
}
