/// <summary>
/// Name: System::Runtime::Remoting::Messaging::InternalMessageWrapper
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Messaging {
class InternalMessageWrapper {
public:
    inline static _TypePtr _InternalMessageWrapper;
};
}
