/// <summary>
/// Name: System::Runtime::Remoting::Messaging::IRemotingFormatter
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Messaging {
class IRemotingFormatter {
public:
    inline static _TypePtr _IRemotingFormatter;
};
}
