/// <summary>
/// Name: System::Runtime::Remoting::Messaging::LogicalCallContext
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Messaging {
class LogicalCallContext {
public:
    inline static _TypePtr _LogicalCallContext;
};
}
