/// <summary>
/// Name: System::Runtime::Remoting::Messaging::MessageSurrogateFilter
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Messaging {
class MessageSurrogateFilter {
public:
    inline static _TypePtr _MessageSurrogateFilter;
};
}
