/// <summary>
/// Name: System::Runtime::Remoting::Messaging::MethodCall
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Messaging {
class MethodCall {
public:
    inline static _TypePtr _MethodCall;
};
}
