/// <summary>
/// Name: System::Runtime::Remoting::Messaging::MethodCallMessageWrapper
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Messaging {
class MethodCallMessageWrapper {
public:
    inline static _TypePtr _MethodCallMessageWrapper;
};
}
