/// <summary>
/// Name: System::Runtime::Remoting::Messaging::MethodResponse
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Messaging {
class MethodResponse {
public:
    inline static _TypePtr _MethodResponse;
};
}
