/// <summary>
/// Name: System::Runtime::Remoting::Messaging::OneWayAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Messaging {
class OneWayAttribute {
public:
    inline static _TypePtr _OneWayAttribute;
};
}
