/// <summary>
/// Name: System::Runtime::Remoting::Messaging::RemotingSurrogateSelector
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Messaging {
class RemotingSurrogateSelector {
public:
    inline static _TypePtr _RemotingSurrogateSelector;
};
}
