/// <summary>
/// Name: System::Runtime::Remoting::Messaging::ReturnMessage
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Messaging {
class ReturnMessage {
public:
    inline static _TypePtr _ReturnMessage;
};
}
