/// <summary>
/// Name: System::Text::ASCIIEncoding
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Text {
class ASCIIEncoding {
public:
    inline static _TypePtr _ASCIIEncoding;
};
}
