/// <summary>
/// Name: System::Text::DecoderFallback
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Text {
class DecoderFallback {
public:
    inline static _TypePtr _DecoderFallback;
};
}
