/// <summary>
/// Name: System::Text::Decoder
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Text {
class Decoder {
public:
    inline static _TypePtr _Decoder;
};
}
