/// <summary>
/// Name: System::Text::DecoderReplacementFallback
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Text {
class DecoderReplacementFallback {
public:
    inline static _TypePtr _DecoderReplacementFallback;
};
}
