/// <summary>
/// Name: System::Text::DecoderReplacementFallbackBuffer
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Text {
class DecoderReplacementFallbackBuffer {
public:
    inline static _TypePtr _DecoderReplacementFallbackBuffer;
};
}
