/// <summary>
/// Name: System::Text::DecoderFallbackBuffer
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Text {
class DecoderFallbackBuffer {
public:
    inline static _TypePtr _DecoderFallbackBuffer;
};
}
