/// <summary>
/// Name: System::Text::DecoderFallbackException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Text {
class DecoderFallbackException {
public:
    inline static _TypePtr _DecoderFallbackException;
};
}
