/// <summary>
/// Name: System::Text::DecoderExceptionFallback
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Text {
class DecoderExceptionFallback {
public:
    inline static _TypePtr _DecoderExceptionFallback;
};
}
