/// <summary>
/// Name: System::Text::DecoderExceptionFallbackBuffer
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Text {
class DecoderExceptionFallbackBuffer {
public:
    inline static _TypePtr _DecoderExceptionFallbackBuffer;
};
}
