/// <summary>
/// Name: System::Text::EncoderReplacementFallback
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Text {
class EncoderReplacementFallback {
public:
    inline static _TypePtr _EncoderReplacementFallback;
};
}
