/// <summary>
/// Name: System::Text::EncoderFallbackBuffer
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Text {
class EncoderFallbackBuffer {
public:
    inline static _TypePtr _EncoderFallbackBuffer;
};
}
