/// <summary>
/// Name: System::Text::EncoderExceptionFallback
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Text {
class EncoderExceptionFallback {
public:
    inline static _TypePtr _EncoderExceptionFallback;
};
}
