/// <summary>
/// Name: System::Text::EncoderExceptionFallbackBuffer
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Text {
class EncoderExceptionFallbackBuffer {
public:
    inline static _TypePtr _EncoderExceptionFallbackBuffer;
};
}
