/// <summary>
/// Name: System::Text::EncoderReplacementFallbackBuffer
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Text {
class EncoderReplacementFallbackBuffer {
public:
    inline static _TypePtr _EncoderReplacementFallbackBuffer;
};
}
