/// <summary>
/// Name: System::Text::EncoderFallbackException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Text {
class EncoderFallbackException {
public:
    inline static _TypePtr _EncoderFallbackException;
};
}
