/// <summary>
/// Name: System::Text::Encoding
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Text {
class Encoding {
public:
    inline static _TypePtr _Encoding;
};
}
