/// <summary>
/// Name: System::Text::EncoderFallback
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Text {
class EncoderFallback {
public:
    inline static _TypePtr _EncoderFallback;
};
}
