/// <summary>
/// Name: System::Text::Encoder
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Text {
class Encoder {
public:
    inline static _TypePtr _Encoder;
};
}
