/// <summary>
/// Name: System::Text::EncodingInfo
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Text {
class EncodingInfo {
public:
    inline static _TypePtr _EncodingInfo;
};
}
