/// <summary>
/// Name: System::Text::NormalizationForm
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Text {
class NormalizationForm {
public:
    inline static _TypePtr _NormalizationForm;
};
}
