/// <summary>
/// Name: System::Text::StringBuilder
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Text {
class StringBuilder {
public:
    inline static _TypePtr _StringBuilder;
};
}
