/// <summary>
/// Name: System::Text::UnicodeEncoding
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Text {
class UnicodeEncoding {
public:
    inline static _TypePtr _UnicodeEncoding;
};
}
