/// <summary>
/// Name: System::Text::UTF32Encoding
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Text {
class UTF32Encoding {
public:
    inline static _TypePtr _UTF32Encoding;
};
}
