/// <summary>
/// Name: System::Text::UTF7Encoding
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Text {
class UTF7Encoding {
public:
    inline static _TypePtr _UTF7Encoding;
};
}
