/// <summary>
/// Name: System::Runtime::Remoting::Activation::ActivatorLevel
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Activation {
class ActivatorLevel {
public:
    inline static _TypePtr _ActivatorLevel;
};
}
