/// <summary>
/// Name: System::Runtime::Remoting::Activation::IActivator
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Activation {
class IActivator {
public:
    inline static _TypePtr _IActivator;
};
}
