/// <summary>
/// Name: System::Runtime::Remoting::Activation::IConstructionCallMessage
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Activation {
class IConstructionCallMessage {
public:
    inline static _TypePtr _IConstructionCallMessage;
};
}
