/// <summary>
/// Name: System::Runtime::Remoting::Activation::IConstructionReturnMessage
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Activation {
class IConstructionReturnMessage {
public:
    inline static _TypePtr _IConstructionReturnMessage;
};
}
