/// <summary>
/// Name: System::Runtime::Remoting::Activation::UrlAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Activation {
class UrlAttribute {
public:
    inline static _TypePtr _UrlAttribute;
};
}
