/// <summary>
/// Name: System::Runtime::Remoting::Services::EnterpriseServicesHelper
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Services {
class EnterpriseServicesHelper {
public:
    inline static _TypePtr _EnterpriseServicesHelper;
};
}
