/// <summary>
/// Name: System::Runtime::Remoting::Services::ITrackingHandler
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Services {
class ITrackingHandler {
public:
    inline static _TypePtr _ITrackingHandler;
};
}
