/// <summary>
/// Name: System::Runtime::Remoting::Services::TrackingServices
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Services {
class TrackingServices {
public:
    inline static _TypePtr _TrackingServices;
};
}
