/// <summary>
/// Name: System::IO::BinaryWriter
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::IO {
class BinaryWriter {
public:
    inline static _TypePtr _BinaryWriter;
};
}
