/// <summary>
/// Name: System::IO::BinaryReader
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::IO {
class BinaryReader {
public:
    inline static _TypePtr _BinaryReader;
};
}
