/// <summary>
/// Name: System::IO::BufferedStream
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::IO {
class BufferedStream {
public:
    inline static _TypePtr _BufferedStream;
};
}
