/// <summary>
/// Name: System::IO::DirectoryNotFoundException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::IO {
class DirectoryNotFoundException {
public:
    inline static _TypePtr _DirectoryNotFoundException;
};
}
