/// <summary>
/// Name: System::IO::Directory
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::IO {
class Directory {
public:
    inline static _TypePtr _Directory;
};
}
