/// <summary>
/// Name: System::IO::DirectoryInfo
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::IO {
class DirectoryInfo {
public:
    inline static _TypePtr _DirectoryInfo;
};
}
