/// <summary>
/// Name: System::IO::DriveType
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::IO {
class DriveType {
public:
    inline static _TypePtr _DriveType;
};
}
