/// <summary>
/// Name: System::IO::DriveNotFoundException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::IO {
class DriveNotFoundException {
public:
    inline static _TypePtr _DriveNotFoundException;
};
}
