/// <summary>
/// Name: System::IO::DriveInfo
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::IO {
class DriveInfo {
public:
    inline static _TypePtr _DriveInfo;
};
}
