/// <summary>
/// Name: System::IO::FileSystemInfo
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::IO {
class FileSystemInfo {
public:
    inline static _TypePtr _FileSystemInfo;
};
}
