/// <summary>
/// Name: System::IO::FileMode
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::IO {
class FileMode {
public:
    inline static _TypePtr _FileMode;
};
}
