/// <summary>
/// Name: System::IO::FileOptions
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::IO {
class FileOptions {
public:
    inline static _TypePtr _FileOptions;
};
}
