/// <summary>
/// Name: System::IO::FileNotFoundException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::IO {
class FileNotFoundException {
public:
    inline static _TypePtr _FileNotFoundException;
};
}
