/// <summary>
/// Name: System::IO::FileInfo
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::IO {
class FileInfo {
public:
    inline static _TypePtr _FileInfo;
};
}
