/// <summary>
/// Name: System::IO::FileLoadException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::IO {
class FileLoadException {
public:
    inline static _TypePtr _FileLoadException;
};
}
