/// <summary>
/// Name: System::IO::File
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::IO {
class File {
public:
    inline static _TypePtr _File;
};
}
