/// <summary>
/// Name: System::IO::FileAccess
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::IO {
class FileAccess {
public:
    inline static _TypePtr _FileAccess;
};
}
