/// <summary>
/// Name: System::IO::FileAttributes
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::IO {
class FileAttributes {
public:
    inline static _TypePtr _FileAttributes;
};
}
