/// <summary>
/// Name: System::IO::FileStream
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::IO {
class FileStream {
public:
    inline static _TypePtr _FileStream;
};
}
