/// <summary>
/// Name: System::IO::FileShare
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::IO {
class FileShare {
public:
    inline static _TypePtr _FileShare;
};
}
