/// <summary>
/// Name: System::IO::IOException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::IO {
class IOException {
public:
    inline static _TypePtr _IOException;
};
}
