/// <summary>
/// Name: System::IO::MemoryStream
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::IO {
class MemoryStream {
public:
    inline static _TypePtr _MemoryStream;
};
}
