/// <summary>
/// Name: System::IO::PathTooLongException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::IO {
class PathTooLongException {
public:
    inline static _TypePtr _PathTooLongException;
};
}
