/// <summary>
/// Name: System::IO::Path
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::IO {
class Path {
public:
    inline static _TypePtr _Path;
};
}
