/// <summary>
/// Name: System::IO::SearchOption
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::IO {
class SearchOption {
public:
    inline static _TypePtr _SearchOption;
};
}
