/// <summary>
/// Name: System::IO::SeekOrigin
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::IO {
class SeekOrigin {
public:
    inline static _TypePtr _SeekOrigin;
};
}
