/// <summary>
/// Name: System::IO::StreamReader
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::IO {
class StreamReader {
public:
    inline static _TypePtr _StreamReader;
};
}
