/// <summary>
/// Name: System::IO::Stream
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::IO {
class Stream {
public:
    inline static _TypePtr _Stream;
};
}
