/// <summary>
/// Name: System::IO::StreamWriter
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::IO {
class StreamWriter {
public:
    inline static _TypePtr _StreamWriter;
};
}
