/// <summary>
/// Name: System::IO::StringWriter
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::IO {
class StringWriter {
public:
    inline static _TypePtr _StringWriter;
};
}
