/// <summary>
/// Name: System::IO::StringReader
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::IO {
class StringReader {
public:
    inline static _TypePtr _StringReader;
};
}
