/// <summary>
/// Name: System::IO::TextWriter
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::IO {
class TextWriter {
public:
    inline static _TypePtr _TextWriter;
};
}
