/// <summary>
/// Name: System::IO::TextReader
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::IO {
class TextReader {
public:
    inline static _TypePtr _TextReader;
};
}
