/// <summary>
/// Name: System::IO::UnmanagedMemoryStream
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::IO {
class UnmanagedMemoryStream {
public:
    inline static _TypePtr _UnmanagedMemoryStream;
};
}
