/// <summary>
/// Name: System::Runtime::Remoting::Channels::BaseChannelObjectWithProperties
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Channels {
class BaseChannelObjectWithProperties {
public:
    inline static _TypePtr _BaseChannelObjectWithProperties;
};
}
