/// <summary>
/// Name: System::Runtime::Remoting::Channels::BaseChannelSinkWithProperties
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Channels {
class BaseChannelSinkWithProperties {
public:
    inline static _TypePtr _BaseChannelSinkWithProperties;
};
}
