/// <summary>
/// Name: System::Runtime::Remoting::Channels::BaseChannelWithProperties
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Channels {
class BaseChannelWithProperties {
public:
    inline static _TypePtr _BaseChannelWithProperties;
};
}
