/// <summary>
/// Name: System::Runtime::Remoting::Channels::ChannelServices
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Channels {
class ChannelServices {
public:
    inline static _TypePtr _ChannelServices;
};
}
