/// <summary>
/// Name: System::Runtime::Remoting::Channels::ChannelDataStore
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Channels {
class ChannelDataStore {
public:
    inline static _TypePtr _ChannelDataStore;
};
}
