/// <summary>
/// Name: System::Runtime::Remoting::Channels::ClientChannelSinkStack
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Channels {
class ClientChannelSinkStack {
public:
    inline static _TypePtr _ClientChannelSinkStack;
};
}
