/// <summary>
/// Name: System::Runtime::Remoting::Channels::IChannelSinkBase
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Channels {
class IChannelSinkBase {
public:
    inline static _TypePtr _IChannelSinkBase;
};
}
