/// <summary>
/// Name: System::Runtime::Remoting::Channels::IChannelDataStore
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Channels {
class IChannelDataStore {
public:
    inline static _TypePtr _IChannelDataStore;
};
}
