/// <summary>
/// Name: System::Runtime::Remoting::Channels::IChannel
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Channels {
class IChannel {
public:
    inline static _TypePtr _IChannel;
};
}
