/// <summary>
/// Name: System::Runtime::Remoting::Channels::IChannelReceiverHook
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Channels {
class IChannelReceiverHook {
public:
    inline static _TypePtr _IChannelReceiverHook;
};
}
