/// <summary>
/// Name: System::Runtime::Remoting::Channels::IChannelReceiver
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Channels {
class IChannelReceiver {
public:
    inline static _TypePtr _IChannelReceiver;
};
}
