/// <summary>
/// Name: System::Runtime::Remoting::Channels::IChannelSender
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Channels {
class IChannelSender {
public:
    inline static _TypePtr _IChannelSender;
};
}
