/// <summary>
/// Name: System::Runtime::Remoting::Channels::IClientResponseChannelSinkStack
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Channels {
class IClientResponseChannelSinkStack {
public:
    inline static _TypePtr _IClientResponseChannelSinkStack;
};
}
