/// <summary>
/// Name: System::Runtime::Remoting::Channels::IClientFormatterSinkProvider
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Channels {
class IClientFormatterSinkProvider {
public:
    inline static _TypePtr _IClientFormatterSinkProvider;
};
}
