/// <summary>
/// Name: System::Runtime::Remoting::Channels::IClientFormatterSink
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Channels {
class IClientFormatterSink {
public:
    inline static _TypePtr _IClientFormatterSink;
};
}
