/// <summary>
/// Name: System::Runtime::Remoting::Channels::IClientChannelSinkProvider
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Channels {
class IClientChannelSinkProvider {
public:
    inline static _TypePtr _IClientChannelSinkProvider;
};
}
