/// <summary>
/// Name: System::Runtime::Remoting::Channels::IClientChannelSinkStack
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Channels {
class IClientChannelSinkStack {
public:
    inline static _TypePtr _IClientChannelSinkStack;
};
}
