/// <summary>
/// Name: System::Runtime::Remoting::Channels::IClientChannelSink
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Channels {
class IClientChannelSink {
public:
    inline static _TypePtr _IClientChannelSink;
};
}
