/// <summary>
/// Name: System::Runtime::Remoting::Channels::ISecurableChannel
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Channels {
class ISecurableChannel {
public:
    inline static _TypePtr _ISecurableChannel;
};
}
