/// <summary>
/// Name: System::Runtime::Remoting::Channels::IServerChannelSink
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Channels {
class IServerChannelSink {
public:
    inline static _TypePtr _IServerChannelSink;
};
}
