/// <summary>
/// Name: System::Runtime::Remoting::Channels::IServerChannelSinkStack
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Channels {
class IServerChannelSinkStack {
public:
    inline static _TypePtr _IServerChannelSinkStack;
};
}
