/// <summary>
/// Name: System::Runtime::Remoting::Channels::IServerResponseChannelSinkStack
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Channels {
class IServerResponseChannelSinkStack {
public:
    inline static _TypePtr _IServerResponseChannelSinkStack;
};
}
