/// <summary>
/// Name: System::Runtime::Remoting::Channels::IServerFormatterSinkProvider
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Channels {
class IServerFormatterSinkProvider {
public:
    inline static _TypePtr _IServerFormatterSinkProvider;
};
}
