/// <summary>
/// Name: System::Runtime::Remoting::Channels::IServerChannelSinkProvider
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Channels {
class IServerChannelSinkProvider {
public:
    inline static _TypePtr _IServerChannelSinkProvider;
};
}
