/// <summary>
/// Name: System::Runtime::Remoting::Channels::ITransportHeaders
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Channels {
class ITransportHeaders {
public:
    inline static _TypePtr _ITransportHeaders;
};
}
