/// <summary>
/// Name: System::Runtime::Remoting::Channels::ServerChannelSinkStack
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Channels {
class ServerChannelSinkStack {
public:
    inline static _TypePtr _ServerChannelSinkStack;
};
}
