/// <summary>
/// Name: System::Runtime::Remoting::Channels::SinkProviderData
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Channels {
class SinkProviderData {
public:
    inline static _TypePtr _SinkProviderData;
};
}
