/// <summary>
/// Name: System::Runtime::Remoting::Channels::TransportHeaders
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Channels {
class TransportHeaders {
public:
    inline static _TypePtr _TransportHeaders;
};
}
