/// <summary>
/// Name: System::Collections::Generic::KeyNotFoundException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Collections::Generic {
class KeyNotFoundException {
public:
    inline static _TypePtr _KeyNotFoundException;
};
}
