/// <summary>
/// Name: System::Resources::IResourceWriter
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Resources {
class IResourceWriter {
public:
    inline static _TypePtr _IResourceWriter;
};
}
