/// <summary>
/// Name: System::Resources::IResourceReader
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Resources {
class IResourceReader {
public:
    inline static _TypePtr _IResourceReader;
};
}
