/// <summary>
/// Name: System::Resources::MissingManifestResourceException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Resources {
class MissingManifestResourceException {
public:
    inline static _TypePtr _MissingManifestResourceException;
};
}
