/// <summary>
/// Name: System::Resources::MissingSatelliteAssemblyException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Resources {
class MissingSatelliteAssemblyException {
public:
    inline static _TypePtr _MissingSatelliteAssemblyException;
};
}
