/// <summary>
/// Name: System::Resources::NeutralResourcesLanguageAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Resources {
class NeutralResourcesLanguageAttribute {
public:
    inline static _TypePtr _NeutralResourcesLanguageAttribute;
};
}
