/// <summary>
/// Name: System::Resources::ResourceManager
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Resources {
class ResourceManager {
public:
    inline static _TypePtr _ResourceManager;
};
}
