/// <summary>
/// Name: System::Resources::ResourceSet
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Resources {
class ResourceSet {
public:
    inline static _TypePtr _ResourceSet;
};
}
