/// <summary>
/// Name: System::Resources::ResourceWriter
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Resources {
class ResourceWriter {
public:
    inline static _TypePtr _ResourceWriter;
};
}
