/// <summary>
/// Name: System::Resources::ResourceReader
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Resources {
class ResourceReader {
public:
    inline static _TypePtr _ResourceReader;
};
}
