/// <summary>
/// Name: System::Resources::SatelliteContractVersionAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Resources {
class SatelliteContractVersionAttribute {
public:
    inline static _TypePtr _SatelliteContractVersionAttribute;
};
}
