/// <summary>
/// Name: System::Resources::UltimateResourceFallbackLocation
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Resources {
class UltimateResourceFallbackLocation {
public:
    inline static _TypePtr _UltimateResourceFallbackLocation;
};
}
