/// <summary>
/// Name: System::Runtime::Hosting::ActivationArguments
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Hosting {
class ActivationArguments {
public:
    inline static _TypePtr _ActivationArguments;
};
}
