/// <summary>
/// Name: System::Runtime::Hosting::ApplicationActivator
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Hosting {
class ApplicationActivator {
public:
    inline static _TypePtr _ApplicationActivator;
};
}
