/// <summary>
/// Name: System::Runtime::InteropServices::Expando::IExpando
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices::Expando {
class IExpando {
public:
    inline static _TypePtr _IExpando;
};
}
