/// <summary>
/// Name: System::Runtime::InteropServices::_Activator
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class _Activator {
public:
    inline static _TypePtr __Activator;
};
}
