/// <summary>
/// Name: System::Runtime::InteropServices::_Assembly
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class _Assembly {
public:
    inline static _TypePtr __Assembly;
};
}
