/// <summary>
/// Name: System::Runtime::InteropServices::_AssemblyBuilder
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class _AssemblyBuilder {
public:
    inline static _TypePtr __AssemblyBuilder;
};
}
