/// <summary>
/// Name: System::Runtime::InteropServices::_AssemblyName
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class _AssemblyName {
public:
    inline static _TypePtr __AssemblyName;
};
}
