/// <summary>
/// Name: System::Runtime::InteropServices::_Attribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class _Attribute {
public:
    inline static _TypePtr __Attribute;
};
}
