/// <summary>
/// Name: System::Runtime::InteropServices::_ConstructorBuilder
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class _ConstructorBuilder {
public:
    inline static _TypePtr __ConstructorBuilder;
};
}
