/// <summary>
/// Name: System::Runtime::InteropServices::_CustomAttributeBuilder
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class _CustomAttributeBuilder {
public:
    inline static _TypePtr __CustomAttributeBuilder;
};
}
