/// <summary>
/// Name: System::Runtime::InteropServices::_EventInfo
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class _EventInfo {
public:
    inline static _TypePtr __EventInfo;
};
}
