/// <summary>
/// Name: System::Runtime::InteropServices::_Exception
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class _Exception {
public:
    inline static _TypePtr __Exception;
};
}
