/// <summary>
/// Name: System::Runtime::InteropServices::_FieldBuilder
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class _FieldBuilder {
public:
    inline static _TypePtr __FieldBuilder;
};
}
