/// <summary>
/// Name: System::Runtime::InteropServices::_FieldInfo
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class _FieldInfo {
public:
    inline static _TypePtr __FieldInfo;
};
}
