/// <summary>
/// Name: System::Runtime::InteropServices::_ILGenerator
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class _ILGenerator {
public:
    inline static _TypePtr __ILGenerator;
};
}
