/// <summary>
/// Name: System::Runtime::InteropServices::_LocalBuilder
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class _LocalBuilder {
public:
    inline static _TypePtr __LocalBuilder;
};
}
