/// <summary>
/// Name: System::Runtime::InteropServices::_MemberInfo
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class _MemberInfo {
public:
    inline static _TypePtr __MemberInfo;
};
}
