/// <summary>
/// Name: System::Runtime::InteropServices::_MethodInfo
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class _MethodInfo {
public:
    inline static _TypePtr __MethodInfo;
};
}
