/// <summary>
/// Name: System::Runtime::InteropServices::_MethodBase
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class _MethodBase {
public:
    inline static _TypePtr __MethodBase;
};
}
