/// <summary>
/// Name: System::Runtime::InteropServices::_MethodBuilder
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class _MethodBuilder {
public:
    inline static _TypePtr __MethodBuilder;
};
}
