/// <summary>
/// Name: System::Runtime::InteropServices::_MethodRental
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class _MethodRental {
public:
    inline static _TypePtr __MethodRental;
};
}
