/// <summary>
/// Name: System::Runtime::InteropServices::_ModuleBuilder
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class _ModuleBuilder {
public:
    inline static _TypePtr __ModuleBuilder;
};
}
