/// <summary>
/// Name: System::Runtime::InteropServices::_Module
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class _Module {
public:
    inline static _TypePtr __Module;
};
}
