/// <summary>
/// Name: System::Runtime::InteropServices::_ParameterInfo
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class _ParameterInfo {
public:
    inline static _TypePtr __ParameterInfo;
};
}
