/// <summary>
/// Name: System::Runtime::InteropServices::_ParameterBuilder
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class _ParameterBuilder {
public:
    inline static _TypePtr __ParameterBuilder;
};
}
