/// <summary>
/// Name: System::Runtime::InteropServices::_PropertyBuilder
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class _PropertyBuilder {
public:
    inline static _TypePtr __PropertyBuilder;
};
}
