/// <summary>
/// Name: System::Runtime::InteropServices::_PropertyInfo
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class _PropertyInfo {
public:
    inline static _TypePtr __PropertyInfo;
};
}
