/// <summary>
/// Name: System::Runtime::InteropServices::_Thread
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class _Thread {
public:
    inline static _TypePtr __Thread;
};
}
