/// <summary>
/// Name: System::Runtime::InteropServices::_TypeBuilder
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class _TypeBuilder {
public:
    inline static _TypePtr __TypeBuilder;
};
}
