/// <summary>
/// Name: System::Runtime::InteropServices::_Type
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class _Type {
public:
    inline static _TypePtr __Type;
};
}
