/// <summary>
/// Name: System::Runtime::InteropServices::AllowReversePInvokeCallsAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class AllowReversePInvokeCallsAttribute {
public:
    inline static _TypePtr _AllowReversePInvokeCallsAttribute;
};
}
