/// <summary>
/// Name: System::Runtime::InteropServices::ArrayWithOffset
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class ArrayWithOffset {
public:
    inline static _TypePtr _ArrayWithOffset;
};
}
