/// <summary>
/// Name: System::Runtime::InteropServices::AssemblyRegistrationFlags
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class AssemblyRegistrationFlags {
public:
    inline static _TypePtr _AssemblyRegistrationFlags;
};
}
