/// <summary>
/// Name: System::Runtime::InteropServices::AutomationProxyAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class AutomationProxyAttribute {
public:
    inline static _TypePtr _AutomationProxyAttribute;
};
}
