/// <summary>
/// Name: System::Runtime::InteropServices::BestFitMappingAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class BestFitMappingAttribute {
public:
    inline static _TypePtr _BestFitMappingAttribute;
};
}
