/// <summary>
/// Name: System::Runtime::InteropServices::BIND_OPTS
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class BIND_OPTS {
public:
    inline static _TypePtr _BIND_OPTS;
};
}
