/// <summary>
/// Name: System::Runtime::InteropServices::BStrWrapper
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class BStrWrapper {
public:
    inline static _TypePtr _BStrWrapper;
};
}
