/// <summary>
/// Name: System::Runtime::InteropServices::CallingConvention
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class CallingConvention {
public:
    inline static _TypePtr _CallingConvention;
};
}
