/// <summary>
/// Name: System::Runtime::InteropServices::CALLCONV
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class CALLCONV {
public:
    inline static _TypePtr _CALLCONV;
};
}
