/// <summary>
/// Name: System::Runtime::InteropServices::CharSet
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class CharSet {
public:
    inline static _TypePtr _CharSet;
};
}
