/// <summary>
/// Name: System::Runtime::InteropServices::ClassInterfaceType
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class ClassInterfaceType {
public:
    inline static _TypePtr _ClassInterfaceType;
};
}
