/// <summary>
/// Name: System::Runtime::InteropServices::ClassInterfaceAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class ClassInterfaceAttribute {
public:
    inline static _TypePtr _ClassInterfaceAttribute;
};
}
