/// <summary>
/// Name: System::Runtime::InteropServices::CoClassAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class CoClassAttribute {
public:
    inline static _TypePtr _CoClassAttribute;
};
}
