/// <summary>
/// Name: System::Runtime::InteropServices::ComAliasNameAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class ComAliasNameAttribute {
public:
    inline static _TypePtr _ComAliasNameAttribute;
};
}
