/// <summary>
/// Name: System::Runtime::InteropServices::ComConversionLossAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class ComConversionLossAttribute {
public:
    inline static _TypePtr _ComConversionLossAttribute;
};
}
