/// <summary>
/// Name: System::Runtime::InteropServices::ComCompatibleVersionAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class ComCompatibleVersionAttribute {
public:
    inline static _TypePtr _ComCompatibleVersionAttribute;
};
}
