/// <summary>
/// Name: System::Runtime::InteropServices::ComDefaultInterfaceAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class ComDefaultInterfaceAttribute {
public:
    inline static _TypePtr _ComDefaultInterfaceAttribute;
};
}
