/// <summary>
/// Name: System::Runtime::InteropServices::ComEventInterfaceAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class ComEventInterfaceAttribute {
public:
    inline static _TypePtr _ComEventInterfaceAttribute;
};
}
