/// <summary>
/// Name: System::Runtime::InteropServices::COMException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class COMException {
public:
    inline static _TypePtr _COMException;
};
}
