/// <summary>
/// Name: System::Runtime::InteropServices::ComInterfaceType
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class ComInterfaceType {
public:
    inline static _TypePtr _ComInterfaceType;
};
}
