/// <summary>
/// Name: System::Runtime::InteropServices::ComImportAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class ComImportAttribute {
public:
    inline static _TypePtr _ComImportAttribute;
};
}
