/// <summary>
/// Name: System::Runtime::InteropServices::ComMemberType
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class ComMemberType {
public:
    inline static _TypePtr _ComMemberType;
};
}
