/// <summary>
/// Name: System::Runtime::InteropServices::ComSourceInterfacesAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class ComSourceInterfacesAttribute {
public:
    inline static _TypePtr _ComSourceInterfacesAttribute;
};
}
