/// <summary>
/// Name: System::Runtime::InteropServices::ComUnregisterFunctionAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class ComUnregisterFunctionAttribute {
public:
    inline static _TypePtr _ComUnregisterFunctionAttribute;
};
}
