/// <summary>
/// Name: System::Runtime::InteropServices::ComVisibleAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class ComVisibleAttribute {
public:
    inline static _TypePtr _ComVisibleAttribute;
};
}
