/// <summary>
/// Name: System::Runtime::InteropServices::CONNECTDATA
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class CONNECTDATA {
public:
    inline static _TypePtr _CONNECTDATA;
};
}
