/// <summary>
/// Name: System::Runtime::InteropServices::DefaultCharSetAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class DefaultCharSetAttribute {
public:
    inline static _TypePtr _DefaultCharSetAttribute;
};
}
