/// <summary>
/// Name: System::Runtime::InteropServices::DISPPARAMS
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class DISPPARAMS {
public:
    inline static _TypePtr _DISPPARAMS;
};
}
