/// <summary>
/// Name: System::Runtime::InteropServices::DispIdAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class DispIdAttribute {
public:
    inline static _TypePtr _DispIdAttribute;
};
}
