/// <summary>
/// Name: System::Runtime::InteropServices::DllImportAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class DllImportAttribute {
public:
    inline static _TypePtr _DllImportAttribute;
};
}
