/// <summary>
/// Name: System::Runtime::InteropServices::ErrorWrapper
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class ErrorWrapper {
public:
    inline static _TypePtr _ErrorWrapper;
};
}
