/// <summary>
/// Name: System::Runtime::InteropServices::EXCEPINFO
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class EXCEPINFO {
public:
    inline static _TypePtr _EXCEPINFO;
};
}
