/// <summary>
/// Name: System::Runtime::InteropServices::ExtensibleClassFactory
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class ExtensibleClassFactory {
public:
    inline static _TypePtr _ExtensibleClassFactory;
};
}
