/// <summary>
/// Name: System::Runtime::InteropServices::FieldOffsetAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class FieldOffsetAttribute {
public:
    inline static _TypePtr _FieldOffsetAttribute;
};
}
