/// <summary>
/// Name: System::Runtime::InteropServices::FILETIME
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class FILETIME {
public:
    inline static _TypePtr _FILETIME;
};
}
