/// <summary>
/// Name: System::Runtime::InteropServices::FUNCKIND
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class FUNCKIND {
public:
    inline static _TypePtr _FUNCKIND;
};
}
