/// <summary>
/// Name: System::Runtime::InteropServices::FUNCFLAGS
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class FUNCFLAGS {
public:
    inline static _TypePtr _FUNCFLAGS;
};
}
