/// <summary>
/// Name: System::Runtime::InteropServices::GCHandleType
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class GCHandleType {
public:
    inline static _TypePtr _GCHandleType;
};
}
