/// <summary>
/// Name: System::Runtime::InteropServices::GuidAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class GuidAttribute {
public:
    inline static _TypePtr _GuidAttribute;
};
}
