/// <summary>
/// Name: System::Runtime::InteropServices::HandleRef
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class HandleRef {
public:
    inline static _TypePtr _HandleRef;
};
}
