/// <summary>
/// Name: System::Runtime::InteropServices::ICustomFactory
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class ICustomFactory {
public:
    inline static _TypePtr _ICustomFactory;
};
}
