/// <summary>
/// Name: System::Runtime::InteropServices::ICustomAdapter
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class ICustomAdapter {
public:
    inline static _TypePtr _ICustomAdapter;
};
}
