/// <summary>
/// Name: System::Runtime::InteropServices::ICustomMarshaler
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class ICustomMarshaler {
public:
    inline static _TypePtr _ICustomMarshaler;
};
}
