/// <summary>
/// Name: System::Runtime::InteropServices::IDispatchImplAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class IDispatchImplAttribute {
public:
    inline static _TypePtr _IDispatchImplAttribute;
};
}
