/// <summary>
/// Name: System::Runtime::InteropServices::IDispatchImplType
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class IDispatchImplType {
public:
    inline static _TypePtr _IDispatchImplType;
};
}
