/// <summary>
/// Name: System::Runtime::InteropServices::IDLFLAG
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class IDLFLAG {
public:
    inline static _TypePtr _IDLFLAG;
};
}
