/// <summary>
/// Name: System::Runtime::InteropServices::ImportedFromTypeLibAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class ImportedFromTypeLibAttribute {
public:
    inline static _TypePtr _ImportedFromTypeLibAttribute;
};
}
