/// <summary>
/// Name: System::Runtime::InteropServices::ImporterEventKind
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class ImporterEventKind {
public:
    inline static _TypePtr _ImporterEventKind;
};
}
