/// <summary>
/// Name: System::Runtime::InteropServices::InAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class InAttribute {
public:
    inline static _TypePtr _InAttribute;
};
}
