/// <summary>
/// Name: System::Runtime::InteropServices::InterfaceTypeAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class InterfaceTypeAttribute {
public:
    inline static _TypePtr _InterfaceTypeAttribute;
};
}
