/// <summary>
/// Name: System::Runtime::InteropServices::InvalidComObjectException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class InvalidComObjectException {
public:
    inline static _TypePtr _InvalidComObjectException;
};
}
