/// <summary>
/// Name: System::Runtime::InteropServices::InvalidOleVariantTypeException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class InvalidOleVariantTypeException {
public:
    inline static _TypePtr _InvalidOleVariantTypeException;
};
}
