/// <summary>
/// Name: System::Runtime::InteropServices::INVOKEKIND
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class INVOKEKIND {
public:
    inline static _TypePtr _INVOKEKIND;
};
}
