/// <summary>
/// Name: System::Runtime::InteropServices::IRegistrationServices
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class IRegistrationServices {
public:
    inline static _TypePtr _IRegistrationServices;
};
}
