/// <summary>
/// Name: System::Runtime::InteropServices::ITypeLibImporterNotifySink
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class ITypeLibImporterNotifySink {
public:
    inline static _TypePtr _ITypeLibImporterNotifySink;
};
}
