/// <summary>
/// Name: System::Runtime::InteropServices::ITypeLibExporterNameProvider
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class ITypeLibExporterNameProvider {
public:
    inline static _TypePtr _ITypeLibExporterNameProvider;
};
}
