/// <summary>
/// Name: System::Runtime::InteropServices::ITypeLibExporterNotifySink
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class ITypeLibExporterNotifySink {
public:
    inline static _TypePtr _ITypeLibExporterNotifySink;
};
}
