/// <summary>
/// Name: System::Runtime::InteropServices::ITypeLibConverter
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class ITypeLibConverter {
public:
    inline static _TypePtr _ITypeLibConverter;
};
}
