/// <summary>
/// Name: System::Runtime::InteropServices::LayoutKind
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class LayoutKind {
public:
    inline static _TypePtr _LayoutKind;
};
}
