/// <summary>
/// Name: System::Runtime::InteropServices::LCIDConversionAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class LCIDConversionAttribute {
public:
    inline static _TypePtr _LCIDConversionAttribute;
};
}
