/// <summary>
/// Name: System::Runtime::InteropServices::LIBFLAGS
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class LIBFLAGS {
public:
    inline static _TypePtr _LIBFLAGS;
};
}
