/// <summary>
/// Name: System::Runtime::InteropServices::MarshalAsAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class MarshalAsAttribute {
public:
    inline static _TypePtr _MarshalAsAttribute;
};
}
