/// <summary>
/// Name: System::Runtime::InteropServices::Marshal
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class Marshal {
public:
    inline static _TypePtr _Marshal;
};
}
