/// <summary>
/// Name: System::Runtime::InteropServices::MarshalDirectiveException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class MarshalDirectiveException {
public:
    inline static _TypePtr _MarshalDirectiveException;
};
}
