/// <summary>
/// Name: System::Runtime::InteropServices::ObjectCreationDelegate
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class ObjectCreationDelegate {
public:
    inline static _TypePtr _ObjectCreationDelegate;
};
}
