/// <summary>
/// Name: System::Runtime::InteropServices::OptionalAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class OptionalAttribute {
public:
    inline static _TypePtr _OptionalAttribute;
};
}
