/// <summary>
/// Name: System::Runtime::InteropServices::OutAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class OutAttribute {
public:
    inline static _TypePtr _OutAttribute;
};
}
