/// <summary>
/// Name: System::Runtime::InteropServices::PARAMDESC
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class PARAMDESC {
public:
    inline static _TypePtr _PARAMDESC;
};
}
