/// <summary>
/// Name: System::Runtime::InteropServices::PreserveSigAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class PreserveSigAttribute {
public:
    inline static _TypePtr _PreserveSigAttribute;
};
}
