/// <summary>
/// Name: System::Runtime::InteropServices::PrimaryInteropAssemblyAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class PrimaryInteropAssemblyAttribute {
public:
    inline static _TypePtr _PrimaryInteropAssemblyAttribute;
};
}
