/// <summary>
/// Name: System::Runtime::InteropServices::ProgIdAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class ProgIdAttribute {
public:
    inline static _TypePtr _ProgIdAttribute;
};
}
