/// <summary>
/// Name: System::Runtime::InteropServices::RegistrationConnectionType
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class RegistrationConnectionType {
public:
    inline static _TypePtr _RegistrationConnectionType;
};
}
