/// <summary>
/// Name: System::Runtime::InteropServices::RegistrationServices
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class RegistrationServices {
public:
    inline static _TypePtr _RegistrationServices;
};
}
