/// <summary>
/// Name: System::Runtime::InteropServices::RegistrationClassContext
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class RegistrationClassContext {
public:
    inline static _TypePtr _RegistrationClassContext;
};
}
