/// <summary>
/// Name: System::Runtime::InteropServices::RuntimeEnvironment
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class RuntimeEnvironment {
public:
    inline static _TypePtr _RuntimeEnvironment;
};
}
