/// <summary>
/// Name: System::Runtime::InteropServices::SafeArrayRankMismatchException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class SafeArrayRankMismatchException {
public:
    inline static _TypePtr _SafeArrayRankMismatchException;
};
}
