/// <summary>
/// Name: System::Runtime::InteropServices::SafeArrayTypeMismatchException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class SafeArrayTypeMismatchException {
public:
    inline static _TypePtr _SafeArrayTypeMismatchException;
};
}
