/// <summary>
/// Name: System::Runtime::InteropServices::SafeHandle
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class SafeHandle {
public:
    inline static _TypePtr _SafeHandle;
};
}
