/// <summary>
/// Name: System::Runtime::InteropServices::SetWin32ContextInIDispatchAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class SetWin32ContextInIDispatchAttribute {
public:
    inline static _TypePtr _SetWin32ContextInIDispatchAttribute;
};
}
