/// <summary>
/// Name: System::Runtime::InteropServices::StructLayoutAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class StructLayoutAttribute {
public:
    inline static _TypePtr _StructLayoutAttribute;
};
}
