/// <summary>
/// Name: System::Runtime::InteropServices::SYSKIND
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class SYSKIND {
public:
    inline static _TypePtr _SYSKIND;
};
}
