/// <summary>
/// Name: System::Runtime::InteropServices::TYPEDESC
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class TYPEDESC {
public:
    inline static _TypePtr _TYPEDESC;
};
}
