/// <summary>
/// Name: System::Runtime::InteropServices::TypeLibConverter
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class TypeLibConverter {
public:
    inline static _TypePtr _TypeLibConverter;
};
}
