/// <summary>
/// Name: System::Runtime::InteropServices::TypeLibVarAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class TypeLibVarAttribute {
public:
    inline static _TypePtr _TypeLibVarAttribute;
};
}
