/// <summary>
/// Name: System::Runtime::InteropServices::TypeLibTypeAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class TypeLibTypeAttribute {
public:
    inline static _TypePtr _TypeLibTypeAttribute;
};
}
