/// <summary>
/// Name: System::Runtime::InteropServices::TypeLibTypeFlags
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class TypeLibTypeFlags {
public:
    inline static _TypePtr _TypeLibTypeFlags;
};
}
