/// <summary>
/// Name: System::Runtime::InteropServices::TypeLibFuncFlags
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class TypeLibFuncFlags {
public:
    inline static _TypePtr _TypeLibFuncFlags;
};
}
