/// <summary>
/// Name: System::Runtime::InteropServices::TypeLibFuncAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class TypeLibFuncAttribute {
public:
    inline static _TypePtr _TypeLibFuncAttribute;
};
}
