/// <summary>
/// Name: System::Runtime::InteropServices::TypeLibImportClassAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class TypeLibImportClassAttribute {
public:
    inline static _TypePtr _TypeLibImportClassAttribute;
};
}
