/// <summary>
/// Name: System::Runtime::InteropServices::TypeLibImporterFlags
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class TypeLibImporterFlags {
public:
    inline static _TypePtr _TypeLibImporterFlags;
};
}
