/// <summary>
/// Name: System::Runtime::InteropServices::TypeLibVarFlags
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class TypeLibVarFlags {
public:
    inline static _TypePtr _TypeLibVarFlags;
};
}
