/// <summary>
/// Name: System::Runtime::InteropServices::TypeLibExporterFlags
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class TypeLibExporterFlags {
public:
    inline static _TypePtr _TypeLibExporterFlags;
};
}
