/// <summary>
/// Name: System::Runtime::InteropServices::TypeLibVersionAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class TypeLibVersionAttribute {
public:
    inline static _TypePtr _TypeLibVersionAttribute;
};
}
