/// <summary>
/// Name: System::Runtime::InteropServices::UCOMIEnumConnectionPoints
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class UCOMIEnumConnectionPoints {
public:
    inline static _TypePtr _UCOMIEnumConnectionPoints;
};
}
