/// <summary>
/// Name: System::Runtime::InteropServices::UCOMIBindCtx
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class UCOMIBindCtx {
public:
    inline static _TypePtr _UCOMIBindCtx;
};
}
