/// <summary>
/// Name: System::Runtime::InteropServices::UCOMIPersistFile
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class UCOMIPersistFile {
public:
    inline static _TypePtr _UCOMIPersistFile;
};
}
