/// <summary>
/// Name: System::Runtime::InteropServices::UCOMIStream
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class UCOMIStream {
public:
    inline static _TypePtr _UCOMIStream;
};
}
