/// <summary>
/// Name: System::Runtime::InteropServices::UCOMIConnectionPointContainer
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class UCOMIConnectionPointContainer {
public:
    inline static _TypePtr _UCOMIConnectionPointContainer;
};
}
