/// <summary>
/// Name: System::Runtime::InteropServices::UCOMIMoniker
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class UCOMIMoniker {
public:
    inline static _TypePtr _UCOMIMoniker;
};
}
