/// <summary>
/// Name: System::Runtime::InteropServices::UCOMIConnectionPoint
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class UCOMIConnectionPoint {
public:
    inline static _TypePtr _UCOMIConnectionPoint;
};
}
