/// <summary>
/// Name: System::Runtime::InteropServices::UCOMIEnumString
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class UCOMIEnumString {
public:
    inline static _TypePtr _UCOMIEnumString;
};
}
