/// <summary>
/// Name: System::Runtime::InteropServices::UCOMIEnumVARIANT
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class UCOMIEnumVARIANT {
public:
    inline static _TypePtr _UCOMIEnumVARIANT;
};
}
