/// <summary>
/// Name: System::Runtime::InteropServices::UCOMITypeLib
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class UCOMITypeLib {
public:
    inline static _TypePtr _UCOMITypeLib;
};
}
