/// <summary>
/// Name: System::Runtime::InteropServices::UCOMITypeInfo
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class UCOMITypeInfo {
public:
    inline static _TypePtr _UCOMITypeInfo;
};
}
