/// <summary>
/// Name: System::Runtime::InteropServices::UCOMIRunningObjectTable
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class UCOMIRunningObjectTable {
public:
    inline static _TypePtr _UCOMIRunningObjectTable;
};
}
