/// <summary>
/// Name: System::Runtime::InteropServices::UCOMITypeComp
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class UCOMITypeComp {
public:
    inline static _TypePtr _UCOMITypeComp;
};
}
