/// <summary>
/// Name: System::Runtime::InteropServices::UCOMIEnumMoniker
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class UCOMIEnumMoniker {
public:
    inline static _TypePtr _UCOMIEnumMoniker;
};
}
