/// <summary>
/// Name: System::Runtime::InteropServices::UnknownWrapper
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class UnknownWrapper {
public:
    inline static _TypePtr _UnknownWrapper;
};
}
