/// <summary>
/// Name: System::Runtime::InteropServices::UnmanagedType
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class UnmanagedType {
public:
    inline static _TypePtr _UnmanagedType;
};
}
