/// <summary>
/// Name: System::Runtime::InteropServices::VARDESC
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class VARDESC {
public:
    inline static _TypePtr _VARDESC;
};
}
