/// <summary>
/// Name: System::Runtime::InteropServices::VARFLAGS
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class VARFLAGS {
public:
    inline static _TypePtr _VARFLAGS;
};
}
