/// <summary>
/// Name: System::Runtime::InteropServices::VariantWrapper
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::InteropServices {
class VariantWrapper {
public:
    inline static _TypePtr _VariantWrapper;
};
}
