/// <summary>
/// Name: System::Security::Permissions::CodeAccessSecurityAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Permissions {
class CodeAccessSecurityAttribute {
public:
    inline static _TypePtr _CodeAccessSecurityAttribute;
};
}
