/// <summary>
/// Name: System::Security::Permissions::EnvironmentPermission
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Permissions {
class EnvironmentPermission {
public:
    inline static _TypePtr _EnvironmentPermission;
};
}
