/// <summary>
/// Name: System::Security::Permissions::EnvironmentPermissionAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Permissions {
class EnvironmentPermissionAttribute {
public:
    inline static _TypePtr _EnvironmentPermissionAttribute;
};
}
