/// <summary>
/// Name: System::Security::Permissions::EnvironmentPermissionAccess
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Permissions {
class EnvironmentPermissionAccess {
public:
    inline static _TypePtr _EnvironmentPermissionAccess;
};
}
