/// <summary>
/// Name: System::Security::Permissions::FileDialogPermissionAccess
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Permissions {
class FileDialogPermissionAccess {
public:
    inline static _TypePtr _FileDialogPermissionAccess;
};
}
