/// <summary>
/// Name: System::Security::Permissions::FileDialogPermissionAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Permissions {
class FileDialogPermissionAttribute {
public:
    inline static _TypePtr _FileDialogPermissionAttribute;
};
}
