/// <summary>
/// Name: System::Security::Permissions::FileIOPermissionAccess
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Permissions {
class FileIOPermissionAccess {
public:
    inline static _TypePtr _FileIOPermissionAccess;
};
}
