/// <summary>
/// Name: System::Security::Permissions::FileIOPermission
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Permissions {
class FileIOPermission {
public:
    inline static _TypePtr _FileIOPermission;
};
}
