/// <summary>
/// Name: System::Security::Permissions::FileDialogPermission
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Permissions {
class FileDialogPermission {
public:
    inline static _TypePtr _FileDialogPermission;
};
}
