/// <summary>
/// Name: System::Security::Permissions::FileIOPermissionAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Permissions {
class FileIOPermissionAttribute {
public:
    inline static _TypePtr _FileIOPermissionAttribute;
};
}
