/// <summary>
/// Name: System::Security::Permissions::GacIdentityPermissionAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Permissions {
class GacIdentityPermissionAttribute {
public:
    inline static _TypePtr _GacIdentityPermissionAttribute;
};
}
