/// <summary>
/// Name: System::Security::Permissions::GacIdentityPermission
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Permissions {
class GacIdentityPermission {
public:
    inline static _TypePtr _GacIdentityPermission;
};
}
