/// <summary>
/// Name: System::Security::Permissions::HostProtectionAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Permissions {
class HostProtectionAttribute {
public:
    inline static _TypePtr _HostProtectionAttribute;
};
}
