/// <summary>
/// Name: System::Security::Permissions::HostProtectionResource
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Permissions {
class HostProtectionResource {
public:
    inline static _TypePtr _HostProtectionResource;
};
}
