/// <summary>
/// Name: System::Security::Permissions::IsolatedStorageContainment
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Permissions {
class IsolatedStorageContainment {
public:
    inline static _TypePtr _IsolatedStorageContainment;
};
}
