/// <summary>
/// Name: System::Security::Permissions::IsolatedStoragePermission
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Permissions {
class IsolatedStoragePermission {
public:
    inline static _TypePtr _IsolatedStoragePermission;
};
}
