/// <summary>
/// Name: System::Security::Permissions::IsolatedStorageFilePermission
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Permissions {
class IsolatedStorageFilePermission {
public:
    inline static _TypePtr _IsolatedStorageFilePermission;
};
}
