/// <summary>
/// Name: System::Security::Permissions::IsolatedStoragePermissionAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Permissions {
class IsolatedStoragePermissionAttribute {
public:
    inline static _TypePtr _IsolatedStoragePermissionAttribute;
};
}
