/// <summary>
/// Name: System::Security::Permissions::IUnrestrictedPermission
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Permissions {
class IUnrestrictedPermission {
public:
    inline static _TypePtr _IUnrestrictedPermission;
};
}
