/// <summary>
/// Name: System::Security::Permissions::KeyContainerPermissionFlags
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Permissions {
class KeyContainerPermissionFlags {
public:
    inline static _TypePtr _KeyContainerPermissionFlags;
};
}
