/// <summary>
/// Name: System::Security::Permissions::KeyContainerPermission
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Permissions {
class KeyContainerPermission {
public:
    inline static _TypePtr _KeyContainerPermission;
};
}
