/// <summary>
/// Name: System::Security::Permissions::KeyContainerPermissionAccessEntryEnumerator
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Permissions {
class KeyContainerPermissionAccessEntryEnumerator {
public:
    inline static _TypePtr _KeyContainerPermissionAccessEntryEnumerator;
};
}
