/// <summary>
/// Name: System::Security::Permissions::KeyContainerPermissionAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Permissions {
class KeyContainerPermissionAttribute {
public:
    inline static _TypePtr _KeyContainerPermissionAttribute;
};
}
