/// <summary>
/// Name: System::Security::Permissions::KeyContainerPermissionAccessEntryCollection
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Permissions {
class KeyContainerPermissionAccessEntryCollection {
public:
    inline static _TypePtr _KeyContainerPermissionAccessEntryCollection;
};
}
