/// <summary>
/// Name: System::Security::Permissions::KeyContainerPermissionAccessEntry
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Permissions {
class KeyContainerPermissionAccessEntry {
public:
    inline static _TypePtr _KeyContainerPermissionAccessEntry;
};
}
