/// <summary>
/// Name: System::Security::Permissions::PermissionState
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Permissions {
class PermissionState {
public:
    inline static _TypePtr _PermissionState;
};
}
