/// <summary>
/// Name: System::Security::Permissions::PermissionSetAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Permissions {
class PermissionSetAttribute {
public:
    inline static _TypePtr _PermissionSetAttribute;
};
}
