/// <summary>
/// Name: System::Security::Permissions::PrincipalPermissionAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Permissions {
class PrincipalPermissionAttribute {
public:
    inline static _TypePtr _PrincipalPermissionAttribute;
};
}
