/// <summary>
/// Name: System::Security::Permissions::PrincipalPermission
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Permissions {
class PrincipalPermission {
public:
    inline static _TypePtr _PrincipalPermission;
};
}
