/// <summary>
/// Name: System::Security::Permissions::PublisherIdentityPermission
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Permissions {
class PublisherIdentityPermission {
public:
    inline static _TypePtr _PublisherIdentityPermission;
};
}
