/// <summary>
/// Name: System::Security::Permissions::PublisherIdentityPermissionAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Permissions {
class PublisherIdentityPermissionAttribute {
public:
    inline static _TypePtr _PublisherIdentityPermissionAttribute;
};
}
