/// <summary>
/// Name: System::Security::Permissions::ReflectionPermissionFlag
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Permissions {
class ReflectionPermissionFlag {
public:
    inline static _TypePtr _ReflectionPermissionFlag;
};
}
