/// <summary>
/// Name: System::Security::Permissions::ReflectionPermissionAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Permissions {
class ReflectionPermissionAttribute {
public:
    inline static _TypePtr _ReflectionPermissionAttribute;
};
}
