/// <summary>
/// Name: System::Security::Permissions::ReflectionPermission
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Permissions {
class ReflectionPermission {
public:
    inline static _TypePtr _ReflectionPermission;
};
}
