/// <summary>
/// Name: System::Security::Permissions::RegistryPermissionAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Permissions {
class RegistryPermissionAttribute {
public:
    inline static _TypePtr _RegistryPermissionAttribute;
};
}
