/// <summary>
/// Name: System::Security::Permissions::RegistryPermission
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Permissions {
class RegistryPermission {
public:
    inline static _TypePtr _RegistryPermission;
};
}
