/// <summary>
/// Name: System::Security::Permissions::RegistryPermissionAccess
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Permissions {
class RegistryPermissionAccess {
public:
    inline static _TypePtr _RegistryPermissionAccess;
};
}
