/// <summary>
/// Name: System::Security::Permissions::SecurityPermissionAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Permissions {
class SecurityPermissionAttribute {
public:
    inline static _TypePtr _SecurityPermissionAttribute;
};
}
