/// <summary>
/// Name: System::Security::Permissions::SecurityPermissionFlag
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Permissions {
class SecurityPermissionFlag {
public:
    inline static _TypePtr _SecurityPermissionFlag;
};
}
