/// <summary>
/// Name: System::Security::Permissions::SecurityAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Permissions {
class SecurityAttribute {
public:
    inline static _TypePtr _SecurityAttribute;
};
}
