/// <summary>
/// Name: System::Security::Permissions::SecurityAction
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Permissions {
class SecurityAction {
public:
    inline static _TypePtr _SecurityAction;
};
}
