/// <summary>
/// Name: System::Security::Permissions::SiteIdentityPermissionAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Permissions {
class SiteIdentityPermissionAttribute {
public:
    inline static _TypePtr _SiteIdentityPermissionAttribute;
};
}
