/// <summary>
/// Name: System::Security::Permissions::SiteIdentityPermission
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Permissions {
class SiteIdentityPermission {
public:
    inline static _TypePtr _SiteIdentityPermission;
};
}
