/// <summary>
/// Name: System::Security::Permissions::StrongNameIdentityPermissionAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Permissions {
class StrongNameIdentityPermissionAttribute {
public:
    inline static _TypePtr _StrongNameIdentityPermissionAttribute;
};
}
