/// <summary>
/// Name: System::Security::Permissions::StrongNamePublicKeyBlob
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Permissions {
class StrongNamePublicKeyBlob {
public:
    inline static _TypePtr _StrongNamePublicKeyBlob;
};
}
