/// <summary>
/// Name: System::Security::Permissions::UIPermissionClipboard
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Permissions {
class UIPermissionClipboard {
public:
    inline static _TypePtr _UIPermissionClipboard;
};
}
