/// <summary>
/// Name: System::Security::Permissions::UIPermissionWindow
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Permissions {
class UIPermissionWindow {
public:
    inline static _TypePtr _UIPermissionWindow;
};
}
