/// <summary>
/// Name: System::Security::Permissions::UIPermissionAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Permissions {
class UIPermissionAttribute {
public:
    inline static _TypePtr _UIPermissionAttribute;
};
}
