/// <summary>
/// Name: System::Security::Permissions::UrlIdentityPermission
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Permissions {
class UrlIdentityPermission {
public:
    inline static _TypePtr _UrlIdentityPermission;
};
}
