/// <summary>
/// Name: System::Security::Permissions::UrlIdentityPermissionAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Permissions {
class UrlIdentityPermissionAttribute {
public:
    inline static _TypePtr _UrlIdentityPermissionAttribute;
};
}
