/// <summary>
/// Name: System::Security::Permissions::ZoneIdentityPermission
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Permissions {
class ZoneIdentityPermission {
public:
    inline static _TypePtr _ZoneIdentityPermission;
};
}
