/// <summary>
/// Name: System::Security::Permissions::ZoneIdentityPermissionAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Permissions {
class ZoneIdentityPermissionAttribute {
public:
    inline static _TypePtr _ZoneIdentityPermissionAttribute;
};
}
