/// <summary>
/// Name: System::Runtime::Remoting::Contexts::ContextAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Contexts {
class ContextAttribute {
public:
    inline static _TypePtr _ContextAttribute;
};
}
