/// <summary>
/// Name: System::Runtime::Remoting::Contexts::ContextProperty
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Contexts {
class ContextProperty {
public:
    inline static _TypePtr _ContextProperty;
};
}
