/// <summary>
/// Name: System::Runtime::Remoting::Contexts::Context
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Contexts {
class Context {
public:
    inline static _TypePtr _Context;
};
}
