/// <summary>
/// Name: System::Runtime::Remoting::Contexts::CrossContextDelegate
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Contexts {
class CrossContextDelegate {
public:
    inline static _TypePtr _CrossContextDelegate;
};
}
