/// <summary>
/// Name: System::Runtime::Remoting::Contexts::IContributeServerContextSink
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Contexts {
class IContributeServerContextSink {
public:
    inline static _TypePtr _IContributeServerContextSink;
};
}
