/// <summary>
/// Name: System::Runtime::Remoting::Contexts::IContextAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Contexts {
class IContextAttribute {
public:
    inline static _TypePtr _IContextAttribute;
};
}
