/// <summary>
/// Name: System::Runtime::Remoting::Contexts::IContextProperty
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Contexts {
class IContextProperty {
public:
    inline static _TypePtr _IContextProperty;
};
}
