/// <summary>
/// Name: System::Runtime::Remoting::Contexts::IContributeClientContextSink
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Contexts {
class IContributeClientContextSink {
public:
    inline static _TypePtr _IContributeClientContextSink;
};
}
