/// <summary>
/// Name: System::Runtime::Remoting::Contexts::IContributeEnvoySink
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Contexts {
class IContributeEnvoySink {
public:
    inline static _TypePtr _IContributeEnvoySink;
};
}
