/// <summary>
/// Name: System::Runtime::Remoting::Contexts::IContextPropertyActivator
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Contexts {
class IContextPropertyActivator {
public:
    inline static _TypePtr _IContextPropertyActivator;
};
}
