/// <summary>
/// Name: System::Runtime::Remoting::Contexts::IContributeDynamicSink
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Contexts {
class IContributeDynamicSink {
public:
    inline static _TypePtr _IContributeDynamicSink;
};
}
