/// <summary>
/// Name: System::Runtime::Remoting::Contexts::IContributeObjectSink
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Contexts {
class IContributeObjectSink {
public:
    inline static _TypePtr _IContributeObjectSink;
};
}
