/// <summary>
/// Name: System::Runtime::Remoting::Contexts::IDynamicMessageSink
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Contexts {
class IDynamicMessageSink {
public:
    inline static _TypePtr _IDynamicMessageSink;
};
}
