/// <summary>
/// Name: System::Runtime::Remoting::Contexts::IDynamicProperty
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Contexts {
class IDynamicProperty {
public:
    inline static _TypePtr _IDynamicProperty;
};
}
