/// <summary>
/// Name: System::Runtime::Remoting::Contexts::SynchronizationAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Runtime::Remoting::Contexts {
class SynchronizationAttribute {
public:
    inline static _TypePtr _SynchronizationAttribute;
};
}
