/// <summary>
/// Name: System::Reflection::AmbiguousMatchException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection {
class AmbiguousMatchException {
public:
    inline static _TypePtr _AmbiguousMatchException;
};
}
