/// <summary>
/// Name: System::Reflection::AssemblyCopyrightAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection {
class AssemblyCopyrightAttribute {
public:
    inline static _TypePtr _AssemblyCopyrightAttribute;
};
}
