/// <summary>
/// Name: System::Reflection::AssemblyTitleAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection {
class AssemblyTitleAttribute {
public:
    inline static _TypePtr _AssemblyTitleAttribute;
};
}
