/// <summary>
/// Name: System::Reflection::AssemblyVersionAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection {
class AssemblyVersionAttribute {
public:
    inline static _TypePtr _AssemblyVersionAttribute;
};
}
