/// <summary>
/// Name: System::Reflection::AssemblyInformationalVersionAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection {
class AssemblyInformationalVersionAttribute {
public:
    inline static _TypePtr _AssemblyInformationalVersionAttribute;
};
}
