/// <summary>
/// Name: System::Reflection::AssemblyFileVersionAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection {
class AssemblyFileVersionAttribute {
public:
    inline static _TypePtr _AssemblyFileVersionAttribute;
};
}
