/// <summary>
/// Name: System::Reflection::AssemblyKeyNameAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection {
class AssemblyKeyNameAttribute {
public:
    inline static _TypePtr _AssemblyKeyNameAttribute;
};
}
