/// <summary>
/// Name: System::Reflection::AssemblyNameFlags
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection {
class AssemblyNameFlags {
public:
    inline static _TypePtr _AssemblyNameFlags;
};
}
