/// <summary>
/// Name: System::Reflection::AssemblyTrademarkAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection {
class AssemblyTrademarkAttribute {
public:
    inline static _TypePtr _AssemblyTrademarkAttribute;
};
}
