/// <summary>
/// Name: System::Reflection::AssemblyName
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection {
class AssemblyName {
public:
    inline static _TypePtr _AssemblyName;
};
}
