/// <summary>
/// Name: System::Reflection::AssemblyDelaySignAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection {
class AssemblyDelaySignAttribute {
public:
    inline static _TypePtr _AssemblyDelaySignAttribute;
};
}
