/// <summary>
/// Name: System::Reflection::AssemblyAlgorithmIdAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection {
class AssemblyAlgorithmIdAttribute {
public:
    inline static _TypePtr _AssemblyAlgorithmIdAttribute;
};
}
