/// <summary>
/// Name: System::Reflection::AssemblyDescriptionAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection {
class AssemblyDescriptionAttribute {
public:
    inline static _TypePtr _AssemblyDescriptionAttribute;
};
}
