/// <summary>
/// Name: System::Reflection::AssemblyCultureAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection {
class AssemblyCultureAttribute {
public:
    inline static _TypePtr _AssemblyCultureAttribute;
};
}
