/// <summary>
/// Name: System::Reflection::AssemblyKeyFileAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection {
class AssemblyKeyFileAttribute {
public:
    inline static _TypePtr _AssemblyKeyFileAttribute;
};
}
