/// <summary>
/// Name: System::Reflection::AssemblyProductAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection {
class AssemblyProductAttribute {
public:
    inline static _TypePtr _AssemblyProductAttribute;
};
}
