/// <summary>
/// Name: System::Reflection::AssemblyDefaultAliasAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection {
class AssemblyDefaultAliasAttribute {
public:
    inline static _TypePtr _AssemblyDefaultAliasAttribute;
};
}
