/// <summary>
/// Name: System::Reflection::AssemblyFlagsAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection {
class AssemblyFlagsAttribute {
public:
    inline static _TypePtr _AssemblyFlagsAttribute;
};
}
