/// <summary>
/// Name: System::Reflection::Assembly
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection {
class Assembly {
public:
    inline static _TypePtr _Assembly;
};
}
