/// <summary>
/// Name: System::Reflection::AssemblyConfigurationAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection {
class AssemblyConfigurationAttribute {
public:
    inline static _TypePtr _AssemblyConfigurationAttribute;
};
}
