/// <summary>
/// Name: System::Reflection::BindingFlags
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection {
class BindingFlags {
public:
    inline static _TypePtr _BindingFlags;
};
}
