/// <summary>
/// Name: System::Reflection::Binder
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection {
class Binder {
public:
    inline static _TypePtr _Binder;
};
}
