/// <summary>
/// Name: System::Reflection::CallingConventions
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection {
class CallingConventions {
public:
    inline static _TypePtr _CallingConventions;
};
}
