/// <summary>
/// Name: System::Reflection::ConstructorInfo
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection {
class ConstructorInfo {
public:
    inline static _TypePtr _ConstructorInfo;
};
}
