/// <summary>
/// Name: System::Reflection::CustomAttributeFormatException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection {
class CustomAttributeFormatException {
public:
    inline static _TypePtr _CustomAttributeFormatException;
};
}
