/// <summary>
/// Name: System::Reflection::CustomAttributeTypedArgument
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection {
class CustomAttributeTypedArgument {
public:
    inline static _TypePtr _CustomAttributeTypedArgument;
};
}
