/// <summary>
/// Name: System::Reflection::CustomAttributeNamedArgument
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection {
class CustomAttributeNamedArgument {
public:
    inline static _TypePtr _CustomAttributeNamedArgument;
};
}
