/// <summary>
/// Name: System::Reflection::CustomAttributeData
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection {
class CustomAttributeData {
public:
    inline static _TypePtr _CustomAttributeData;
};
}
