/// <summary>
/// Name: System::Reflection::DefaultMemberAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection {
class DefaultMemberAttribute {
public:
    inline static _TypePtr _DefaultMemberAttribute;
};
}
