/// <summary>
/// Name: System::Reflection::EventInfo
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection {
class EventInfo {
public:
    inline static _TypePtr _EventInfo;
};
}
