/// <summary>
/// Name: System::Reflection::EventAttributes
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection {
class EventAttributes {
public:
    inline static _TypePtr _EventAttributes;
};
}
