/// <summary>
/// Name: System::Reflection::ExceptionHandlingClause
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection {
class ExceptionHandlingClause {
public:
    inline static _TypePtr _ExceptionHandlingClause;
};
}
