/// <summary>
/// Name: System::Reflection::ExceptionHandlingClauseOptions
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection {
class ExceptionHandlingClauseOptions {
public:
    inline static _TypePtr _ExceptionHandlingClauseOptions;
};
}
