/// <summary>
/// Name: System::Reflection::FieldAttributes
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection {
class FieldAttributes {
public:
    inline static _TypePtr _FieldAttributes;
};
}
