/// <summary>
/// Name: System::Reflection::FieldInfo
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection {
class FieldInfo {
public:
    inline static _TypePtr _FieldInfo;
};
}
