/// <summary>
/// Name: System::Reflection::GenericParameterAttributes
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection {
class GenericParameterAttributes {
public:
    inline static _TypePtr _GenericParameterAttributes;
};
}
