/// <summary>
/// Name: System::Reflection::ICustomAttributeProvider
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection {
class ICustomAttributeProvider {
public:
    inline static _TypePtr _ICustomAttributeProvider;
};
}
