/// <summary>
/// Name: System::Reflection::ImageFileMachine
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection {
class ImageFileMachine {
public:
    inline static _TypePtr _ImageFileMachine;
};
}
