/// <summary>
/// Name: System::Reflection::InterfaceMapping
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection {
class InterfaceMapping {
public:
    inline static _TypePtr _InterfaceMapping;
};
}
