/// <summary>
/// Name: System::Reflection::InvalidFilterCriteriaException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection {
class InvalidFilterCriteriaException {
public:
    inline static _TypePtr _InvalidFilterCriteriaException;
};
}
