/// <summary>
/// Name: System::Reflection::IReflect
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection {
class IReflect {
public:
    inline static _TypePtr _IReflect;
};
}
