/// <summary>
/// Name: System::Reflection::LocalVariableInfo
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection {
class LocalVariableInfo {
public:
    inline static _TypePtr _LocalVariableInfo;
};
}
