/// <summary>
/// Name: System::Reflection::ManifestResourceInfo
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection {
class ManifestResourceInfo {
public:
    inline static _TypePtr _ManifestResourceInfo;
};
}
