/// <summary>
/// Name: System::Reflection::MemberFilter
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection {
class MemberFilter {
public:
    inline static _TypePtr _MemberFilter;
};
}
