/// <summary>
/// Name: System::Reflection::MemberTypes
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection {
class MemberTypes {
public:
    inline static _TypePtr _MemberTypes;
};
}
