/// <summary>
/// Name: System::Reflection::MemberInfo
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection {
class MemberInfo {
public:
    inline static _TypePtr _MemberInfo;
};
}
