/// <summary>
/// Name: System::Reflection::MethodInfo
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection {
class MethodInfo {
public:
    inline static _TypePtr _MethodInfo;
};
}
