/// <summary>
/// Name: System::Reflection::MethodAttributes
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection {
class MethodAttributes {
public:
    inline static _TypePtr _MethodAttributes;
};
}
