/// <summary>
/// Name: System::Reflection::MethodImplAttributes
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection {
class MethodImplAttributes {
public:
    inline static _TypePtr _MethodImplAttributes;
};
}
