/// <summary>
/// Name: System::Reflection::MethodBase
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection {
class MethodBase {
public:
    inline static _TypePtr _MethodBase;
};
}
