/// <summary>
/// Name: System::Reflection::MethodBody
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection {
class MethodBody {
public:
    inline static _TypePtr _MethodBody;
};
}
