/// <summary>
/// Name: System::Reflection::ModuleResolveEventHandler
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection {
class ModuleResolveEventHandler {
public:
    inline static _TypePtr _ModuleResolveEventHandler;
};
}
