/// <summary>
/// Name: System::Reflection::Module
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection {
class Module {
public:
    inline static _TypePtr _Module;
};
}
