/// <summary>
/// Name: System::Reflection::ObfuscationAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection {
class ObfuscationAttribute {
public:
    inline static _TypePtr _ObfuscationAttribute;
};
}
