/// <summary>
/// Name: System::Reflection::ObfuscateAssemblyAttribute
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection {
class ObfuscateAssemblyAttribute {
public:
    inline static _TypePtr _ObfuscateAssemblyAttribute;
};
}
