/// <summary>
/// Name: System::Reflection::ParameterModifier
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection {
class ParameterModifier {
public:
    inline static _TypePtr _ParameterModifier;
};
}
