/// <summary>
/// Name: System::Reflection::ParameterAttributes
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection {
class ParameterAttributes {
public:
    inline static _TypePtr _ParameterAttributes;
};
}
