/// <summary>
/// Name: System::Reflection::ParameterInfo
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection {
class ParameterInfo {
public:
    inline static _TypePtr _ParameterInfo;
};
}
