/// <summary>
/// Name: System::Reflection::Pointer
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection {
class Pointer {
public:
    inline static _TypePtr _Pointer;
};
}
