/// <summary>
/// Name: System::Reflection::PortableExecutableKinds
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection {
class PortableExecutableKinds {
public:
    inline static _TypePtr _PortableExecutableKinds;
};
}
