/// <summary>
/// Name: System::Reflection::ProcessorArchitecture
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection {
class ProcessorArchitecture {
public:
    inline static _TypePtr _ProcessorArchitecture;
};
}
