/// <summary>
/// Name: System::Reflection::PropertyAttributes
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection {
class PropertyAttributes {
public:
    inline static _TypePtr _PropertyAttributes;
};
}
