/// <summary>
/// Name: System::Reflection::PropertyInfo
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection {
class PropertyInfo {
public:
    inline static _TypePtr _PropertyInfo;
};
}
