/// <summary>
/// Name: System::Reflection::ReflectionTypeLoadException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection {
class ReflectionTypeLoadException {
public:
    inline static _TypePtr _ReflectionTypeLoadException;
};
}
