/// <summary>
/// Name: System::Reflection::ResourceAttributes
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection {
class ResourceAttributes {
public:
    inline static _TypePtr _ResourceAttributes;
};
}
