/// <summary>
/// Name: System::Reflection::ResourceLocation
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection {
class ResourceLocation {
public:
    inline static _TypePtr _ResourceLocation;
};
}
