/// <summary>
/// Name: System::Reflection::StrongNameKeyPair
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection {
class StrongNameKeyPair {
public:
    inline static _TypePtr _StrongNameKeyPair;
};
}
