/// <summary>
/// Name: System::Reflection::TargetException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection {
class TargetException {
public:
    inline static _TypePtr _TargetException;
};
}
