/// <summary>
/// Name: System::Reflection::TargetParameterCountException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection {
class TargetParameterCountException {
public:
    inline static _TypePtr _TargetParameterCountException;
};
}
