/// <summary>
/// Name: System::Reflection::TargetInvocationException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection {
class TargetInvocationException {
public:
    inline static _TypePtr _TargetInvocationException;
};
}
