/// <summary>
/// Name: System::Reflection::TypeFilter
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection {
class TypeFilter {
public:
    inline static _TypePtr _TypeFilter;
};
}
