/// <summary>
/// Name: System::Reflection::TypeAttributes
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection {
class TypeAttributes {
public:
    inline static _TypePtr _TypeAttributes;
};
}
