/// <summary>
/// Name: System::Reflection::TypeDelegator
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Reflection {
class TypeDelegator {
public:
    inline static _TypePtr _TypeDelegator;
};
}
