/// <summary>
/// Name: System::Security::Cryptography::X509Certificates::X509Certificate
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::Cryptography::X509Certificates {
class X509Certificate {
public:
    inline static _TypePtr _X509Certificate;
};
}
