/// <summary>
/// Name: System::Security::AccessControl::AccessControlModification
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::AccessControl {
class AccessControlModification {
public:
    inline static _TypePtr _AccessControlModification;
};
}
