/// <summary>
/// Name: System::Security::AccessControl::AccessControlActions
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::AccessControl {
class AccessControlActions {
public:
    inline static _TypePtr _AccessControlActions;
};
}
