/// <summary>
/// Name: System::Security::AccessControl::AccessRule
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::AccessControl {
class AccessRule {
public:
    inline static _TypePtr _AccessRule;
};
}
