/// <summary>
/// Name: System::Security::AccessControl::AccessControlType
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::AccessControl {
class AccessControlType {
public:
    inline static _TypePtr _AccessControlType;
};
}
