/// <summary>
/// Name: System::Security::AccessControl::AccessControlSections
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::AccessControl {
class AccessControlSections {
public:
    inline static _TypePtr _AccessControlSections;
};
}
