/// <summary>
/// Name: System::Security::AccessControl::AceEnumerator
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::AccessControl {
class AceEnumerator {
public:
    inline static _TypePtr _AceEnumerator;
};
}
