/// <summary>
/// Name: System::Security::AccessControl::AceFlags
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::AccessControl {
class AceFlags {
public:
    inline static _TypePtr _AceFlags;
};
}
