/// <summary>
/// Name: System::Security::AccessControl::AceQualifier
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::AccessControl {
class AceQualifier {
public:
    inline static _TypePtr _AceQualifier;
};
}
