/// <summary>
/// Name: System::Security::AccessControl::AceType
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::AccessControl {
class AceType {
public:
    inline static _TypePtr _AceType;
};
}
