/// <summary>
/// Name: System::Security::AccessControl::AuditFlags
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::AccessControl {
class AuditFlags {
public:
    inline static _TypePtr _AuditFlags;
};
}
