/// <summary>
/// Name: System::Security::AccessControl::AuthorizationRule
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::AccessControl {
class AuthorizationRule {
public:
    inline static _TypePtr _AuthorizationRule;
};
}
