/// <summary>
/// Name: System::Security::AccessControl::AuthorizationRuleCollection
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::AccessControl {
class AuthorizationRuleCollection {
public:
    inline static _TypePtr _AuthorizationRuleCollection;
};
}
