/// <summary>
/// Name: System::Security::AccessControl::CommonAcl
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::AccessControl {
class CommonAcl {
public:
    inline static _TypePtr _CommonAcl;
};
}
