/// <summary>
/// Name: System::Security::AccessControl::CommonAce
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::AccessControl {
class CommonAce {
public:
    inline static _TypePtr _CommonAce;
};
}
