/// <summary>
/// Name: System::Security::AccessControl::CommonObjectSecurity
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::AccessControl {
class CommonObjectSecurity {
public:
    inline static _TypePtr _CommonObjectSecurity;
};
}
