/// <summary>
/// Name: System::Security::AccessControl::CommonSecurityDescriptor
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::AccessControl {
class CommonSecurityDescriptor {
public:
    inline static _TypePtr _CommonSecurityDescriptor;
};
}
