/// <summary>
/// Name: System::Security::AccessControl::CompoundAce
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::AccessControl {
class CompoundAce {
public:
    inline static _TypePtr _CompoundAce;
};
}
