/// <summary>
/// Name: System::Security::AccessControl::CompoundAceType
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::AccessControl {
class CompoundAceType {
public:
    inline static _TypePtr _CompoundAceType;
};
}
