/// <summary>
/// Name: System::Security::AccessControl::ControlFlags
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::AccessControl {
class ControlFlags {
public:
    inline static _TypePtr _ControlFlags;
};
}
