/// <summary>
/// Name: System::Security::AccessControl::CryptoKeyRights
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::AccessControl {
class CryptoKeyRights {
public:
    inline static _TypePtr _CryptoKeyRights;
};
}
