/// <summary>
/// Name: System::Security::AccessControl::CryptoKeySecurity
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::AccessControl {
class CryptoKeySecurity {
public:
    inline static _TypePtr _CryptoKeySecurity;
};
}
