/// <summary>
/// Name: System::Security::AccessControl::CryptoKeyAuditRule
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::AccessControl {
class CryptoKeyAuditRule {
public:
    inline static _TypePtr _CryptoKeyAuditRule;
};
}
