/// <summary>
/// Name: System::Security::AccessControl::CryptoKeyAccessRule
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::AccessControl {
class CryptoKeyAccessRule {
public:
    inline static _TypePtr _CryptoKeyAccessRule;
};
}
