/// <summary>
/// Name: System::Security::AccessControl::CustomAce
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::AccessControl {
class CustomAce {
public:
    inline static _TypePtr _CustomAce;
};
}
