/// <summary>
/// Name: System::Security::AccessControl::DirectorySecurity
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::AccessControl {
class DirectorySecurity {
public:
    inline static _TypePtr _DirectorySecurity;
};
}
