/// <summary>
/// Name: System::Security::AccessControl::DirectoryObjectSecurity
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::AccessControl {
class DirectoryObjectSecurity {
public:
    inline static _TypePtr _DirectoryObjectSecurity;
};
}
