/// <summary>
/// Name: System::Security::AccessControl::DiscretionaryAcl
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::AccessControl {
class DiscretionaryAcl {
public:
    inline static _TypePtr _DiscretionaryAcl;
};
}
