/// <summary>
/// Name: System::Security::AccessControl::EventWaitHandleAccessRule
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::AccessControl {
class EventWaitHandleAccessRule {
public:
    inline static _TypePtr _EventWaitHandleAccessRule;
};
}
