/// <summary>
/// Name: System::Security::AccessControl::EventWaitHandleAuditRule
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::AccessControl {
class EventWaitHandleAuditRule {
public:
    inline static _TypePtr _EventWaitHandleAuditRule;
};
}
