/// <summary>
/// Name: System::Security::AccessControl::EventWaitHandleSecurity
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::AccessControl {
class EventWaitHandleSecurity {
public:
    inline static _TypePtr _EventWaitHandleSecurity;
};
}
