/// <summary>
/// Name: System::Security::AccessControl::EventWaitHandleRights
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::AccessControl {
class EventWaitHandleRights {
public:
    inline static _TypePtr _EventWaitHandleRights;
};
}
