/// <summary>
/// Name: System::Security::AccessControl::FileSystemSecurity
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::AccessControl {
class FileSystemSecurity {
public:
    inline static _TypePtr _FileSystemSecurity;
};
}
