/// <summary>
/// Name: System::Security::AccessControl::FileSystemAuditRule
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::AccessControl {
class FileSystemAuditRule {
public:
    inline static _TypePtr _FileSystemAuditRule;
};
}
