/// <summary>
/// Name: System::Security::AccessControl::FileSystemRights
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::AccessControl {
class FileSystemRights {
public:
    inline static _TypePtr _FileSystemRights;
};
}
