/// <summary>
/// Name: System::Security::AccessControl::FileSecurity
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::AccessControl {
class FileSecurity {
public:
    inline static _TypePtr _FileSecurity;
};
}
