/// <summary>
/// Name: System::Security::AccessControl::FileSystemAccessRule
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::AccessControl {
class FileSystemAccessRule {
public:
    inline static _TypePtr _FileSystemAccessRule;
};
}
