/// <summary>
/// Name: System::Security::AccessControl::GenericAce
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::AccessControl {
class GenericAce {
public:
    inline static _TypePtr _GenericAce;
};
}
