/// <summary>
/// Name: System::Security::AccessControl::GenericSecurityDescriptor
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::AccessControl {
class GenericSecurityDescriptor {
public:
    inline static _TypePtr _GenericSecurityDescriptor;
};
}
