/// <summary>
/// Name: System::Security::AccessControl::GenericAcl
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::AccessControl {
class GenericAcl {
public:
    inline static _TypePtr _GenericAcl;
};
}
