/// <summary>
/// Name: System::Security::AccessControl::InheritanceFlags
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::AccessControl {
class InheritanceFlags {
public:
    inline static _TypePtr _InheritanceFlags;
};
}
