/// <summary>
/// Name: System::Security::AccessControl::KnownAce
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::AccessControl {
class KnownAce {
public:
    inline static _TypePtr _KnownAce;
};
}
