/// <summary>
/// Name: System::Security::AccessControl::MutexAccessRule
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::AccessControl {
class MutexAccessRule {
public:
    inline static _TypePtr _MutexAccessRule;
};
}
