/// <summary>
/// Name: System::Security::AccessControl::MutexSecurity
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::AccessControl {
class MutexSecurity {
public:
    inline static _TypePtr _MutexSecurity;
};
}
