/// <summary>
/// Name: System::Security::AccessControl::MutexRights
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::AccessControl {
class MutexRights {
public:
    inline static _TypePtr _MutexRights;
};
}
