/// <summary>
/// Name: System::Security::AccessControl::MutexAuditRule
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::AccessControl {
class MutexAuditRule {
public:
    inline static _TypePtr _MutexAuditRule;
};
}
