/// <summary>
/// Name: System::Security::AccessControl::NativeObjectSecurity
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::AccessControl {
class NativeObjectSecurity {
public:
    inline static _TypePtr _NativeObjectSecurity;
};
}
