/// <summary>
/// Name: System::Security::AccessControl::ObjectAceFlags
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::AccessControl {
class ObjectAceFlags {
public:
    inline static _TypePtr _ObjectAceFlags;
};
}
