/// <summary>
/// Name: System::Security::AccessControl::ObjectAccessRule
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::AccessControl {
class ObjectAccessRule {
public:
    inline static _TypePtr _ObjectAccessRule;
};
}
