/// <summary>
/// Name: System::Security::AccessControl::ObjectAuditRule
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::AccessControl {
class ObjectAuditRule {
public:
    inline static _TypePtr _ObjectAuditRule;
};
}
