/// <summary>
/// Name: System::Security::AccessControl::ObjectAce
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::AccessControl {
class ObjectAce {
public:
    inline static _TypePtr _ObjectAce;
};
}
