/// <summary>
/// Name: System::Security::AccessControl::ObjectSecurity
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::AccessControl {
class ObjectSecurity {
public:
    inline static _TypePtr _ObjectSecurity;
};
}
