/// <summary>
/// Name: System::Security::AccessControl::PrivilegeNotHeldException
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::AccessControl {
class PrivilegeNotHeldException {
public:
    inline static _TypePtr _PrivilegeNotHeldException;
};
}
