/// <summary>
/// Name: System::Security::AccessControl::PropagationFlags
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::AccessControl {
class PropagationFlags {
public:
    inline static _TypePtr _PropagationFlags;
};
}
