/// <summary>
/// Name: System::Security::AccessControl::QualifiedAce
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::AccessControl {
class QualifiedAce {
public:
    inline static _TypePtr _QualifiedAce;
};
}
