/// <summary>
/// Name: System::Security::AccessControl::RawAcl
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::AccessControl {
class RawAcl {
public:
    inline static _TypePtr _RawAcl;
};
}
