/// <summary>
/// Name: System::Security::AccessControl::RawSecurityDescriptor
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::AccessControl {
class RawSecurityDescriptor {
public:
    inline static _TypePtr _RawSecurityDescriptor;
};
}
