/// <summary>
/// Name: System::Security::AccessControl::RegistryAccessRule
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::AccessControl {
class RegistryAccessRule {
public:
    inline static _TypePtr _RegistryAccessRule;
};
}
