/// <summary>
/// Name: System::Security::AccessControl::RegistrySecurity
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::AccessControl {
class RegistrySecurity {
public:
    inline static _TypePtr _RegistrySecurity;
};
}
