/// <summary>
/// Name: System::Security::AccessControl::RegistryAuditRule
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::AccessControl {
class RegistryAuditRule {
public:
    inline static _TypePtr _RegistryAuditRule;
};
}
