/// <summary>
/// Name: System::Security::AccessControl::RegistryRights
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::AccessControl {
class RegistryRights {
public:
    inline static _TypePtr _RegistryRights;
};
}
