/// <summary>
/// Name: System::Security::AccessControl::ResourceType
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::AccessControl {
class ResourceType {
public:
    inline static _TypePtr _ResourceType;
};
}
