/// <summary>
/// Name: System::Security::AccessControl::SecurityInfos
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::AccessControl {
class SecurityInfos {
public:
    inline static _TypePtr _SecurityInfos;
};
}
