/// <summary>
/// Name: System::Security::AccessControl::SystemAcl
/// Generated By: ProxyGenerator
/// Notice: Don't edit
/// <summary>

#pragma once
#include "DotNetHelper.h"

namespace System::Security::AccessControl {
class SystemAcl {
public:
    inline static _TypePtr _SystemAcl;
};
}
